<?php
$sermon = '2';
include 'header.php';
?>
<div data-ident="02-000" class="commenthidden" ><p>Sermon Two of the 36 Lessons illustrates the efforts of more Daedra to impart knowledge to Vivec during his incubation.  He grows further, both conceptually and physically, changing as he absorbs.</p> <p>At the end of this Sermon we watch as Mephala imparts her essence into Vivec in a horrifying but beautiful event.</p> <p class="horizline"></p> <p>In Morrowind, Sermon Two grants a bonus to the Alchemy skill.  It is worth 200 Septims and weighs 3 units.  A copy can be found in the <a class="external" href="http://www.uesp.net/wiki/Morrowind:Andas_Ancestral_Tomb" target="_blank">Andas Ancestral Tomb</a> and in <a class="external" href="http://www.uesp.net/wiki/Morrowind:Vivec_Temple" taget="_blank">High Fane</a> in Vivec city.  A copy is also sold by <a class="external" href="http://www.uesp.net/wiki/Morrowind:Bervaso_Thenim" target="_blank">Bervaso Thenim</a> in Molag Mar.</p> <p>Sermon 29 names this Sermon "The Enantiomorph."  Its number is 68, which corresponds to the word "was."</p></div>
<div data-ident="02-001" class="commenthidden" ><p>Daedra could also be described as "spirits," although none of the spirits mentioned in this Sermon are named as Daedra, with the exception of Mephala, at the end.  So we could assume that the spirits in this Sermon are not Daedra, but perhaps the spirits of Dunmer ancestors.  This idea is somewhat reinforced by the mention of mortal spirits and the Incalculable Effort in Sermon 35.</p></div>
<div data-ident="02-002" class="commenthidden" ><p>The "future" warrior-poet, because that is what Vivec will become, not what he currently is.  Therefore Vivec was not born a God, and instead evolved over time as an Egg.  When he is eventually "born," in Sermon 8, he will become the true Warrior-Poet, although that event will not mark the apex of his power.</p></div>
<div data-ident="02-003" class="commenthidden" ><p>We can understand calling Vivec a "Warrior-Poet," because he is the combination of Sotha Sil (Words) and Almalexia (Swords), as noted earlier in Sermon 1.  But why "invisible?"  This likely has its roots in the description of Vivec in Sermon 1 as having "invisible knowledge of words and swords," but that doesn't really help us much.</p> <p>All I can offer here is guesses.  Maybe the knowledge is "invisible" because it is only knowledge, and not physical like weaponry or armor.  Maybe it's "invisible" because it's difficult to discern and therefore obscure and hard to learn.  Perhaps it's "invisible" because it is hidden within Vivec the Thief, who is hidden by nature.</p> <p>All guesses, no solid answers.  And if this bugs you, by the way, stop reading now.  Seriously.  It's gonna get worse.</p></div>
<div data-ident="02-004" class="commenthidden" ><p>Is it conspicuous that this "hugging" resembles affection, and by extension, Love?</p></div>
<div data-ident="02-005" class="commenthidden" ><p>Incalculable Effort is an interesting term.  It's mentioned later in Sermon 35 and by the Loveletter as being a requirement for the Amaranth event, and by extension the entire purpose of Mundus as a creation.  However, the term <em>probably</em> can be taken somewhat literally, in this case, as meaning "great knowledge."  When the Wife becomes "soaked" in that knowledge, Vehk absorbs it, learning from the first spirit.</p><p>But let's read a little deeper.  Consider a point at which the concepts of "knowledge" and "effort" intersect.  It could be that the "incalculable effort" is not an evolution or maturation of intellectual prowess, but rather a ripening of karmic destiny, the collective "effort" of a person or people to spiritually progress towards enlightenment.</p><p>If you think about it that way, the first spirit is imparting a combination of wisdom, destiny, and spirituality to Vivec.  And in Sermon 35, this subject is going to come up again.</p></div>
<div data-ident="02-006" class="commenthidden" ><p>It's often said in the 36 Lessons, and elsewhere, that "the World" has five corners.  But the use of the term "World" might be deceptive.  For example, Vivec often talks about being a "ruling king of this world," but it is uncertain if he means all of Nirn, or just Morrowind, or the entire span of Mundus.  And Vivec also speaks of Dagoth Ur, saying "There is a world that is sleeping and you must guard against it."  This many variations of meaning leads me to suspect that the word is not intended to mean the same thing every time.</p> <p>Let's argue therefore that, in at least this particular case, "World" means "Nirn," the plane(t) and basically nothing else.  If that's the case, Nirn can be said to have "five corners" because Nirn can be thought of as a metaphor for a Body, perhaps Lorkhan's, or Nir's if you're reading the <a class="external" href="http://www.uesp.net/wiki/Morrowind:The_Annotated_Anuad" target="_blank">Annotated Anuad</a>.  Then the Five Corners likely resemble the five limbs of a body, the Head, both Arms, and both Legs.  The connection with a pentacle is likely <a class="imgModal" href="../css/images/Da_Vinci_Vitruvian_Man.jpg">not accidental</a>.  And by the way, bonus credit if you can count how many limbs are in that picture.  Eight?  Eight limbs?</p><p>But if the World has Five Corners, and therefore is also a body, what other implications does that have?  Does the World have a nervous system?</p> <p>Does it have a brain?</p></div>
<div data-ident="02-007" class="commenthidden" ><p>It's been suggested to me that this is a nod to Crowley again, to a line in The Book of the Law: "O be thou proud and mighty among men," but I don't think so.  The two lines have little to do with one another other than the use of "proud and mighty."  I suspect Vivec is simply stating that the imparting of knowledge and skill to another being is the holiest act a person can perform.</p></div>
<div data-ident="02-008" class="commenthidden" ><p>Hey, they forgot to include headache spells in Morrowind!  What the fuck, Bethesda?!?!?!</p></div>
<div data-ident="02-009" class="commenthidden" ><p>Again, another hyphenated name that makes us think of an Egyptian amalgamation God-figure.  I've not yet found any external links to At-Hatoor yet, though.  Although <em>damn</em> that dude can wear a garment.</p><p>Why are his "implications of meaning" written on his garments, though?  Consider the notion that a person's garments are intrinsically meaningless, not only because they are mere possessions, but also because a person might hide his true nature behind his garments, shamefully relying on clothing to present a false persona, as though hiding behind a mask.</p><p>This would suggest that At-Hatoor's garments, his "implications of meaning," are foolish and not to be trusted.  At-Hatoor intends to teach Vivec that he should not be distracted by implications, but by substance.  Vivec should concern himself only with the true nature of things.</p></div>
<div data-ident="02-010" class="commenthidden" ><p>That's a huge mushroom, by the way.  Not an umbrella.  Just making sure we're on the same page.</p></div>
<div data-ident="02-011" class="commenthidden" ><p>So here we have it.  This is, as I often love to say, the whole point of TES Lore fandom.  We infer meaning in things devoid of detail.  The Elder Scrolls writers give us vague implications of meaning, and we study them and theorize and debate until we come up with an explanation or two.</p> <p>It becomes a little bit like scholarly debate, which is why we often call ourselves lore "scholars."  You can do more for your position with a few references than without, for example.</p> <p>But the best part about Elder Scrolls lore, the absolute best part, is that the developers know we're doing this.  With every new Elder Scrolls game the developers try very hard to not confirm or deny what may have happened in the last game.  Was the Nerevarine a Dunmer and the head of House Telvanni?  Or was he Imperial and head of the Warrior's Guild?  No mention is made of this in Oblivion, the game that followed.</p> <p>The Elder Scrolls series has always been about Freedom, and Bethesda tries to extend that theme to every corner of the games.</p> <p>Incidentally, it's also probable that At-Hatoor's line, "There is a proverb," is a reference to the 36 Lessons of Vivec themselves.  "Herein," he seems to say, "you will find implications of meaning.  Infer significance in things devoid of detail.  There is much hidden that is waiting to be found."  At-Hatoor is telling us that the 36 Lessons hold deeper meanings, and we have but to dig deep enough to find them.</p> <p>Of course, if you consider the approach I discussed earlier, that At-Hatoor's "implications of meaning" have no value, then connecting it to the Lore community is not terribly constructive.  This, again, returns to your personal perspective.  Is fandom valuable?  If not intrinsically valuable, then how can fandom be an avenue to creating value?  Perhaps the wealth of Elder Scrolls fandom is right here, in these conversations, in these intellectual explorations that help us better understand the world around us.</p></div>
<div data-ident="02-012" class="commenthidden" ><p>Since they are cousins, they are sons of two brothers, which by extension probably means that they are products of two different systems.  As we know, in TES, when you have two opposing systems, you're probably looking in the direction of an Enantiomorph.  We'll speak more on that in a later comment.  But keep in mind that, because they are related by blood, the two Cousins likely represent two ideas that are indivisible.</p></div>
<div data-ident="02-013" class="commenthidden" ><p>Ghost Touching isn't something that, to my knowledge, exists in any form in the Elder Scrolls games.  But it's pretty obvious that the Daedric Cousins are able to physically reach inside another person's physical body without damaging the flesh, like ethereal spirits passing through solid stone.</p></div>
<div data-ident="02-014" class="commenthidden" ><p>A star with its penumbra missing does somewhat resemble the human form, four long points and one stubby one at the top.  So perhaps this refers to Vivec's status as an almost-formed being, not nearly born, still developing in the womb, growing that last, fifth limb.</p> <p>But there's also another connection to be made here, that of Jung's concept of Mankind's inner divinity.  As he puts it (and I often quote): "Every man is a Star, every Star is a God."  This concept is echoed somewhat by Aleister Crowley, and Vehk's unfinished star-form might reference his status as an almost-God, forming, but not yet fully developed.  A child-deity, but a deity still.</p> <p>And let's do another one, just to round up to three.  If a Star has five points, and Nirn has five corners, is Nirn also a Star?  The major stars in the sky above Nirn are planets themselves, like Nirn.</p></div>
<div data-ident="02-015" class="commenthidden" ><p>Vanished Forms seems to say "concepts that have been lost," so in this case a "revival" of vanished forms sounds like Vivec reminds people of things that have come before, but have been gone from the world for some time.</p></div>
<div data-ident="02-016" class="commenthidden" ><p>I mentioned before that the two Cousins represent related concepts.  Although I'm not aware of any specific identity they might have, I can make a few guesses about their nature, and a few more about their meaning.</p> <p>One side offers a "series of calamities," that will end the universe.  That's some heavy stuff.  The other side doesn't offer a cure, but only offers "all the primordial marriages" that happen inside each calamity.  So a calamity will contain a "primordial marriage."  What's a primordial marriage?</p> <p>Again, we go back to the Enantiomorph.  A primordial marriage is the combination (marriage) of two basic (primordial) elements.  So the two Daedric cousins are the sons of two brothers, so they themselves are the products of primordial marriages.  And they warn Vivec of the Enantiomorphic events that are required to bring about the end of the universe.</p> <p>If this were any other document, a reader could just brush this off as "color," a concept intended to reinforce the idea that Vivec has been given great secrets by powerful entities.  And that would be in character for this kind of story, as it reinforces Vivec's divinity to say that he was granted such immense knowledge.  But if we did that, we'd be DOING IT WRONG.  There's another way to think about this.</p> <p>As we know, the Aurbis is part of a cycle, one that repeats endlessly in a cycle of "Kalpas," beginning with an event called "Convention" and ending when Alduin consumes reality.  So when the Cousins speak of "the end of the universe," they may well be referring to the end of this Kalpa, or perhaps the entire Aurbis itself.</p> <p>And maybe, just <em>maybe</em>, what they're really talking about is Landfall.  But we're getting ahead of ourselves.  And oh look!  This is the 16th comment in this Sermon.  Coincidence...?</p></div>
<div data-ident="02-017" class="commenthidden" ><p>Well, this could be, like so many other things, another moment used to illustrate how confident Vivec is, how easily he accepts his god-like nature, as though he was born to be a God.  And that's largely the purpose of the 36 Lessons, to illustrate how natural Vivec's God-destiny was.  But there are two other things we might be able to take from this line.</p> <p>The first is the possibility that Vivec is referring to past lives, as though the Elder Scrolls universe might have something that resembles the concept of reincarnation, or perhaps that he is the incarnation of a greater deity, in the same way that <a class="external" href="http://en.wikipedia.org/wiki/Vishnu" target="_blank">Vishnu</a> reincarnates as <a class="external" href="http://en.wikipedia.org/wiki/Krishna" target="_blank">Krishna</a>.  But that's an easy one.</p> <p>The more interesting idea (to me, anyway) is that Vivec, in writing the 36 Lessons, is somewhat embarrassed by the fear he may have felt when he first realized the true future of the Aurbis.  When, during the earliest moments of his freshly stolen God-like perception, what he saw was so frightening that, as he re-wrote his past mortality into a more pleasing form, he might have "overcompensated" a bit.</p> <p>Or perhaps, by this stage of development, Vivec-as-Egg simply didn't understand the full enormity of what had been laid at his feet.</p></div>
<div data-ident="02-018" class="commenthidden" ><p>So here we have it.  At last, the Daedric Prince of whom Vivec is the anticipation.  There's quite a lot about Mephala that can be said, and I've said most of it in a separate essay, but for the moment let's talk about why Vivec is Mephala's anticipation instead of some other Daedric Prince.</p> <p>Mephala is known as the Daedric Prince of Sex and Murder, and this may not be any more reason than is needed to associate her with Vivec, who is inspired heavily by <a class="external" href="http://en.wikipedia.org/wiki/Ardhanarishvara" target="_blank">Ardhanarishvara</a>, the androgynous combination of the Hindu God Shiva (the Destroyer) and Parvati (Fertility).  And so there's your Sex and Murder connection right there.</p> <p>But in addition to that, Vivec represents the joining of dualities, and as such he is the unifying force between two opposite but "confused" entities.  I say "confused" because Sotha Sil and Almalexia are contradictory.  Almalexia represents the Warrior, who is stasis, yet she is feminine, and as such associated with creation and birth.  And yet Sotha Sil is the Mage, associated with creation, and yet he is masculine.  How could these two contradictions ever unify themselves to become Gods?</p> <p>And Mephala's "Black Hands" represent another duality, Terror and Theory.  But we'll deal with that later.</p> <p>Vivec is that unification.  By combining all aspects of both opposites into himself, he becomes the unifying force in the Triune that allows them to elevate to a pure form of existence.</p></div>
<div data-ident="02-019" class="commenthidden" ><p>Is it possible that Vivec had been reincarnated?  I must've been born before...  Or is Vivec so in touch with the nature of the universe that he is able to recall his proper form from the moment of the world's creation, and thus he is not capable of being wounded, even by the Daedra's power?</p><p>Considering the suggestion MK made of Vivec's role in the formation of the Amaranth in C0DA, we might even assume that Vivec is aware, even at this moment, of his destiny.  A destiny laid down from the moment of Nirn's creation, from the instant Anu's dream began.</p></div>
<div data-ident="02-020" class="commenthidden" ><p>Perhaps this is the very instant that Vivec became Mephala's Anticipation.  He takes Mephala's skill and knowledge, suggesting that Vivec is now more like Mephala than Mephala herself.</p></div>
<div data-ident="02-021" class="commenthidden" ><p>This seems to imply that the Daedra are wound so deeply with the structure of Mundus that, should one be destroyed, it would unravel the fabric of the world itself.  Perhaps this suggests that they are much like the Aedra, in that respect.  In the model of the Wheel, they are the voids between the spokes, and surely the space between is as important as their opposites?</p></div>
<div data-ident="02-022" class="commenthidden" ><p>I'm not sure, but I think this is another reference to the idea of an enantiomorphic event, which seems likely considering Sermon 29 calls this Sermon "The Enantiomorph."  Here, Vivec combines himself with Mephala, and to make it real, Mepahala makes sure that Vivec's "mother" remains wounded, blinded.  As though the betrayal and injury work like an official seal of authentication.  "This event happened," it seems to say, "and here are the scars that prove it so."</p> <p>Perhaps we are also watching Vivec mantle Mephala, in a strange way.</p></div>
<div data-ident="02-023" class="commenthidden" ><p>Of Birth: Almalexia.</p> <p>Of Machines: Sotha Sil.</p> <p>The Words Between: Vivec, the Warrior Poet, the words between Sotha and Alma that bind the two together.</p></div>
<div data-ident="02-024" class="commenthidden" ><p>Lots of ways to interpret this.  Though the half-key mentioned is probably Vivec, which half is mentioned?  I'd suggest that either Vivec is, at this point, "half-made,"  which is possible, or that Mephala represents half of Vivec.  Or Vivec is the half because he represents (as the anticipation) half of Mephala.</p> <p>Or perhaps Mephala represents the half-key?</p></div>
<div data-ident="02-025" class="commenthidden" ><p>So what did Sermon 2 teach us?  We've watched Vivec collect more power and knowledge while he laughs off his approaching divinity as though he was born to do it.  And we witnessed the enantiomorphic combination of the mortal(-ish) Vivec Egg and the Daedric Prince Mephala, where Vivec becomes the Anticipation of Mephala.</p></div>
<?php include 'middle.php' ?>
<p>The netchiman's wife who carried the egg of Vivec within her went looking for the lands of the Indoril. Along the journey <span class="lessonlink" data-call="02-001">many spirits</span> came to see her and offer instructions to her son-daughter, the <span class="lessonlink" data-call="02-002">future</span> glorious <span class="lessonlink" data-call="02-003">invisible warrior-poet</span> of Vvardenfell, Vivec.</p>
<p>The first spirit threw his arms about her and <span class="lessonlink" data-call="02-004">hugged his knowledge in tight</span>. The netchiman's wife became soaked in the <span class="lessonlink" data-call="02-005">Incalculable Effort</span>. The egg was delighted and did somersaults inside her, bowing to the <span class="lessonlink" data-call="02-006">five corners of the world</span> and saying:</p>
<p><span class="lessonlink" data-call="02-007">'Thus whoever performs this holy act shall be proud and mighty among the rest!'</span></p>
<p>The second spirit was too aloof and acted above his station so much that he was driven off by a <span class="lessonlink" data-call="02-008">headache spell</span>. The third spirit, <span class="lessonlink" data-call="02-009">At-Hatoor</span>, came down to the netchiman's wife while she relaxed for a while under an <span class="lessonlink" data-call="02-010">Emperor Parasol</span>. His garments were made from implications of meaning, and the egg looked at them three times. The first time Vivec said:</p>
<p>'Ha, it means nothing!'</p> <p>After looking a second time he said:</p>
<p>'Hmm, there might be something there after all.'</p>
<p>Finally, giving At-Hatoor's garments a sidelong glance, he said:</p>
<p>'Amazing, the ability to infer significance in something devoid of detail!'</p>
<p><span class="lessonlink" data-call="02-011">'There is a proverb,'</span> At-Hatoor said, and then he left.</p>
<p>The fourth spirit came with the fifth, for they were <span class="lessonlink" data-call="02-012">cousins</span>. They could <span class="lessonlink" data-call="02-013">ghost touch</span> and probed inside the egg to find its core. Some say Vivec at this point was shaped like <span class="lessonlink" data-call="02-014">a star with its penumbra broken off</span>; others, that it looked like <span class="lessonlink" data-call="02-015">a revival of vanished forms</span>.</p>
<p>'<span class="lessonlink" data-call="02-016">From my side of the family</span>,' the first cousin said, 'I bring you a series of calamities that will bring about the end of the universe.'</p>
<p>'And from my side,' the second cousin said, 'I bring you all the primordial marriages that must happen within them, each one.'</p> <p>At this the egg laughed. 'I am given too much to bear so young. <span class="lessonlink" data-call="02-017">I must have been born before</span>.'</p>
<p>And then the sixth spirit appeared, the <span class="lessonlink" data-call="02-018">Black Hands Mephala</span>, who taught the Velothi at the beginning of days all the arts of sex and murder. Its burning heart melted the eyes of the netchiman's wife and took the egg from her belly with six cutting strokes. The egg-image, however, <span class="lessonlink" data-call="02-019">could see into what it had been before in ancient times</span>, when the earth still cooled, and was not blinded.</p>
<p><span class="lessonlink" data-call="02-020">It joined with the Daedroth and took its former secrets</span>, leaving a few behind <span class="lessonlink" data-call="02-021">to keep the web of the world from disentangling</span>. Then the Black Hands Mephala put the egg back into the netchiman's wife and blew on her with magic breath until the hole closed up. <span class="lessonlink" data-call="02-022">But the Daedroth did not give her back her eyes</span>, saying:</p>
<p>'God hath three keys; <span class="lessonlink" data-call="02-023">of birth, of machines, and of the words between</span>.'</p>
<p>Within this Sermon the wise may find <span class="lessonlink" data-call="02-024">one half</span> of these keys.</p>
<p><span class="lessonlink" data-call="02-025">The ending of the words is ALMSIVI</span><a href="../css/images/36rages/<?php echo pad($sermon); ?>.png">.</a></p>
<?php include 'footer.php' ?>