<?php
$sermon = '3';
include 'header.php';
?>
<div class="commenthidden" data-ident="03-000"><p>Sermon Three of the 36 Lessons grants us a rare glimpse into the lives of the Dwemer and demonstrates how perplexed and confused the Deep Mer are by the concept of Love.  We also get to analyze Vivec's Prayer, an important element in one of the plot threads of the 36 Lessons.</p><p class="horizline"></p> <p>In Morrowind, Sermon Three grants a bonus to the Blunt Weapon skill.  It is worth 200 Septims and weighs 3 units.  A copy can be found in Raram's House in <a class="external" href="http://www.uesp.net/wiki/Morrowind:Indarys_Manor" target="_blank">Indarys Manor</a>, in Tureynulal at Kagrenac's Library, and in the Hall of Justice Secret Library in Vivec. <p>Sermon 29 names this Sermon "The Invisible Gate, ALMSIVI."  Its number is 242, which corresponds to the word "not."</p></div>
<div class="commenthidden" data-ident="03-001"><p>The Dwemer are often the fixation of many TES fans, mostly because of how strange and unusual they seem.  Originally, in the early Elder Scrolls games, the Dwemer were intended to be the Elder Scrolls universe's version of more traditional Dwarves - industrious, antisocial, and obsessed with the deep places of the world.</p> <p>In later games, the Dwemer became something unique.  Enigmatic masters of high technology, they seem almost completely alien to TES fans, and this is not an accident, as Bethesda writers have repeatedly expressed that they do not intend the Dwemer to be able to be understood.  Some fictional universes can seem somehow more authentic if they cannot be fully explained.</p> <p>If this inscrutable nature wasn't enough to stress their relationship with other races, the Dwemer are also unique in the Elder Scrolls universe because they do not have an organized form of religion, or at least not an easily recognizable one.  Dwemer storybooks and spoken history seem to indicate that they felt that there was no difference between Mortal and God except what power a given being could demonstrate.  The Dwemer felt that no God was infallible, and that divinity was merely a state of existence that could be achieved by any Mortal who simply possessed the proper knowledge.  To the Dunmer, who can walk out of their front door and look their Gods in the eyes, these opinions are particularly difficult to tolerate.</p> <p>Though the Dwemer occupy massive underground strongholds in many of Tamriel's provinces, Morrowind is perhaps the largest home to the Dwemeri clans.  At this point in history, Dwemer/Dunmer politics are stressed and probably result in frequent, but small, armed conflicts.</p></div>
<div class="commenthidden" data-ident="03-002"><p>I wonder how they "spied" it?  Other than the sight of a pregnant Chimer, what other indications were there, unless they "saw" with a different sort of sight?</p></div>
<div class="commenthidden" data-ident="03-003"><p>A simulacrum is a simplistic duplication.  A Dwemer robot, in other words, intended to fool the Chimer, although we'll soon see that it doesn't work as intended.</p></div>
<div class="commenthidden" data-ident="03-004"><p>What on earth could the Dunmer have that is "akin" to what the Dwemer have?  Are they talking about Vivec, and the Dwemer have something like Vivec?  I think this might be a safe bet.  Consider Vivec as the Dunmer equivalent of a "super-weapon," or part of the "super-weapon" that is ALMSIVI.  The Dwemer at this time are constructing their own God, Anumidium.  If this is the case, it's easy to see how the Velothi would "covet" it, which is to say, they would search for it if they knew it were missing.</p></div>
<div class="commenthidden" data-ident="03-005"><p>Clearly this is a fairly straight-forward approach, using knives to cut out the Vehk-Egg.  It might seem odd that the Dwemer might approach things so directly.</p></div>
<div class="commenthidden" data-ident="03-006"><p>Solid Sounds is an interesting concept.  We already know from other sources that the Dwemer practice something called "Tonal Architecture."  That term is never explained in plain language, but it's fairly easy to guess that it involves creating architecture, or perhaps structures in the general sense, out of sound.  My guess is that Solid Sounds is another word for Tonal Architecture, and here we are seeing the technique employed for purposes other than construction.</p></div>
<div class="commenthidden" data-ident="03-007"><p>Knives?  Nope.  Tonal Architecture?  Nope.  Great big goddamn blowtorch?  Nope.  Vivec's mother-womb is mighty resilient, almost certainly by benefit of carrying the unborn Egg-God inside of her.</p></div>
<div class="commenthidden" data-ident="03-008"><p>Ah, the Dwemer.  Always enigmatic.</p><p>Kirkbride has mentioned in the past that he prefers the Dwemer to remain unexplainable, thinking that the Elder Scrolls setting benefits from elements that simply cannot be comprehended.  This is a good example, the idea that the Dwemer intentionally misinterpret information.</p><p>You might ask yourself: "Are they doing this holistically?  Letting intuition or blind luck or fate steer their decisions?"  I wouldn't discourage such exploration, but keep in mind that, in a way, the Dwemer might be best suited to remaining an unsolvable mystery.  Every element in a fantasy setting serves a purpose.  The Dwemer serve as a head-scratcher.</p></div>
<div class="commenthidden" data-ident="03-009"><p>Okay, Vivec's Prayer is a pretty important piece of the 36 Lessons, and I'm going to refer to it more than a few times in later lessons.  Get used to hearing about it.</p><p>I'm pretty positive that the prayer's primary purpose is to bring peace to people who are preparing to pass on, and Vivec uses it here to console hir mother-host just before her death.  How does it bring peace?  It depends on how you personally interpret the poem, but I'm going to break down the components first and then offer a summary.</p></div>
<div class="commenthidden" data-ident="03-010"><p>When Vivec speaks of "fire," ze often means a divine form of knowledge that brings about power, but the true meaning is a lot more complex and spiritual than that.  So complex that <a href="../essays/fireofvivec.php">I had to write an essay about it</a>.</p></div>
<div class="commenthidden" data-ident="03-011"><p>Imagine a "safe room," a tiny hideaway where the threatened can find peace and safety.  The Secret Door leads there.</p></div>
<div class="commenthidden" data-ident="03-012"><p>It should be no surprise that Boethiah, a Daedra and Padomaic by nature, has an altar dedicated to Padhome.  The Secret Door is located there, in the most precious corner of Boethiah's House.  Does the Secret Door's location in the altar of Padhome speak to its nature?  Is it located there because it must, by nature, be closely assocated with Padhome?  Or is it there because (or due to) Boethiah's relationship to Padhome?</p></div>
<div class="commenthidden" data-ident="03-013"><p>Boethiah's House probably refers simply to a domain under Boethiah's influence, but it could well refer to Boethiah's Daedric plane in Oblivion, "Attribution's Share," (or "Snake Mount").  The general use of the term "House" in Morrowind often denoted a clan or family, but it could be extended to define a general realm of absolute authority.</p></div>
<div class="commenthidden" data-ident="03-014"><p>The most reasonable interpretation of this prayer is that Vivec is describing a "safe room," a hidden alcove in the House of Boethiah where a mortal's soul can find eternal rest and protection.  Finding this door in the House of Boethiah is important, as Boethiah is the origin of all Velothi religion and a kind and protecting Daedra in the eyes of the Chimer/Dunmer.  By being granted knowledge and entry through this "secret door," the mortal soul is rewarded with an afterlife where they become "safe, and looked after."</p> <p>The thought of being kept in such an existence is soothing to the soul, as a promise of a peaceful and pleasant afterlife.  Considering the possible threats that can come to a Dunmer's House and descendants are (at least in Morrowind) extensive, this is certainly something the soon-to-depart would be worried about.  And since life in general in Morrowind is so risky, the idea of a sheltered afterlife has an obvious appeal.</p> <p>And if you've read <a href="../essays/fireofvivec.php">that essay of mine</a>, entertain the idea that Vivec's Fire "consumes" the essence of the mortal in the same way that it "destroys" all desire.</p> <p>Also, yes, I've written a few unreasonable explanations of this prayer, but I won't waste your time with them.</p></div>
<div class="commenthidden" data-ident="03-015"><p>Dwemeri Atronachs might not sound familiar, but it's just another way to describe the Sphere, Spider, and Centurion constructs you fight in Skyrim.  Isn't it interesting, though?  Other races create "Frost Atronachs" and "Fire Atronachs" from pure magic, or daedric bargains, or such.  The Dwemer build their own out of brass and steam and SCIENCE!</p></div>
<div class="commenthidden" data-ident="03-016"><p>Cornered Spheres might not be intended to be a reference to anything particular.  But since when has that stopped me?</p> <p><a class="external" href="http://en.wikipedia.org/wiki/Squaring_the_circle" target="_blank">Squaring the Circle</a> is an old geometry problem that used to give mathematicians quite a lot of grief in ancient times.  Well, I suppose it still does, but now we know better than to try it.  In summary, the idea is to figure out a simple equation that will give you a square with the same area as a circle.  In the late 1800's this was proven to be impossible, but in the meantime "squaring the circle" had become a metaphor for the quest for perfection, combining two irreconcilable opposites, like uniting Yin and Yang into the Tao.</p> <p>So perhaps the Cornered Spheres of the Dwemeri can be thought of as useful mechanisms of paradox?  An interesting choice since, as we have observed, neither knives nor sounds nor fire could otherwise harm the Netchiman's Wife.  Under Vivec's protection, and the protection of the Daedra who visited her, the Netchiman's Wife could only be harmed by paradox.</p></div>
<div class="commenthidden" data-ident="03-017"><p>To properly talk about this, we're going to first consider what Vivec says and why.  Afterwards, I'll address whether or not the Dwemer can conceive of Love, and why or why not.</p></div>
<div class="commenthidden" data-ident="03-018"><p>A "constituent" is an ingredient.  So Love can be a founding element of moods and affairs, which is to say the emotions and actions of mortals.</p></div>
<div class="commenthidden" data-ident="03-019"><p>So you know how your significant other sometimes starts an argument with you about something that happened an hour ago?</p><p>Women.  Am I right, fellas?  Hah hah.  This guy knows what I'm talkin' about!</p></div>
<div class="commenthidden" data-ident="03-020"><p>We've all had these in our relationships.  Asking your girlfriend not to wear a Van Halen t-shirt because it reminds you that your last ex-girlfriend broke up with you while "Runnin' with the Devil" was playing on the radio.  Remember that time the guy you were dating asked you not to twirl your hair around your finger?  Ever wonder why he asked you to do that?  He didn't have a reason.</p><p>Men.  Am I right, ladies?  Hah hah.  This girl knows what I'm talkin' about!</p></div>
<div class="commenthidden" data-ident="03-021"><p>If you've been in anything like a lengthy relationship, you and your partner have had these sort of "riddles."  Phrases that say one thing but mean another.  Little hints dropped about a certain something that was going to happen later that night if you catch my meaning and I think that you do.</p></div>
<div class="commenthidden" data-ident="03-022"><p>I think this one is pretty obvious.  Sometimes you can tell there's something going on between two people just by the way they look at each other.</p></div>
<div class="commenthidden" data-ident="03-023"><p>This plays into the next note, but basically ze's talking about communication that happens without either person being aware of it.  You're just sitting on the couch, talking about how great Seinfeld was, or how much you miss Firefly.  And maybe without you even being aware of it, it's happening.</p> <p>There's a well-known story about a Buddhist monk who catches his students shouting at each other during an argument.  The monk asks them, "Why do people shout at each other?"</p> <p>His students confer on this and answer, "Because we have lost our focus, and so we are no longer calm."</p> <p>The monk says, "Why shout at the person sitting next to you?  You can easily communicate what you mean with a soft manner."</p> <p>When the students are stumped, the monk says, "When two people are angry at each other, their hearts grow distant from each other.  They must shout so that their hearts can hear from a distance."</p> <p>"When two people begin to fall in love," he continues, "their hearts grow closer.  They don't shout at each other, but talk clearly and softly.  The closer they become, the softer their speech, until they need only whisper.  Two people who are in love often no longer need speech.  They can communicate with only a look.  Their hearts are so close that they do not need to speak at all."</p> <p>When you think about ALMSIVI, and Love, think about that story.  When in Love, you do not need words.  <em>Your souls are united as one</em>.</p></div>
<div class="commenthidden" data-ident="03-024"><p>True devotions could be as simple as basic friendships of any kind.</p></div>
<div class="commenthidden" data-ident="03-025"><p>These "unions" could mean marriages, but they could also just mean very tough, durable friendships that last for years and years.  Little Vehk is correct in identifying Love as an element in <em>all</em> forms of relationships, not just romantic ones.  It's a wise and perceptive examination of the forces that harmoniously bind our minds and souls together.</p></div>
<div class="commenthidden" data-ident="03-026"><p>If this meditation can be considered to be humorous, then I think this is the punchline.  After all those wonderful observations of the nature of affection and adoration, we have some scientific measurements of the "energy" derived from relationships, and of course the last sentence reads like something from a 9th grader's essay that he started on the night before it was due.</p></div>
<div class="commenthidden" data-ident="03-027"><p>I don't claim to be an expert on the Dwemer.  In fact, I think the notion of being an "expert" on a race that is designed to be unintelligible to be a strange idea.  In my <em>opinion</em>, you sort of just have to get used to working in a constant cloud of speculation and ignorance.  So with that in mind, I'm still going to try to give this my best shot.</p> <p>It's common knowledge that the Dwemer do not "worship" the Aedra or Daedra the same way as other races in Tamriel.  The Dwemer feel that these "Gods" are not infallible.  Instead, they feel the Aedra and Daedra simply posses a power greater than the Dwemer, and the Dwemer are confident that they can figure out how to obtain that power for themselves.</p> <p>I suspect this TES equivalent of atheism is the reason why the Dwemer cannot comprehend Love, simply because they cannot comprehend a higher power in the traditionally religious sense.</p> <p>It could also be that the 36 Lessons are giving us a cryptic glance into the every day life of the Dwemer.  Perhaps they do not feel an emotion like affection, as though they were some kind of Vulcan logic-driven society.</p> <p>Let's be honest, I'm really guessing here.  But maybe it's not supposed to make sense?  Maybe guessing is what we're supposed to do.  There are many ways to encourage subjective interpretation.</p></div>
<div class="commenthidden" data-ident="03-028"><p>I suspect the "doom" the Dwemer are referring to are their defeat at the hands of ALMSIVI in Sermon 36.  Now, from what we know about the Dwemer (or perhaps what we <em>think</em> we know about the Dwemer), their disappearance was actually the result of Kagrenac's activation of the Numidium.  But the 36 Lessons of Vivec take a very pro-Dunmer interpretation of the events, and even go so far as to say that Numidium is an "image" of Vivec, as though Kagrenac copied Vivec's Godhood.</p> <p>Since ALMSIVI defeats Kagrenac's giant stompy robot by combining together via the Sixth Walking Way, which is one example of Love in the metaphysical sense, Love is absolutely the "doom" of the Dwemer.  In this version of the tale, anyway.  They do not understand this powerful and primal force, so they know it will be their doom.</p></div>
<div class="commenthidden" data-ident="03-029"><p>So here's a puzzle for you.  You would expect the "Eight Known Worlds" to be a clear reference to the eight Aedra that formed the Planets in the sky over Nirn after the creation of Mundus.  Which Gods comprise the eight "Gift Limbs" changes depending on which culture you ask, but the fans generally consider the Alessian Empire's "Eight Divines" to be the most accurate list.  These would be Akatosh, Arkay, Dibella, Julianos, Kynareth, Mara, Stendarr, and Zenithar.</p> <p>And yet, the Dwemer list a different set: Akatosh, Arkay, Julianos, Kynareth, Lorkhan, Mara, Nirn, Stendarr.  What happened to Dibella and Zenithar?  Where'd Nirn and Lorkhan come from?</p> <p>Even more puzzling is that the Dwemer seem perfectly aware of the physical construction of the Mundian solar system as represented by their Orrery in the Imperial City, which not only utilizes the Alessian model but also identifies Secunda and Masser as the two halves of Lorkhan.  So clearly this is not a simple variance in cultural interpretations.</p> <p>Perhaps we can consider the Dwemer's specific word use.  "Eight known worlds" could imply that these eight entities are what the Dwemer consider to be "worlds," and all other celestial bodies are, well, something else.  I suppose.  Nirn clearly qualifies.  They're standing on it.  Perhaps they've used Lorkhan to describe Masser and Secunda, two heavenly bodies that have seen their fair share of exploration over the centuries.  This leaves Dibella and Zenithar.  Perhaps Dibella and Zenithar are simply not habitable?</p> <p>Dibella is a Goddess described as "hot-blooded."  Maybe her Planet is entirely too hot to be occupied.  That seems a bit too easy, though, and frankly not very interesting.</p> <p>Zenithar is, in some cultures, the God of wealth and commerce.  The Khajiit consider their version, Z'en, to be the God of justice, or "payment in kind," and it's easy to see the common theme between the two concepts.  How that might contribute to an uninhabitable Planet is frankly beyond my imagination at this time.</p> <p>I know these aren't very satisfactory answers.  But given enough time the community will develop something interesting.  And I'll update when we do.</p></div>
<div class="commenthidden" data-ident="03-030"><p>The Secret to Doom, as discussed earlier, is Love, that which creates the destruction of the Dwemer in Sermon 36.</p></div>
<div class="commenthidden" data-ident="03-031"><p>This was a good Sermon for fans of Dwemeris.  Their reluctance to openly discuss ideas with Vivec's Egg echoes the theme of warring concepts, of metaphors made real, which we'll see plenty of in later Sermons.  Because the Dwemer are so dependent on science and technology, and indeed because they seem to avoid magic and faith, reveals a vulnerability that Vivec and ALMSIVI will later exploit.</p> <p>We also read Vivec's prayer for the first time, and see how efficacious it is.  It will come into play again, at a key point, towards the very end of the Sermons.</p> <p>Perhaps in this Sermon we read a little about the way Dwemer and Chimer relations were stressed.  The Dwemer are puzzled by Vivec's description of Love, and no doubt the Chimer are equally puzzled by these enigmatic Mer.  Maybe the Dwemer were never capable of existing long in Tamriel, surrounded by species they couldn't understand and who, in turn, could not understand them.  Incomprehension frequently brings fear to the naturally fearful, and fear leads inevitably to hatred, which causes war.  If the Dwemer had been more willing to allow other races to understand them, their deaths may have been avoidable, but that would have been against their nature.</p> <p>So once again we reach a common philosophical theme in the 36 Lessons.  Separation is both the augend and the sum of fear, which creates hate and suffering.  Only Love, which brings closer all things, can put an end to Fear.</p></div>
<?php include 'middle.php' ?>
<p>Being blind the netchiman's wife wandered into a cave on her way to the domains of House Indoril. It so happened that this cave was a <span class="lessonlink" data-call="03-001">Dwemeri stronghold</span>. The Dwemer <span class="lessonlink" data-call="03-002">spied the egg</span> and captured the netchiman's wife. They bound her head to foot and brought her deep within the earth.</p>
<p>She heard one say:</p>
<p>'Go and <span class="lessonlink" data-call="03-003">make a simulacrum of her</span> and place it back on the surface, for she has <span class="lessonlink" data-call="03-004">something akin to what we have</span> and so the Velothi will covet it and notice if she is too long away.'</p>
<p>In the darkness, the netchiman's wife felt <span class="lessonlink" data-call="03-005">great knives</span> try to cut her open. When the knives did not work, the Dwemer used <span class="lessonlink" data-call="03-006">solid sounds</span>. When those did not work, <span class="lessonlink" data-call="03-007">great heat</span> was brought to bear. Nothing was of any use and egg of Vivec remained safe within her.</p>
<p>A Dwemer said:</p>
<p>'Nothing is of any use. <span class="lessonlink" data-call="03-008">We must go and misinterpret this</span>.'</p>
<p>Vivec felt that his mother was afraid, <span class="lessonlink" data-call="03-009">and so consoled her</span>.</p>
<p>'<span class="lessonlink" data-call="03-010">The fire is mine</span>: let it consume thee,</p>
<p>And make a <span class="lessonlink" data-call="03-011">secret door</span></p>
<p>At the <span class="lessonlink" data-call="03-012">altar of Padhome</span></p>
<p>In the <span class="lessonlink" data-call="03-013">House of Boet-hi-Ah</span></p>
<p>Where we become safe</p>
<p>And <span class="lessonlink" data-call="03-014">looked after</span>.'</p>
<p>This old prayer made the netchiman's wife smile and begin such a deep sleep that when <span class="lessonlink" data-call="03-015">Dwemeri atronachs</span> returned with <span class="lessonlink" data-call="03-016">cornered spheres</span> and cut her apart she did not awake and died peacefully. Vivec was removed from her womb and placed within a magical glass for further study. To confound his captors, he channeled his essence into love, <span class="lessonlink" data-call="03-017">an emotion the Dwemer knew nothing about</span>.</p>
<p>The egg said:</p>
<p>'Love is used not only as a <span class="lessonlink" data-call="03-018">constituent in moods and affairs</span>, but also as the raw material from which relationships produce <span class="lessonlink" data-call="03-019">hour-later exasperations</span>, <span class="lessonlink" data-call="03-020">regrettably fashioned restrictions</span>, <span class="lessonlink" data-call="03-021">riddles laced with affections</span> known only to the loving couple, and <span class="lessonlink" data-call="03-022">looks that linger too long</span>.</p>
<p>Love is also an often-used ingredient in some <span class="lessonlink" data-call="03-023">transparent verbal and nonverbal transactions</span> where, eventually, it can sometimes be converted to a <span class="lessonlink" data-call="03-024">variety of true devotions</span>, some of which yield tough, insoluble and infusible <span class="lessonlink" data-call="03-025">unions</span>. In its basic form, love supplies approximately <span class="lessonlink" data-call="03-026">thirteen draughts of all energy that is derived from relationships</span>. Its role and value in society at large are controversial.'</p>
<p>The Dwemer were <span class="lessonlink" data-call="03-027">vexed at these words</span> and tried to hide behind their power symbols. They sent their atronachs to remove the egg-image from their cave and place it within the simulacrum they had made of Vivec's mother.</p>
<p>A Dwemer said:</p>
<p>'We Dwemer are only aspirants to this that the Velothi have.</p>
<p><span class="lessonlink" data-call="03-028">They shall be our doom</span> in this and the <span class="lessonlink" data-call="03-029">eight known worlds</span>, NIRN, LHKAN, RKHET, THENDR, KYNRT, AKHAT, MHARA and JHUNAL.'</p>
<p>The <span class="lessonlink" data-call="03-030">secret to doom</span> is within this Sermon.</p>
<p><span class="lessonlink" data-call="03-031">The ending of the words is ALMSIVI</span><a href="../css/images/36rages/<?php echo pad($sermon); ?>.png">.</a></p>
<?php include 'footer.php' ?>