<?php
$sermon = '4';
include 'header.php';
?>
<div data-ident="04-000" class="commenthidden" ><p>This Sermon is noteworthy because it suggests the idea that everything in the Elder Scrolls universe (at least in the context of the 36 Lessons) is planned, somehow part of a greater model.  That there are no coincidences in the Elder Scrolls universe means that all events are connected to one another, that nothing is meaningless, and that information can be found in absolutely every word, every object, every action.</p><p class="horizline"></p><p>In Morrowind, reading Sermon Four grants a bonus to Mysticism, is worth 200 septims and weighs 3.0 units.  A copy of Sermon Four can be found in a tower at <a class="external" href="http://www.uesp.net/wiki/Morrowind:Hanud" target="_blank">Hanud</a>, in the shrine at <a class="external" href="http://www.uesp.net/wiki/Morrowind:Ramimilk" target="_blank">Ramimilk</a>, and in the Secret Library at the <a class="external" href="http://www.uesp.net/wiki/Morrowind:Hall_of_Justice" target="_blank">Hall of Justice</a> in Vivec.</p><p>Sermon 29 names this Sermon "The Corners of the House of Troubles."  Its number is 242, which corresponds to the word "born."</p></div>
<div data-ident="04-001" class="commenthidden" ><p>These "spirits" could be Daedra, but they don't have to be.  It's possible these could also be Ancestor Spirits, the souls of powerful dead Dunmer who linger in Tamriel in service to their progeny.</p><p>Uh, but anyway, my gut says they're Daedra of some kind.  Possibly (probably) not Princes, but Daedra none the less.</p></div>
<div data-ident="04-002" class="commenthidden" ><p>These are apparently Daedra who insist that random events can happen in Mundus.  This seems like a safe bet, considering the influence Padomaic entities (Lorkhan, SITHIS, Daedra) have on the events on all levels of the Aurbis.  But as Vivec will prove, nothing in the Godhead's dream happens by accident.</p><p>Interestingly, this also reveals something of Kirkbride's vision of the Daedra, that they have their own internal politics and philosophy, similar to the myriad of demons in Hindu mythology.</p></div>
<div data-ident="04-003" class="commenthidden" ><p>The "popular notion" is the commonly-held concept of a (or <em>the</em>) God and their capacities, which in this case is that God's will is ineffable and flawless, and that all events play out according to God's will.  Vivec argues here that, if the general consensus of what God is and what God can do is true, there can be no accidents or coincidences.</p><p>Vivec makes the "popular notion" distinction.  Is ze suggesting that God can work by means other than the ones held in popular opinion?</p></div>
<div data-ident="04-004" class="commenthidden" ><p>So complete is Vivec's victory over this Guild that history can not be bothered to record their names.</p></div>
<div data-ident="04-005" class="commenthidden" ><p>So now we see that Vivec's divinity is not a natural state, an inevitable ascension, but rather something at risk.  Here, ze sees a challenge, an argument, which Vivec must win in order to maintain hir status as a God.  But why?</p><p>Clearly the only thing standing between Vivec and Godhood at this point is a strong argument.  This likely plays to Vivec's status at this point as an egg, a pure concept, no more than a possible God.  This concept can be shattered at any point by a well-supported suggestion that it is not what it intends to be.</p><p>This doesn't seem so strange, upon examination.  Consider the creation of Mundus: Lorkhan made a suggestion, an argument, and the eight Aedra came together to reinforce this suggestion, still in its form as a void of possibility.  The Aedra were the lines put on paper that draw a form.  The words spoken to form a sentence.  The symbols etched to create a spell.</p><p>But a more pressing question might be: why does Vivec have to argue for hir divinity if there is no such thing as coincidence?  If all events unfold as they are intended, does ze have any influence over hir own fate?  Does hir own attempt to argue the point nullify hir argument?</p></div>
<div data-ident="04-006" class="commenthidden" ><p> Basically the argument here is that "coincidence" is an illusion of perception.  Ze argues that events that appear to correlate are just selected by the viewer from a bottomless sea of events, and any pattern that is assigned to them is assigned from our perception, which by definition is the exact opposite of coincidence.  Therefore, as ze puts it, "synchronicity ends up invalidating the concept of the coincidental."</p><p>The very act of perceiving a supposedly synchronous event is itself the act of observing the will of God.</p></div>
<div data-ident="04-007" class="commenthidden" ><p>This may well be an Earthbone, an Old Ehlnofey: one of the Aedric remnants.  Certainly, considering Vivec's aspirations of Godhood, the Old Gods would be quite concerned with hir qualifications.</p></div>
<div data-ident="04-008" class="commenthidden" ><p>Consider the previous comment about the nature of Mundus as an "argument."  Perhaps the Old Bone is suggesting that Vivec must create a new argument, a new "thought," and in so doing can demonstrate hir ability to harness the creative impulse necessary for the creation of divinity.</p><p>That last part may have seemed a little confusing.  I'll discuss it at length in later sermons, but for now, consider the Aurbis as a "story," and a God is no longer just a character but a co-author of that story.  Therefore some creativity is required of that God, and that requires new, original ideas.  This is what the Old Bone is asking for.</p></div>
<div data-ident="04-009" class="commenthidden" ><p>Interestingly, Almalexia is referred to here as "Love" and not "Mother," or one of her other titles.  Very interesting.</p></div>
<div data-ident="04-010" class="commenthidden" ><p>More or less, the thrust of Vivec's statement here is that ze's seen the sum total of Nirn's "face," ze's explored it entirely, secretly and in darkness (missing candles).  Perhaps this is a reference to Vivec's achievement of CHIM, but I don't think so, since ze only mentions the viewing world, not the Wheel.</p></div>
<div data-ident="04-011" class="commenthidden" ><p>In other words, by condensing itself 20 times, the Old Bone reduces itself to its fundamental essence: its purest, most simple form.</p></div>
<div data-ident="04-012" class="commenthidden" ><p>Most probably this is a reference to semen, and by extension, biological inheritance via (for example) DNA.  Vivec drinks it, and this is how ze "absorbs" the essence of the Old Bone.</p></div>
<div data-ident="04-013" class="commenthidden" ><p>By absorbing the essence of an Old Bone, Vivec becomes something called a "Ruling King."  The exact definition of what a Ruling King is, or what one can do, is not provided.  But we can assume that at the very least, a Ruling King is a being of immense power and responsibility.</p><p>Considering the influences of other fictional and religious sources on the 36 Lessons, I suspect it's likely that a Ruling King is in some way related to an enlightened scholar of Eastern cultures.  Depending on the specific source, this could mean a person of incredible wisdom and knowledge, or a magnificent Demi-God of unfathomable power.</p></div>
<div data-ident="04-014" class="commenthidden" ><p>This is a spirit that deals in specifics, a common theme in this Sermon.  Like the Coincidence Guild, this is another embodiment of a philosophy.  The Coincidence Guild suggest: "Hey, stuff happens.  Sometimes for no reason."  The Chancellor suggests: "Everything can be measured.  Nothing is unknowable."</p><p>Are you sensing the theme here, by the way?  Vivec is being confronted by concepts.  First, ze must prove that there are no coincidences and that the Will of God exists.  Then ze must confuse the entire world, introducing something New to an entity that should not be able to be surprised.  When confronted by a representative of certainty, of precision, Vivec asserts that ze is a "letter written in uncertainty."  Ze is a random element, something new, destined to arrive by the will of God.</p></div>
<div data-ident="04-015" class="commenthidden" ><p>It should be unsurprising to you that certainty looks perfect.  Whether or not that also means "beautiful" is a matter of personal interpretation.  The Altmer, I suspect, would find perfection as beautiful because of their strong Anuic tendencies and the marvelous comfort they might find in the uniform and infinite complexity of Aetherius.  Or perhaps they maintain a concept of "true" beauty similar to Plato's "<a class="external" href="http://en.wikipedia.org/wiki/Theory_of_Forms" target="_blank">Theory of Forms</a>."</p><p>The Dunmer, on the other hand, have a very different opinion of beauty, in that they appreciate the flaws, the "ugliness."</p><p>Which one do you prefer?  Or rather: how much of one or the other?</p></div>
<div data-ident="04-016" class="commenthidden" ><p>I'm wondering if this has anything to do with Mirror Logicians, Altmer who fight the Numidium in all its various dimensional forms, forwards and backwards across history.  Perhaps, given the existence of the <a class="external" href="http://uesp.net/wiki/Morrowind:Antabolis_Informant" target="_blank">Dwemer Puzzle Box</a>, this is a reference to the Deep Elves?</p></div>
<div data-ident="04-017" class="commenthidden" ><p> "White glamour" is a reference to powder makeup for the face.  Within the context of Veloth, this is probably a jab at foolish and vain young women (hence: "girls").  In my head, I like to think Vivec's making fun of romance literature.  "This ain't <em>Little Women</em>.  Gods are being born, here."</p></div>
<div data-ident="04-018" class="commenthidden" ><p>This can be a way of expressing Vivec's Padomaic nature as an element of chaotic change, as above.  Otherwise, like a story, a letter is written with intent, and sent to a specific destination.  Is this "letter" uncertain because its message is not definite?  Or because it has been sent to an uncertain place?  Or both?</p><p>But it could also be a nod towards a literal "letter," that of the symbol of CHIM.  CHIM's sigil is, when written, constantly shifting and flickering, as though it threatens to blink out of existence at any moment.  So perhaps Vivec's recommendation, later, to become a letter written in uncertainty is a plea for attaining CHIM?</p></div>
<div data-ident="04-019" class="commenthidden" ><p>The symbolism of this is not lost on Vivec.  The Chancellor is showing Vivec an astrolabe, a device used to measure and predict the movements of celestial bodies.  A "map," effectively, of the observable universe.  In the 36 Lessons, it effectively represents the ability to understand the Aurbis, and reality itself.  By breaking it in half, he communicates that Vivec's journey will be un-mappable.  None have done it before, and none but Vivec can withstand it.</p></div>
<div data-ident="04-020" class="commenthidden" ><p>To labor under the demands of one's senses is slavery.  The senses are either liars, or are lied to.  The Aurbis is nothing but a dream, yet the senses tell us it is real.  Therefore, to believe the lie, that the Aurbis is something of substance, is to labor under the lies told by the senses.</p><p>If you'd like to learn more about laboring under the slavery of the senses, I'd recommend reading more about the Buddhist concept of <a class="external" href="http://en.wikipedia.org/wiki/Ayatana" target="_blank">Ayatana</a>, the "sense sphere" of the human body.</p></div>
<div data-ident="04-021" class="commenthidden" ><p>If you have been born a life of luxury, ignore it.  Like Siddhartha leaving the palace of his father, if you will.</p></div>
<div data-ident="04-022" class="commenthidden" ><p>Here Vivec states hir understanding that a Ruling King is not a place of privilege or luxury.  This is the truest form of leadership: to labor under the demands of the people you serve.</p></div>
<div data-ident="04-023" class="commenthidden" ><p>So Vivec faces various spirits, many of whom seem to follow a theme set by the spirit itself.  The Coincidence guild shows up and Vivec denies the existence of coincidences.  From this assertion of logical structure, ze is visited by spirits that represent specifics, measurements, logic, and frameworks.</p><p>The Old Bone of the Earth represents one of the myriad of supporting "laws of nature" that hold Nirn together.  The Chancellor of Exactitude represents the measurements and models that present the universe as a finite, understandable object.</p><p>If Vivec had agreed with the Coincidence Guild, would ze have then faced Spirits representing elements of white noise?  Of random potential?  Of unpredictable chaos?</p><p>Either way, it doesn't matter.  Coincidence was destroyed in the land of the Velothi, so from now on everything in the 36 Lessons happens because of God's will.</p><p>But which God?</p></div>
<?php include 'middle.php' ?>
<p>The simulacrum of the netchiman's wife who carried the egg of Vivec within it went back to looking for the lands of the Indoril. Along the journey <span class="lessonlink" data-call="04-001">many more spirits</span> came to see it and offer instructions to its son-daughter, the future glorious invisible warrior-poet of Vvardenfell, Vivec. A troupe of spirits called the <span class="lessonlink" data-call="04-002">Lobbyists for the Coincidence Guild</span> appeared. Vivec understood the challenge immediately and said:</p>
<p>'<span class="lessonlink" data-call="04-003">The popular notion of God kills happenstance</span>.'</p>
<p>The head of the Lobbyists, <span class="lessonlink" data-call="04-004">whose name is forgotten</span>, tried to defend the concept's existence. He said, 'Saying something at the same time can be magical.'</p>
<p><span class="lessonlink" data-call="04-005">Vivec knew that to retain his divinity that he must make a strong argument against luck</span>. He said:</p>
<p>'Is not the <span class="lessonlink" data-call="04-006">sudden revelation of corresponding conditions</span> and disparate elements that gel at the moment of the coincidence one of the prerequisites to being, in fact, coincidental? Synchronicity comes out of repeated coincidences at the lowest level. Further examination shows it is the utter power of the sheer number of coincidences that leads one to the idea that synchronicity is guided by something more than chance. Therefore, synchronicity ends up invalidating the concept of the coincidental, even though they are the symptomatic signs that bring it to the surface.'</p>
<p>Thus was coincidence destroyed in the land of the Velothi.</p>
<p>Then an <span class="lessonlink" data-call="04-007">Old Bone of the earth</span> rose up before the simulacrum of the netchiman's wife and said, 'If you are to be born a ruling king of the world you must confuse it with new words. <span class="lessonlink" data-call="04-008">Set me into pondering</span>.'</p>
<p>'Very well,' Vivec said, 'Let me talk to you of the world, which I share with <span class="lessonlink" data-call="04-009">mystery and love</span>. <span class="lessonlink" data-call="04-010">Who is her capital</span>? Have you taken the scenic route of her cameo? I have-- lightly, in secret, missing candles because they're on the untrue side, and run my hand along the edge of a shadow made from one hundred and three divisions of warmth, and left no proof.'</p>
<p>At this the Old Bone <span class="lessonlink" data-call="04-011">folded unto itself twenty times</span> until it became <span class="lessonlink" data-call="04-012">akin to milk</span>, which Vivec drank, becoming a <span class="lessonlink" data-call="04-013">ruling king</span> of the world.</p>
<p>Finally the <span class="lessonlink" data-call="04-014">Chancellor of Exactitude</span> appeared, and he was <span class="lessonlink" data-call="04-015">perfect to look upon from every angle</span>. Vivec understood the challenge immediately and said:</p>
<p>'Certitude is for the <span class="lessonlink" data-call="04-016">puzzle-box logicians</span> and <span class="lessonlink" data-call="04-017">girls of white glamour</span> who harbor it on their own time. I am a <span class="lessonlink" data-call="04-018">letter written in uncertainty</span>.'</p>
<p>The Chancellor bowed his head and smiled fifty different and perfect ways all at once. <span class="lessonlink" data-call="04-019">He pulled the astrolabe of the universe</span> from his robe and broke it in half, handing both halves to the egg-image of Vivec.</p>
<p>Vivec laughed and said, 'Yes, I know. The <span class="lessonlink" data-call="04-020">slave labor of the senses</span> is as selfish as polar ice, and worsens when energies are spent on a life <span class="lessonlink" data-call="04-021">others regard as fortunate</span>. <span class="lessonlink" data-call="04-022">To be a ruling king</span> I will have to suffer much that cannot be suffered, and to weigh matters that no astrolabe or compass can measure.'</p>
<p><span class="lessonlink" data-call="04-023">The ending of the words is ALMSIVI</span><a href="../css/images/36rages/<?php echo pad($sermon); ?>.png">.</a></p>
<?php include 'footer.php' ?>