<?php
$sermon = '5';
include 'header.php';
?>
<div data-ident="05-000" class="commenthidden" ><p>Sermon Five introduces, at last, the Dunmer hero Nerevar.  It is the narrative of the final event before Vivec is introduced to hir brother and sister in the city of Almalexia.</p><p class="horizline"></p><p>In Morrowind, reading Sermon Five grants a bonus to the Axe skill, is worth 200 septims and weighs 3.0 units.  A copy of Sermon Five can be found in the <a class="external" href="http://www.uesp.net/wiki/Morrowind:Lleran_Ancestral_Tomb" target="_blank">Lleran Ancestral Tomb</a>, and in the Secret Library at the <a class="external" href="http://www.uesp.net/wiki/Morrowind:Hall_of_Justice" target="_blank">Hall of Justice</a> in Vivec.</p><p>Sermon 29 names this Sermon "The Corners of the World."  Its number is 100, which corresponds to the word "a."</p></div>
<div data-ident="05-001" class="commenthidden" ><p>Sure, the Dwemer built it "in haste," when they realized Almalexia and Sotha Sil would notice the Netchiman's Wife was missing, but perhaps this also demonstrates an innate lack of knowledge in the Dwemer's ability to replicate a Dunmer mother.  Besides, it's also likely that Dwemer automatons are never intended to stray from the underground tunnels of the Deep Elves, and so they are particularly susceptible to the harsh climate of Vvardenfell.</p></div>
<div data-ident="05-002" class="commenthidden" ><p>Traditionally Dwemer automata are thought to be made of the rather under-defined "Dwemer Metal," but that metal is often depicted as brass or gold.  Certainly Dwemer Metal is more robust than gold.  But it is interesting that the Dwemer constructed the simulacrum out of a golden material, since the Chimer are often depicted as having golden skin.</p><p>Later, when Vivec "absorbs" the simulacrum at the moment of hir mystical birth, it's helpful to consider that ze has absorbed a Dwemer creation, one of golden skin.  That very golden skin image will become quite relevant later, when the fate of the Dwemer is revealed.</p></div>
<div data-ident="05-003" class="commenthidden" ><p>So this wreck of a machine laid in the dust for nearly three months before someone finally noticed it.  I suspect it's rather hard to miss a golden mechanical woman lying beside a road.  Can we therefore suppose that not too many people travel this particular path?  I wonder why?</p><p>Maybe this is due to the presence of one or more Dwemer caves, like the one in Sermon Three.  These might make it dangerous for Chimer travelers.  These were the days before Resdaynia, which means the Chimer and Dwemer were often in conflict.</p></div>
<div data-ident="05-004" class="commenthidden" ><p> Finally the 36 Lessons gives us a modicrum of the background of the great Dunmer hero, Nerevar.  Such is the danger of those roads that pass Dwemer strongholds that merchant caravans must hire warriors for protection, from the Dwemer, or bandits, or from both.</p><p>In this Lesson, Indoril Nerevar is presented as a common warrior, a guard on this otherwise featureless caravan.  Most other in-game sources tell us that Nerevar was a great warrior of tremendous reputation, possibly a high ranking member of a House of Dunmer named House Mora, who married Almalexia and became the head of House Indoril.  He was considered the greatest general of his time, and yet the Lessons depict him as a bit of an idiot, useless without the great wisdom of his closest friend and mentor, Vivec.</p><p>As you read through the 36 Lessons, and learn of the great friendship between Vivec and Nerevar, consider why the Lessons and other historical documents depict Nerevar with such great disparity.</p></div>
<div data-ident="05-005" class="commenthidden" ><p>The sentence "anon Almalexia" leads us to believe that the city was, at this point, not yet called Almalexia.  What it was called before is not entirely clear to me, although comments in the Tribunal expansion suggest that it used to be, or was built on top of, a Dwemer city of some considerable size.</p><p>Interestingly, after becoming occupied by the Dunmer and Almalexia, the city was later attacked by Mehrunes Dagon in 1E 2920, after the events depicted in the 36 Lessons.  Though Sotha Sil and AYEM were able to drive Dagon back to Oblivion, they were not quick enough to prevent the city's destruction.</p><p>That Almalexia the city is considered the "capital" of Veloth, the kingdom of the Chimer, speaks to AYEM's status as the "leader" or "queen" of the Velothi, even though Vivec is considered to be the most publicly visible of the Tribunal.</p></div>
<div data-ident="05-006" class="commenthidden" ><p>Again: Vivec is in the process of being born.  ALMSIVI is birthing itself.  There is a connection to be made here, between Vivec's Dwemeri-created womb and the use of the Heart of Lorkhan and Kagrenac's Tools.  ALMSIVI is born of the creations of Dwemeris.</p><p>Also: Awwww... socially-awkward Vivec.</p></div>
<div data-ident="05-007" class="commenthidden" ><p>There's an interesting theory going around in the fan community that Dwemer Metal is actually made of (or derived from) souls of the Dwemer themselves.  But I think in this case the Chimer warrior (who is actually Nerevar himself) is referencing the tendency of the Dwemer to create the skin and bone of their creations out of the metal particular to their crafts.</p></div>
<div data-ident="05-008" class="commenthidden" ><p>So now we see that the Chimer consider Almalexia to be their mother, or at least a mother-figure.  Alternatively this could be nothing more than a formal title assigned to Almalexia, like Queen or Pharaoh in any other culture, though I suspect the word "mother" would be capitalized, were that the case.</p></div>
<div data-ident="05-009" class="commenthidden" ><p> I'm not real sure where Noormoc is.  I'd assume it's a Dunmer settlement, but it doesn't appear on any maps I can find, even concept maps.</p><p>It's probably safe to speculate that Noormoc has or possibly features a shrine to Mehrunes Dagon.</p></div>
<div data-ident="05-010" class="commenthidden" ><p>The color red is interesting.  Dagon is often associated with red, mostly because of his destructive rage.  But we know from the <a class="external" href="http://www.uesp.net/wiki/Lore:The_Arcturian_Heresy" target="_blank">Arcturian Heresy</a> that red is also the color of betrayal.  Cross-reference that with the first story from the <a class="external" href="http://www.imperial-library.info/content/seven-fights-aldudagga" target="_blank">Seven Fights of the Aldudagga</a> and Dagon's association with the color becomes far more intimate.</p><p>Also consider the possibility that Dagon's wives are red because of a blood oath of some kind.  Consider again that this could be a reference to menstrual blood, or the virgin's "proof of blood."</p></div>
<div data-ident="05-011" class="commenthidden" ><p>So this merchant captain has hired a wise man to help advise him when prophecy can aid in his profits.  This could well be a wise and common practice in Velothi society, considering how much weight they put in prophecy, and the magical nature of the Elder Scrolls universe in general.</p><p>I often wonder about what specific role these shamans might perform.  Some kind of divination, certainly, but how?  The reading of cast bones?  Kau Cim sticks?  Certainly the practice could be requested before any choice the merchant captain might make.</p><p>But when you consider how rare fortune tellers are in other cultures, it suggests that this merchant captain is of some considerable renown or success.  This is not someone who is scraping for every coin.  This merchant is likely someone important and, if that is the case, I would suggest that it's likely this merchant is heavily associated with the merchant House in Morrowind, Hlaalu.</p></div>
<div data-ident="05-012" class="commenthidden" ><p>Does the wise counsellor have a kind of intuitive sense of Vivec's presence in the simulacrum?  Or has a Velothi prophecy predicted Vivec's coming?  Perhaps the very presence of the Egg-Image has aligned certain signs in such a way to communicate a message to those who have the wisdom to read it: the movement of the winds, the position of the sun, the date and time, the posture of the simulacrum.  Anything could be interpreted as significant.</p></div>
<div data-ident="05-013" class="commenthidden" ><p>This is almost certainly a reference to the Four Corners of the House of Troubles, the four "evil" Daedra Molag Bal, Mehrunes Dagon, Malacath, and Sheogorath.  "Good wounded" could be a vaginal metaphor, or possibly a concept of wounds meant to cause pleasure instead of suffering.  Collectively these all lead me to believe that the Red Wives of Dagon are in to some seriously kinky sex.</p></div>
<div data-ident="05-014" class="commenthidden" ><p>Sexual techniques.  Possibly these could be literal magical techniques, which seems likely considering the thorough integration of magic into every day Tamrielic existence.</p><p>Vivec knows a few of these.  We'll see them later.</p></div>
<div data-ident="05-015" class="commenthidden" ><p> It might be noteworthy that the usual phrase "under the sun" is transformed to "under the moons" in Velothi culture.  The reasoning is obvious: Altmer may worship Magnus, the sun, but Velothi are far more concerned with the comings and goings of Lorkhan, and his lunar corpse.</p><p>This is something of a reference to what comparative religion researchers sometimes call Lunar or Solar religions; systems of faith or culture that appear to configure themselves around Gods based on the Sun or the Moon.</p><p>How these two cultures differentiate between the Solar and Lunar "characteristics" is so diverse that I simply refuse to write about it here.  But Wikipedia's got a lot of links for you to read, so have at it.</p></div>
<div data-ident="05-016" class="commenthidden" ><p>This is the Nords of Skyrim, again.  The Chimer were probably quite aware that Skyrim was preparing to go to war with all of Morrowind's people.  During this time in history, Skyrim was led by Ysmir, although who exactly Ysmir was is still a matter of some debate.</p><p>Undoubtedly, small skirmishes between Skyrim and Resdayn broke out here and there before the full force of Skyrim's invasion happened between 1E 222 and 1E 272.  Even after they were thrown out of Morrowind in 1E 416, the Nords will continue to challenge the Chimer in smaller numbers. We'll hear of those short battles later, in Sermon Nine.</p></div>
<div data-ident="05-017" class="commenthidden" ><p>When ze hears the merchant captain speak Nerevar's name, Vivec is spurned into action.  This is the mortal hero ze has been waiting for, the Hortator.</p></div>
<div data-ident="05-018" class="commenthidden" ><p>Vivec speaks directly into Nerevar's mind.  Ze knows Nerevar can hear hir.</p><p>Sometimes I wonder about Nerevar.  In this situation, a strange voice sounds out in his head and speaks in riddles, so his first inclination is to kill his employer.  Interesting choice, dude.</p></div>
<div data-ident="05-019" class="commenthidden" ><p>Just as the Chancellor of Exactitude folded into himself until nothing was left but his purest essence, Vivec asks Nerevar to "unfold," evolve in complexity, into a clear unknown, a force (like Vivec) of unpredictability and change.</p></div>
<div data-ident="05-020" class="commenthidden" ><p>This line seems somewhat meditative to me.  I think Vivec is advising silence until Nerevar reunites spiritually with his past.  Or maybe it's just a poetic way of advising a receptive, patient, student-like attitude.</p> <p>A more metaphysical explanation comes from the concept that the 36 Lessons of Vivec are actually written by Vivec for the Nerevarine, the person playing Morrowind, to read.  If this was the case, this line could be encouraging the Nerevarine to "sleep in the yesterday," or to contemplate and immerse one's self in past lives and events.  "Learn about the past," it seems to suggest.</p> <p>Another alternative is that this line is a recommendation to remain "cloaked in our former enemies," as suggested by Nerevar in the next lesson.  Vivec is possibly suggesting that the Chimer should "stay quiet" and peaceful with the Dwemer in order to maintain the union necessary to repel the menace of Skyrim's invasion</p></div>
<div data-ident="05-021" class="commenthidden" ><p>I can't read the words "melting stone" without thinking about Molag Bal, whose name translates to "Fire Stone."  Perhaps this is a recommendation that Nerevar should feel no sympathies towards the Daedra.  Or maybe Vivec is alluding to events involving Molag Bal that have yet to happen.</p> <p>Does that seem a little weak to you?  It should.  Probably a better interpretation lies within the deeper symbolism of a melting stone, and this comes to you via TES lore fan Umpteen:</p> <p>A stone that melts is a solid transforming into a liquid.  A transition from static to mutable.  In the stone's case, it does this by application of heat, and Fire is a metaphor in the Lessons for divine knowledge and ability.  In this case, Vivec is saying that one should not feel sorry for a melting stone.  Because even though it is in pain, it is transforming into a better shape.</p> <p>We'll see more of this philosophy when discussing the concept of the Sword and being "cut into better shapes."</p></div>
<div data-ident="05-022" class="commenthidden" ><p>Theoretically this might sound like a promotion for Nerevar, but there have historically been bodyguard services in many Eastern cultures that utilized a combination of physical force and personal reputation to protect merchant caravans.  Michelle Yeoh's character, Yu Shu Lien, in Crouching Tiger, Hidden Dragon (2000) is the head of one such service.  In these cultures, such bodyguard services enjoy an incredibly high level of public respect and reputation.</p><p>And sure, how much could it serve a guard's reputation if he kills his own employer, but this is the 36 Lessons.  Death and destruction are serious concepts, but killing in the service of your fate is a holy act.  As in the Bhagavad Gita: "Destruction in the course of performing one's own duty is better than engaging in another's duties, for to follow another's path is dangerous."</p></div>
<div data-ident="05-023" class="commenthidden" ><p>Welcome our great Hero to the story.  Over the remaining lessons, a reader might become somewhat confused by Nerevar's behavior; it's certainly far from clever.  Even if we consider this as Nerevar's "education" on becoming a hero, other historical documents indicate that Nerevar was far more instrumental and effective during these times than as depicted in the 36 Lessons.</p><p>Clearly Nerevar's behavior in later Sermons serves the same purpose as everything else in the Lessons: to expand upon and describe Vivec's process of becoming divine, and hir discovery and exploration of the true nature of the universe, as well as what will be required of hir in the future.  It's a story about one person: the author.</p></div>
<?php include 'middle.php' ?>
<p>Finally the simulacrum of the netchiman's wife became <span class="lessonlink" data-call="05-001">unstable</span>. The Dwemer in their haste had built it shoddily and the ashes of Red Mountain slowed its <span class="lessonlink" data-call="05-002">golden tendons</span>. Before long it fell on its knees beside the road to the lands of the Indoril and pitched over, to be discovered <span class="lessonlink" data-call="05-003">eighty days later</span> by a <span class="lessonlink" data-call="05-004">merchant caravan</span> on its way to the capital of Veloth, <span class="lessonlink" data-call="05-005">anon Almalexia</span>.</p>
<p>Vivec had not been among his people <span class="lessonlink" data-call="05-006">all the days of his pre-life</span> so he stayed silent and let the Chimer in the caravan think that the simulacrum was broken and empty. A Chimer warrior, who was protecting the caravan said, 'Look here how the Dwemer try to fool us as ever, crafting our likenesses out of their <span class="lessonlink" data-call="05-007">flesh-metals</span>. We should take this to the capital and show <span class="lessonlink" data-call="05-008">our mother Ayem</span>. She will want to see this new strategy of our enemies.'</p>
<p>But the merchant captain said, 'I doubt that we shall be paid well for the effort. We can make more money if we stop at <span class="lessonlink" data-call="05-009">Noormoc</span> and sell it to the <span class="lessonlink" data-call="05-010">Red Wives</span> of Dagon, who pay well for the wonders made by the Deep Folk.'</p>
<p>But another Chimer, who was wise in the ways of prophecy, looked on the simulacrum with disquietude. '<span class="lessonlink" data-call="05-011">Was I not hired on to help you seek the best of fortunes</span>? I say you should listen to your warrior, then, and take this thing to Ayem, for though manufactured by our enemies there is something in it that <span class="lessonlink" data-call="05-012">will become sacred</span>, or has been already.'</p>
<p>The merchant captain took pause then and looked on the simulacrum of the netchiman's wife and, though he heeded always the advice of his seers, could do no more than think of the profits to be made at Noormoc. He though (sic) mainly of the Red Wives' form of recompense, which was <span class="lessonlink" data-call="05-013">four-cornered and good wounded</span>, a <span class="lessonlink" data-call="05-014">belly-magic</span> known <span class="lessonlink" data-call="05-015">nowhere else under the moons</span>. His lust made him deny Ayem his mother. He gave order to change course for Noormoc.</p>
<p>Before the caravan could get underway again, the Chimeri warrior who had counseled a passage to the capital threw his money to the merchant captain and said, 'I will pay you thus for the simulacrum and warn you: war is coming with the <span class="lessonlink" data-call="05-016">shaggy men of the north</span> and I will not have my mother Ayem at uneven odds with one enemy while tending to another.'</p>
<p>'Nerevar,' the merchant captain said, 'this is not enough. I am Triune in my own way, but I follow the road of my body and demand more.'</p>
<p>The Vivec <span class="lessonlink" data-call="05-017">could not remain silent anymore</span> and said into Nerevar's head these words:</p>
<p><span class="lessonlink" data-call="05-018">'You can hear the words, so run away</span></p>
<p>Come Hortator, <span class="lessonlink" data-call="05-019">unfold into a clear unknown</span>,</p>
<p><span class="lessonlink" data-call="05-020">Stay quiet until you've slept in the yesterday</span>,</p>
<p><span class="lessonlink" data-call="05-021">And say no elegies for the melting stone</span>.'</p>
<p>So Nerevar slew the merchant captain and <span class="lessonlink" data-call="05-022">took the caravan for his own</span>.</p>
<p><span class="lessonlink" data-call="05-023">The ending of the words is ALMSIVI</span><a href="../css/images/36rages/<?php echo pad($sermon); ?>.png">.</a></p>
<?php include 'footer.php' ?>