<?php
$sermon = '7';
include 'header.php';
?>
<div data-ident="07-000" class="commenthidden" ><p>Sermon Seven leaves Vivec's narrative point of view and plunges us briefly into the realm of the Daedra. We'll watch as the Duke of Scamps has his legions of troops reviewed by a representative of Mehrunes Dagon, and then everybody talks about how based ALMSIVI is.</p><p class="horizline"></p><p>In Morrowind, Sermon Seven grants a bonus to the Block skill.  It is worth 200 Septims and weighs 3 units.  A copy can be found in the Temple at <a class="external" href="http://www.uesp.net/wiki/Morrowind:Molag_Mar" target="_blank">Molag Mar</a>, and another in <a class="external" href="http://www.uesp.net/wiki/Morrowind:Tureynulal" target="_blank">Tureynulal</a> at Kagrenac's Library.</p><p>Sermon 29 names this Sermon "The Sword at the Center."  Its number is 39, which references the word "His."</p></div>
<div data-ident="07-001" class="commenthidden" ><p>Contrary to whatever impression you might've received while playing Elder Scrolls 4: Oblivion, or even for that matter a cursory examination of the structure of the Aurbis, "Oblivion" is not a single location, but rather an entire dimension.  It can be thought of as a place that surrounds Mundus, the mortal dimension, on all sides.  This is why this line is phrased "from the oblivion," rather like one might say "from the West," or "from the South."  This can be a very difficult concept to grasp.</p><p>In practical application, this means that Mehrunes Dagon, during his invasion of Nirn in the last years of the 3rd Era, didn't use his gateways to reduce travel time from his plane of Oblivion into Mundus, like highways or a teleporter.  Rather they acted as "doorways," used to enter a room that did not exist previous to the door's construction.  It's wibbly-wobbly timey-wimey stuff, except it isn't.  It's actually very solid math.</p></div>
<div data-ident="07-002" class="commenthidden" ><p>So apparently scamps have a hierarchy of some kind?  It's hard to tell from the games alone, but it seems quite obvious in the 36 Lessons that the Daedra have not only a culture, but politics and relationships.  This is expanded upon as early as Elder Scrolls Adventures: Battlespire.</p><p>Furthermore, Scamps at this point in the lessons are not the diminutive irritants that they are in the games.  It's not until Molag Bal curses them in Sermon 14 that they become the largely useless critters we now know and frequently wreck.</p></div>
<div data-ident="07-003" class="commenthidden" ><p>The concept of the House of Troubles is not unfamiliar to most Elder Scrolls fans.  Consisting of Molag Bal, Mehrunes Dagon, Malacath, and Sheogorath, the House of Troubles represent the four most untrustworthy Daedra known.</p><p>Most Daedra are largely ambivalent to the needs of mortals.  They prefer to play with them, like a cat plays with a dying mouse.  Some Daedra seem to have something like a fondness for mortals, and actively aid them.  But the four members of the House of Troubles are clearly enemies of all mortal life.</p><p>What's interesting about this depiction is that the Lessons suggest that there is an actual House involved, and that it isn't just a figure of speech.  Traditionally it's thought that the Daedra each occupy their own dimension of Oblivion, separated from each other's powers and influences.  Considering the contritious and destructive nature of these Gods, that option seems safer to me.</p><p>That isn't really a huge leap.  Often in the Elder Scrolls universe, a metaphor can sometimes turn out to be literal, to be both real and imaginary.</p><p>Although I can't help but wonder if perhaps the House of Troubles is actually a gateway-dimension, of sorts.  Like a path through which a traveller can access the four distinct planes of Oblivion of each Daedric Prince.</p></div>
<div data-ident="07-004" class="commenthidden" ><p>I think the House of Troubles is arranged like a fortress of some kind, with multiple layers of hallways and battlements that must be entered sequentially.  Alternatively, this could be a series of engraved doors down one length of hallway, I suppose.</p></div>
<div data-ident="07-005" class="commenthidden" ><p>The positively bizarre representative of Mehrunes Dagon serves as Dagon's "chief of staff," so to speak.  His butler.  What, you think Dagon's gonna answer his own door?  Nah.</p></div>
<div data-ident="07-006" class="commenthidden" ><p>The Daedric Prince of destruction.  Many of you may remember him as the Big Bad Guy from Elder Scrolls IV: Oblivion.</p><p>Though his true motivations change depending on who you ask, Dagon appears to be solely concerned with the wholesale destruction of Tamriel and everything on the face of Nirn.  Why?  In my opinion, because it's his nature.  Simple as that.  But other myths, such as the Leaper Demon King's story in the Seven Fights of the Aldudagga, suggest that Dagon has been "cursed" with his nature.</p></div>
<div data-ident="07-007" class="commenthidden" ><p>This is a title that sticks out to me, because as far as I know it's not really well-reflected in lore after Morrowind.  I suppose a fairly literal interpretation would be that fire is a destructive force, though I can only consider "foul water" as the carrier of disease, not destruction.</p><p>But if we think about the two as elements of fear, it starts to make a little more sense.  Much of Morrowind's symbolism and metaphor borrow from early religions, when foul waters and fire were both quite frightening.  Foul water, for example, is quite lethal without proper medical care. And I'm sure I don't need to explain the primal dangers of fire.</p></div>
<div data-ident="07-008" class="commenthidden" ><p>That Duke Kh-Utta has seven legions is interesting.  Numerology in many Christian and Judaic cultures imbues the number Seven with a holy power, as though it is the "perfect" number of God.</p><p>In Sermon 29 we will discover that the number Seven is associated with the Sword at the Center.</p></div>
<div data-ident="07-009" class="commenthidden" ><p>I'm not entirely convinced that the seven scamp legions have one-to-one analogs with other Elder Scrolls concepts.  Some of the descriptions of the armies seem to correlate with various races on Nirn, but the variance is too strong to create a reliable link.  And besides, why should the Duke of Scamps command aspects of the mortal races?</p><p>It seems to me slightly less unlikely that Duke Kh-Utta's legions borrow negative aspects from seven races.  This would illustrate the moral lesson that a collection of people exhibit negative or evil acts and emotions as influenced by a Daedric force.  This, however, also seems out of character considering the nebulous definitions of "good" and "evil" in the Lessons.</p><p>Rather, it's safer to assume that the Seven Legions are types of Daedra that were knocked around during the conceptual stages of Morrowind's development, or something as simple as ideas Kirkbride had in his head.</p></div>
<div data-ident="07-010" class="commenthidden" ><p>So this is symbolically interesting.  The major domo's head is composed of Dagon's two mastered elements, but can you visualize them as one?  A fire within water would be extinguished.  Water near fire evaporates.  Is the fire within the globe of water, or does it surround it?  Either way, this raises an interesting observation about the nature of Dagon's elements.</p><p>Dagon's elements of water and fire are chiral elements; opposites that cannot exist in harmony.  The combination of chiral elements is, as we all know, an Enantiomorph.  You'll see a lot of these, of course, but they are nearly always the markers of divinity, for reasons which we will explore in later comments.</p></div>
<div data-ident="07-011" class="commenthidden" ><p>Apparently this is how the two Daedra communicate with each other.  The major domo seems to be looking into Kh-Utta's mind to see the seven legions the Duke has promised.</p></div>
<div data-ident="07-012" class="commenthidden" ><p>Yeah, yeah, I know I said I didn't think there was a link between these legions and anything else in the TES universe, but let's give 'em a shot anyway.</p></div>
<div data-ident="07-013" class="commenthidden" ><p>Nothing comes to mind immediately. Something about this line reminds me of Nords but I can't place what, exactly. Beyond that, to "die at least twice" makes me think of the undead, or perhaps an army that has enough necromancers to reanimate fallen warriors.</p></div>
<div data-ident="07-014" class="commenthidden" ><p>The easiest conclusion is that this is a reference to Morihaus and the Emperor of Cyrodiil. A more accurate (or obvious) way to refer to the Emperor would be as the "red" Emperor, the color being a reference to (among many things) the blood-red stone in the Amulet of Kings.</p></div>
<div data-ident="07-015" class="commenthidden" ><p>A Gorgon is a creature from Greek mythology that traditionally (but not always) possesses snake-like features. Often they are depicted as having a reptilian lower-torso. Inverted, in this case, means the upper torsos of these demons are reptilian. Easily this brings to mind the Tsaesci, a race of snake-like creatures from Akavir.  Similar to the Gorgon of myth, the description of a Tsaesci varies depending on who's telling the tale.</p><p>That they have scales shaped like the faces of men is interesting as well, since the Tsaesci are often rumored to be shape-shifters.</p><p>And if they aren't the Tsaesci, could this be the Argonians?</p><p>Alignments like these are confusing energies. If we're not supposed to assume that these legions are allegorical, why the stunning similarities?</p></div>
<div data-ident="07-016" class="commenthidden" ><p>In answer to the question posed at the end of the previous comment: here's why. Without exploring possible connections, a legion of double-crossed lovers makes sense, since they certainly have cause for fury.</p><p>But what similarities can you find, if any?</p></div>
<div data-ident="07-017" class="commenthidden" ><p>It's been suggested that this could be a nod to Peryite, the Daedric Prince of disease, but I'm dubious. And besides, either these legions are other princes, or they are other races, right?</p><p>But could they be both? It's not out of character for the Dunmer (a xenophobic race, on balance) to refer to other "not-Dunmer" collectively as demons.</p></div>
<div data-ident="07-018" class="commenthidden" ><p>You can go a few ways with this one. Some people consider it a reference to the Dwemer, since they give a shortened list of planets in Sermon 3.</p><p>But since Gods are Planets (or at least Aedra), are these divine but weakened creatures of some kind?</p></div>
<div data-ident="07-019" class="commenthidden" ><p>Something about this reminds me strongly of the Barons of Move Like This. Could this be a Redguard reference?</p></div>
<div data-ident="07-020" class="commenthidden" ><p>Interesting that the Duke of Scamps should be summoned by Dagon the Razor considering his name sounds like "cutter."</p></div>
<div data-ident="07-021" class="commenthidden" ><p>So what are Duke Kh-Utta's legions? If they're representations of mortal races, they're short a few, to say the least. I think it's far more likely that they serve as an opportunity to gain a glimpse into the complex world of the Daedra.</p></div>
<div data-ident="07-022" class="commenthidden" ><p>I think this is the thrust of this Sermon. It illustrates that Duke Kh-Utta possesses a mighty army, and furthermore that he is suggesting an alliance with Mehrunes Dagon, the Prince of Destruction. Yet Dagon's own majordomo is so in awe of the power of Nerevar and ALMSIVI that he insists that these forces are insufficient.</p><p>Whether this is technically truthful or not is irrelevant, since the 36 Lessons serve to teach and to convince, not to tell an accurate history. For all we know, this meeting never actually took place. Or maybe it didn't take place until Vivec wrote this sermon and made it take place, retroactively.</p></div>
<div data-ident="07-023" class="commenthidden" ><p>This could be another way to speak of the Tribunal, even before their formation in the next Sermon, at the "birthing" of Vivec. But it could be that the majordomo is speaking of the larger issue, that of the Tribunal's religion, of the practice of worshipping ALMSIVI.</p><p>I would go another step and suggest that there is no difference between the religion of ALMSIVI (the "Triune way") and ALMSIVI itself. That when we speak of "ALMSIVI" we don't refer to AYEM, SEHTI, and VEHK, but rather to the over-entity, the Tribunal and their worshippers and their practices as a single multi-faceted concept. It's the difference between the Holy Trinity and Christianity as a whole.</p></div>
<div data-ident="07-024" class="commenthidden" ><p>I've heard a lot of people refer to this as a reference to Middle Earth in the Lord of the Rings, and I think that's probably a miss.</p><p>In this case, the "middle world" probably refers to the realm between the Sea (the lower) and the Stars (the upper). This is a philosophy common to many Eastern religions.</p><p>It could also refer to the nature of Mundus, Nirn's dimension, as being between Oblivion and Mortal Death in the sub-gradient structure of the Aurbis, but this seems a little weak to me.</p></div>
<div data-ident="07-025" class="commenthidden" ><p>This poem illustrates the way the Daedra feel when they watch ALMSIVI at work, collecting the "heat," or desire and prayers of the Dunmer that used to go to the Daedra. They think of the wars to come, of the opportunities to gain in power from the tribute that is now placed on the doorstep of the Tribunal.</p></div>
<div data-ident="07-026" class="commenthidden" ><p>Interestingly, it seems as though Vivec is taking credit for Nerevar's "marks" that distinguish him as a mortal of great promise and destiny. In What My Beloved Taught Me, we discover that Vehk read the palms of Nerevar and saw his destiny already written there.</p><p>So once again, Vivec takes credit for every major event in Dunmer history, with possibly the exception of the Velothi exodus.</p><p>But here's another thought: what if, even before Vivec "re-created" hir reality by hir own Will, the destinies of Vehk and Nerevar were already intertwined? If there is no coincidence, is there also no free will? What if Vivec's betrayal of Nerevar was always destined to happen?</p><p>If that is true, then perhaps Vivec really is the cause of Nerevar's words of power?</p></div>
<div data-ident="07-027" class="commenthidden" ><p>"Weapons" of "Padomay," or change. Nerevar has, quite literally, marks upon his hands that declare him a weapon or tool of change, as though he wields the very will of Padomay itself. In the scope of the 36 Lessons, these two words are used to describe the Hortator himself, whether the Nerevarine or Nerevar.</p><p>This "marking" can be found in a number of real-world fables and myths. Heroes are sometimes marked directly by a God, or born with a birthmark. Or perhaps certain events early in their lives have led them to bear a unique mark that distinguishes them from the crowd. I'm thinking specifically of Harry Potter here, in case that isn't obvious, but there's so many examples it's almost impossible to miss them, if you look.</p><p>It might seem unusual that truly great Heroes are (traditionally) born into the role, rather than achieving their accolades through hard work, starting from the same "common dirt" as everyone else. The difference is due to the purpose of myths. Do they serve to encourage the average person to achieve greatness? Or do they instead serve to illustrate a larger moral lesson, or to propose a philosophical conundrum?</p><p>The more specific you get, the more complex the issue becomes. Is the Hero born into auspicious circumstances so there can be some sort of internal struggle when the Hero inevitably leaves for "adventure," or its equivalent?</p><p>You know, I'm going to stop right now before I end up writing way too much about this. Just go read your Jung and your Campbell if you have any questions. It should be required reading in anybody's library, anyway.</p></div>
<div data-ident="07-028" class="commenthidden" ><p>So what have we learned from this Sermon? It's possible that it exists largely for purposes of politics and dogma: to reinforce the sheer dominating power of ALMSIVI. Despite its sphere of destruction, Mehrunes Dagon itself sees certain doom at the hands of Nerevar and the Tribunal, even when reinforced by seven legions of scamps.</p><p>It might also explain one or more reasons why the Daedra largely leave Morrowind alone, even though the large amount of Daedric worship in Morrowind might otherwise make invasion easy.</p><p>I think an important thing to take away from this Sermon is Nerevar's hands of destiny. Vivec has destroyed coincidence, so it stands to reason that Nerevar must be destined to achieve greatness.</p></div>
<?php include 'middle.php' ?>
<p>As the caravan of Nerevar now made for the capital of Veloth, anon Almalexia, there came great rumblings <span class="lessonlink" data-call="07-001">from the oblivion</span>. A <span class="lessonlink" data-call="07-002">duke among scamps</span> wandered into the <span class="lessonlink" data-call="07-003">House of Troubles</span>, <span class="lessonlink" data-call="07-004">pausing before each scripture door</span> to pay his respects, until finally he was met by the <span class="lessonlink" data-call="07-005">major domo</span> of <span class="lessonlink" data-call="07-006">Mehrunes Dagon</span>.</p>
<p>The Duke of Scamps said, 'I was summoned by Lord Dagon, <span class="lessonlink" data-call="07-007">master of the foul waters and fire</span>, and I have brought the pennants of my <span class="lessonlink" data-call="07-008">seven</span> <span class="lessonlink" data-call="07-009">legions</span>.'</p>
<p>The major domo, whose head was a <span class="lessonlink" data-call="07-010">bubble</span> of foul water and fire, bowed low, so that the head of the Duke of Scamps became <span class="lessonlink" data-call="07-011">enclosed</span> in his own.</p>
<p>He saw the <span class="lessonlink" data-call="07-012">first pennant</span>, which commanded a legion of <span class="lessonlink" data-call="07-013">grim warriors</span> who could die at least twice.</p>
<p>He saw the second pennant, which commanded a legion of <span class="lessonlink" data-call="07-014">winged bulls and the emperor of color</span> that rode upon each.</p>
<p>He saw the third pennant, which commanded a legion of <span class="lessonlink" data-call="07-015">inverted gorgons</span>, great snakes whose scales were the faces of men.</p>
<p>He saw the fourth pennant, which commanded a legion of <span class="lessonlink" data-call="07-016">double-crossed lovers</span>.</p>
<p>He saw the fifth pennant, which commanded a legion of <span class="lessonlink" data-call="07-017">jumping wounds</span> looking to hop onto a victim.</p>
<p>He saw the sixth pennant, which commanded a legion of <span class="lessonlink" data-call="07-018">abridged planets</span>.</p>
<p>He saw the seventh pennant, which commanded a legion of <span class="lessonlink" data-call="07-019">armored winning moves</span>.</p>
<p>To which the major domo said, '<span class="lessonlink" data-call="07-020">Duke Kh-Utta</span>, <span class="lessonlink" data-call="07-021">your legions</span> while mighty are <span class="lessonlink" data-call="07-022">not enough</span> to destroy Nerevar or <span class="lessonlink" data-call="07-023">the Triune way</span>. Look upon the Hortator and see the wisdom he takes to wife.'</p>
<p>And they looked into the <span class="lessonlink" data-call="07-024">middle world</span> and saw:</p>
<p><span class="lessonlink" data-call="07-025">Evaporating in a throng of thunder</span></p>
<p>Of red war and chitin men,</p>
<p>Where destines</p>
<p>Take him further from our ways</p>
<p>The heat that we have wanted</p>
<p>And pray they still remember,</p>
<p>Where destines</p>
<p>Clothe the distance,</p>
<p>Glad in the golden east that we saw it now,</p>
<p>Instead of the war and repair</p>
<p>Of the oblivious fracture</p>
<p>A curse on the Hortator</p>
<p>And two more on his hands</p>
<p>And the Duke of Scamps saw the palms of the Hortator, upon which <span class="lessonlink" data-call="07-026">the egg had written</span> these words of power: <span class="lessonlink" data-call="07-027">GHARTOK PADHOME</span> GHARTOK PADHOME.</p>
<p><span class="lessonlink" data-call="07-028">The ending of the words is ALMSIVI</span><a href="../css/images/36rages/<?php echo pad($sermon); ?>.png">.</a></p>
<?php include 'footer.php' ?>