<?php
$sermon = '8';
include 'header.php';
?>
<div data-ident="08-000" class="commenthidden" ><p>Sermon Eight shows us the formation of ALMSIVI, at least in spiritual form, uniting Almalexia (the Warrior) and Sotha Sil (the Mage) through Vivec (the Thief).</p><p class="horizline"></p><p>In Morrowind, Sermon Eight grants a bonus to the Athletics skill.  It is worth 200 Septims and weighs 3 units.  A copy can be found in the Temple at <a class="external" href="http://www.uesp.net/wiki/Morrowind:Molag_Mar" target="_blank">Molag Mar</a>, and another in the Temple at <a class="external" href="http://www.uesp.net/wiki/Morrowind:Ald%27ruhn" target="_blank">Ald'ruhn</a>.</p><p>Sermon 29 names this Sermon "The Wheel, or the Eight Givers."  Its number is 484, which references the word "destiny."</p></div>
<div data-ident="08-001" class="commenthidden" ><p>The idea is that you have musicians playing along side your caravan, announcing its position to all would-be assailants. Any caravan bold enough to broadcast its presence to thieves is clearly capable of handling them, or so the thinking goes. Also, some escort services powerful enough to garner a reputation of being difficult to waylay might play a particular theme as more of a warning than anything else.</p><p>And if people hear your caravan and recognize the banners, that's a bit like free advertisement. And of course you can use the noise to announce your arrival, as depicted.</p><p>I swear this is a thing that happens in both Eastern and Western cultures but I'm having a hell of a time finding a reference for either.</p></div>
<div data-ident="08-002" class="commenthidden" ><p>Later, in Sermon 29, we'll discover that the number 11 belongs to "the Master," a title given to any powerful and enlightened being. That the capital of Veloth has 11 gates is probably intentional, but it does not necessarily designate Almalexia as a Master herself.</p></div>
<div data-ident="08-003" class="commenthidden" ><p>Almalexia's city, known in other texts as "Mournhold," has an interesting name. But I haven't found any history to it, so I'm not aware of anything "mourning" related that might involve the city itself. Considering this city existed in games as far back as the first Elder Scrolls game, I don't think much more thought was put into its title other than that it should sound "dark elf-ish."</p></div>
<div data-ident="08-004" class="commenthidden" ><p>Does it seem odd that Almalexia already seems to have a husband, even before Nerevar's arrival? Or is this entity a "husband" in service only?</p><p>The "state" probably refers to the mutable, ever-changing nature of this entity. But can you imagine what might be implied if it instead meant a "state," as in a selection of a country?</p></div>
<div data-ident="08-005" class="commenthidden" ><p>Remember in Sermon 1 that Vivec was described by Almalexia as "an egg, and an image." In Sermon 25 we'll spend some time analyzing the Promise of the PSJJJJ, which include these terms. But quickly, let's just talk about "images" as they seem to lie in the symbolism of the 36 Lessons.</p><p>Let's read a passage from Carl Jung's <a class="external" href="http://en.wikipedia.org/wiki/Red_Book_%28Jung%29" target="_blank">Red Book</a>:</p> <blockquote><p>If we possess the image of a thing, we possess half the thing. The image of the world is half the world. He who possesses the world but not its image possesses only half the world, since his soul is poor and has nothing. The wealth of the soul exists in Images.  He who possesses the image of the world, possesses half the world, even if his humanity is poor and owns nothing. But hunger makes the soul into a beast that devours the unbearable and is poisoned by it. My friends, it is wise to nourish the soul, otherwise you will breed dragons and devils in your heart.</p></blockquote><p>In this case, and as I'll discuss at length in the next comment, Almalexia's "husband-state" is not a true husband, not a complete person.</p></div>
<div data-ident="08-006" class="commenthidden" ><p>That this creature meets Almalexia's "need" does not have to have a sexual connotation. Instead, it could be an entity that changes in appearance to match Ayem's wardrobe, or its behavior to match her emotional desire.</p><p>Or perhaps it does service her sexually. We could think of this as a sign that Almalexia's marriage to Nerevar was not one based on lust, especially if this husband-state already satisfied every need she had. Or it could tell us that Almalexia is not a spinstress, or a helpless and suppressed (or repressed) maiden who clings to some ridiculous sense of virginal value, like a fantasy-genre trope. If that's the case, then Almalexia may have truly married Nerevar for love, if not political purposes.</p><p>Either way, one thing is certain: Almalexia is not married to a true individual, a real living being, an actual person. Though this creature may be called a "husband," this probably only serves as confirmation that it services her sexual desires. This could imply (depending on your viewpoint) that Almalexia's marriage to Nerevar was a happy one, at least at some point.</p><p>With most interpretations, Almalexia comes out of it as a formidable leader. Even the most sexist presumptions seem impossible to apply to her.</p></div>
<div data-ident="08-007" class="commenthidden" ><p>I'm going to stop you right here and make sure you're not thinking that this is a Thu'um reference. It's probably not that.</p><p>A guild that represents the people might be called "the Shouts" as a commentary on the mob mentality of the masses. Picture a crowd of people at a rally, all shouting their slogans at the top of their lungs. This guild is loud, and probably obnoxious, but they represent the will of the masses, and that is why they are important enough to be invited to witness the arrival of ALMSIVI.</p></div>
<div data-ident="08-008" class="commenthidden" ><p>Maybe this is an unintended glance into Vivec's hidden feelings on the Velothi. As the 36 Lessons unfold, Vivec's narration seems to imply that ze is becoming increasingly dissatisfied with hir own people. Later, in Sermon 33, Vivec will take steps to ensure that the Velothi people do not stray too far from hir path.</p><p>But as we know, by the time Elder Scrolls 3: Morrowind begins, a great deal of sedition is being found among the Dunmer. The <a class="external" href="http://www.uesp.net/wiki/Lore:Dissident_Priests" target="_blank">Dissident Priests</a> have gained enough traction and influence to begin distributing <a class="external" href="http://www.uesp.net/wiki/Lore:Progress_of_Truth" target="_blank">religious texts</a> questioning the new Tribunal culture and their leadership.</p><p>The decay of Tribunal culture, incidentally, mirrors the decline of its creators. The longer the members of ALMSIVI remain separated from the Heart of Lorkhan the more they decline in both power and sanity. Vivec sinks lower into depression and ambivalence, Sotha Sil retreats further into his own reality, the Clockwork City, and Almalexia apparently descends into madness.</p></div>
<div data-ident="08-009" class="commenthidden" ><p>This is probably the repetition of a theme that pops up from here to there in Elder Scrolls lore, which (to my knowledge) originated from the study of Arthurian legends. The concept is often abbreviated as "the King and the Land are One," and is shown most clearly the story of the <a class="external" href="http://en.wikipedia.org/wiki/Fisher_King" target="_blank">Fisher King</a>. When overly simplified, this mythical concept directly links a King with the Land he governs. When the King is "good" (in various ways), the land reflects this goodness with fertility and beauty. An "evil" King rules over a dark and sinister landscape.</p><p>If that principle is reflected in Morrowind's mythology, what does the current state of Morrowind say about its King, Almalexia? Would you argue that Morrowind is the landscape of a "good" or a "bad" King? At the beginning of the game, who is the King of Morrowind?</p></div>
<div data-ident="08-010" class="commenthidden" ><p>It does seem as if Sotha Sil is at least a little comfortable with guiding the ignorant. In <a class="external" href="http://www.uesp.net/wiki/Morrowind:2920,_The_Last_Year_of_the_First_Era" target="_blank">2920, the Last Year of the First Era</a> we see him teaching mortal mages in the Summerset Isles.</p><p>Both this section and the one before seem to show a snide contempt that Vivec holds for hir own people. Whether this seems true or not is entirely subjective. But it's not impossible that a self-made God might become at least a little dissatisfied with a complacent or seemingly helpless mass.</p><p>And yet, let's consider the possibility that the Lessons are affording a unique glimpse into Vivec's most private, hidden emotions. Much of What My Beloved Taught Me suggests that Vivec began hir mortal life as a hood rat, a thief, a skooma dealer, and a prostitute. Ze struggled to survive in the shadow of Vvardenfell's capital city of Mournhold. Every day ze rubbed elbows with thieves, drug addicts, perverts, and murderers.</p><p>Are these little moments of contempt a sign that mortal Vivec was disgusted by hir fellow Chimer? It certainly seems plausible to me.</p><p>But what's really interesting, in my opinion, is how carefully concealed this anger has been portrayed in the narrative. Perhaps Vivec doesn't want to show this side of hirself to hir people. Maybe the original text has been "cleaned up" by the Tribunal Temple, although evidence of their influence in later chapters tends to be more ham-fisted. And this could be Vehk the Mortal speaking through hir God-self, but it seems unlikely since the clear examples we have of this are far more obfuscated.</p></div>
<div data-ident="08-011" class="commenthidden" ><p>Has Vivec basically just sort of yada-yada'd over Nerevar's rise to power in House Indoril? You can't just yada-yada over the most interesting part, Vivec.</p></div>
<div data-ident="08-012" class="commenthidden" ><p>I think Reman's ears are burning.</p></div>
<div data-ident="08-013" class="commenthidden" ><p>What did Nerevar learn? Sermon Six is the answer. Vivec encourages caution, stealth, and cleverness. From this education, Nerevar concludes that the best course is to maintain a rocky peace with the Dwemer.</p><p>Do they do this so that they can better defend themselves against the Nords? Or so that Vivec can get closer to the Heart of Lorkhan?</p></div>
<div data-ident="08-014" class="commenthidden" ><p>Vivec is an Egg and an Image riding in the "skin" or body of Dwemer make. This is a theme or a tactic that will be revisited several times in the 36 Lessons.</p><p>"Hiding" in skin might seem like something that refers to race, and it does. Vivec is suggesting the exploitation of other people's prejudices and ignorance for the benefit of the Chimer / Dunmer. This is very much within the Thief's modus operandi.</p><blockquote><p>You have to be trusted by the people that you lie to</p><p>So that when they turn their backs on you</p><p>You'll get the chance to put the knife in.</p></blockquote></div>
<div data-ident="08-015" class="commenthidden" ><p>Again, something's telling me he's talking about the Heart of Lorkhan.</p></div>
<div data-ident="08-016" class="commenthidden" ><p>Again with the skin and deception. In this case, Boethiah disguised herself as Trinimac and spoke Truth to the Chimer, and in turn they performed the exodus of the Velothi.</p><p>But this possibly reveals another wrinkle in the wearing of another's skin: it seems to change you, in turn. Or perhaps the change must also be a change in nature. In other words, must it be more than skin deep?</p><p>But maybe changing first in nature can produce a change in appearance?</p></div>
<div data-ident="08-017" class="commenthidden" ><p>Another reference to Sermon Six and the Fourth Walking Way. Boethiah "mantled" Trinimac. Can you see the similarities between Vivec's advice (hiding in the skin of your enemies) and Mantling (walking like them until they walk like you)?</p></div>
<div data-ident="08-018" class="commenthidden" ><p>I wonder about this. The description of Sotha Sil's powerful form of mysticism seems to use seemingly contradictory elements (a metal, Iron, and a gas, vapor). But as we've already seen demonstrated, the nature of divinity is often depicted as the union of disparate elements.</p><p>Apparently the temperature at which Iron vaporizes is 2,862 degrees Celsius, or 5,182 degrees Fahrenheit. That's pretty damn hot.</p></div>
<div data-ident="08-019" class="commenthidden" ><p>I'm thinking these might be creatures Sotha Sil has personally animated but I don't have anything to back that up. Daedra, perhaps?</p></div>
<div data-ident="08-020" class="commenthidden" ><p>As in the "reincarnation" of Mephala, I should think. Born in auspicious conditions and destined for greatness, just like any good mythic hero.</p></div>
<div data-ident="08-021" class="commenthidden" ><p>Is Vivec speaking of the rhymes (remember: warrior poet) within the rituals and ordeals? Or of the rituals and ordeals and rhymes within hir skin? Yet another example of where the Oxford Comma could come in handy.</p></div>
<div data-ident="08-022" class="commenthidden" ><p>The simplest thing to say here is that Vivec is preparing to reveal hir skin, to shrug off (or absorb) the skin of the Dwemer. But it could also be a metaphor for the act of being born.</p><p>But it's impossible to ignore the religious connotations of the word. And the widest definition of the term would be the disclosure of knowledge or truth, which is also an excellent way to think about the "birth" of Vivec: not as the birth of an organism, but rather (or also) the birth of a philosophy, of knowledge, of a new universal truth.</p><p>Birth in general is an extremely religious and metaphysical event. There's, well, there's quite a lot to be found if you explore.</p><p>And I think it's appropriate that the Warrior Poet marks this occasion with a verse.</p></div>
<div data-ident="08-023" class="commenthidden" ><p>The Ehlnofex from Sermon One is repeated again, but this time as  a declaration and not as a prediction, or a spell. That the Tribunal can be named and expressed in the language of the Gods is appropriate, since they are Gods themselves. I think there is no closer guarantee of power than to have your name enter the dictionary of the divine.</p></div>
<div data-ident="08-024" class="commenthidden" ><p>This again leads me in the direction of ALMSIVI as three entities that form a fourth uber-entity. This is reflected in a wide range of real-world religions, but especially relevant are the various triple-deities in the Vedic religions. Not all Hindu religions support the Trimurti concept, but some do, and generally speaking they play to the tune of three Gods:</p> <ol><li>Brahma, the Creator</li><li>Vishnu, the Maintainer</li><li>Shiva, the Destroyer</li></ol> <p>This tribunal aligns well with this version of the Trimurti, in the respect that Brahma might be the Mage (the creative forces), that Vishnu would be the Warrior (the conservative forces), and Shiva of course would be the Thief (the force for change).</p><p>However, it's hard to pass up the obvious physical and thematic similarities between Vivec and Ardhanarishvara, a deity that creates a synthesis between Shiva and his consort, Parvati. It's interesting, I think, that Ardhanarishvara exemplifies the concept of the "the bisexuality and therefore the non-duality" (non-binary sexual nature) of the Supreme Being. From this, we can suggest that Vivec, as the very Godhead itself, transcends all known concepts of mortal sexuality, and I'd even suggest all concepts of mortal existence.</p></div>
<div data-ident="08-025" class="commenthidden" ><p>This is probably a very artful way of describing the incredible spiritual significance that Vivec commands. So powerful and vital is ze that even Vivec's footprints are considered holy information.</p><p>Later in the Lessons we'll discover that a person's feet are culturally tied to their power, to their essence. But we'll tackle that one later.</p></div>
<div data-ident="08-026" class="commenthidden" ><p>This is how Sotha Sil silences the Shouts. "Look, people. Vivec effortlessly produces things you want to know." Clearly they were so busy being noisy that they were unable to see the Truth in front of their eyes. He who knows, does not speak. He who speaks, knows not.</p></div>
<div data-ident="08-027" class="commenthidden" ><p>Because hir Mother was granted gills by the Dreugh, and the simulacrum was a duplicate of hir Mother, so Vivec now has gills.</p></div>
<div data-ident="08-028" class="commenthidden" ><p>This is a reference to the visitations of the Daedra and other God-like entities during the previous Sermons. The "arts" they granted Vivec were blended into hir essence as ze gestated in the womb of the Netchiman's wife.</p></div>
<div data-ident="08-029" class="commenthidden" ><p>Where the Egg joined with Sotha Sil's homunculi in Sermon One.</p></div>
<div data-ident="08-030" class="commenthidden" ><p>Burned by the gaze of Mephala in Sermon Two.</p></div>
<div data-ident="08-031" class="commenthidden" ><p>Encased by the Dwemer in the simulacrum of the Netchiman's wife in Sermon Three.</p></div>
<div data-ident="08-032" class="commenthidden" ><p>And eventually pitched over in Sermon Five, worn out by the ashes of Red Mountain.</p></div>
<div data-ident="08-033" class="commenthidden" ><p>This is more numerology. In Sermon 29, the number Six represents The Walking Ways, which are methods of attaining divinity. We'll be dealing with them extensively as these commentaries proceed.</p><p>"The Wise" is the title of Sermon Three, and probably represents ALMSIVI, or at least its three agents.</p><p>That Vivec is "Six times the wise" means that ze is six times three, or 18. And wouldn't you know it, Sermon 29 names Sermon 18 as "The Egg, or Six Times the Wise."</p><p>For more about how Vivec and the number 18 work together, wait until Sermon 29.</p></div>
<div data-ident="08-034" class="commenthidden" ><p>An axiom is a point from which reasoning can begin, a self-evident fact that requires no explanation, a fundamental principle. A "martial axiom" implies a basic, undeniable force of war.</p><p>That the term "axiom" is often applied to philosophy and language is not an accident. This is  again a combination of the Sword and the Word.</p></div>
<div data-ident="08-035" class="commenthidden" ><p>Since Vivec was anticipated by Mephala, the Daedric Prince of sex and murder, and ze is the Warrior Poet... Well, this shakes out easily.</p></div>
<div data-ident="08-036" class="commenthidden" ><p>As I've mentioned before, Vivec appears to be the only Intersexed mortal in all of Elder Scrolls history. Beyond that, while ze does share some things in common with hir brother and sister, ze is the only mortal-become-God that bridges the divinity between two other Gods.</p></div>
<div data-ident="08-037" class="commenthidden" ><p>There are a large selection of repeated themes in Dunmer lore, and one of them is the idea of being "different," for one reason or another. The Chimer are philosophically different from their Altmer brethren due to their decision to emphasize ancestral worship and to ignore the Aedra in favor of the Daedra. That difference was further pronounced after their appearances changed when they became the Dunmer.</p><p>That they go "in thunder" reminds us that the Dunmer embrace their different nature. They are proud of what sets them apart from the other Tamriellic races. That they are "ash-skinned" is not something to be ashamed of.</p><p>And the emphasis of one's skin is repeated as Vivec "grows" into the simulacrum. It's skin is replaced by Vivec's, the Dwemer concept replaced by the Dunmer, as it will be again.</p></div>
<div data-ident="08-038" class="commenthidden" ><p>Let me take a moment to explain why Vivec is such a vital part of ALMSIVI.</p><p>Look at the state of ALMSIVI without Vivec. Sotha Sil and Almalexia seem to sum up both "halves" of the God, as Yin and Yang seem to fully embody the sum of the Tao. This very neatly summarizes the nature of the Enantiomorph: two chiral entities. Perfect opposites.</p><p>But Vivec becomes necessary because two chiral entities cannot unify. The nature of Yin and Yang is that they are constantly in flux, continuously in struggle. Just as the interaction between Anu and Padomay create the Aurbis, opposites are never capable of true integration.</p><p>While Sotha Sil and Almalexia are certainly not at odds with each other, they are also incapable of fully realizing their true potential. This is what makes an enantiomorph so incredible: it achieves the impossible by allowing two diametrically opposed forces to unite into an entirely new force that is greater than the sum of its parts.</p><p>This achievement is normally considered entirely impossible, which is why Vivec must serve as the "bridge" between Almalexia and Sotha Sil. By attaining "Mastery," Vivec can serve as the vessel through which the impossible can be performed.</p><p>Very few people will argue that Sotha Sil, Almalexia, and Vivec are all true "Gods" in the traditional sense. Certainly they are incredibly powerful mortals. But ALMSIVI, a constructed super-being, is a fine contender for divinity.</p><p>Clearly, that is a Walking Way.</p><p>But which one?</p></div>
<div data-ident="08-039" class="commenthidden" ><p>And so Vivec is officially born. Not a mortal's birth, with screaming and fluids, but the magnificent birth of a God incarnate: effortless and free from the sin of pain and desire. This birth cannot happen before the members of ALMSIVI are united because, in a way, Vivec cannot (or should not) exist without them. Hir destiny is to create the bridge between opposites, and in doing so ze becomes both opposites, and therefore neither. Not a third element, but beyond even that. In a universe where there is either only One or Nothing, Vivec is something uniquely Other.</p></div>
<?php include 'middle.php' ?>
<p>And presently Nerevar and Vivec were within sight of the capital and the Four Corners of the House of Troubles knew that it was not time to contest them. The <span class="lessonlink" data-call="08-001">caravan musicians</span> made a great song of entrance and the <span class="lessonlink" data-call="08-002">eleven gates</span> of the <span class="lessonlink" data-call="08-003">Mourning Hold</span> were thrown wide.</p>
<p>Ayem was accompanied by her <span class="lessonlink" data-call="08-004">husband-state</span>, a <span class="lessonlink" data-call="08-005">flickering image</span> that was channeled to her <span class="lessonlink" data-call="08-006">ever-changing female need</span>. Around her were the <span class="lessonlink" data-call="08-007">Shouts</span>, a guild now forgotten, who carried with them the whims of the people, for the Velothi then were <span class="lessonlink" data-call="08-008">still mostly good at heart</span>. The Shouts were the counselors of <span class="lessonlink" data-call="08-009">Ayem and the country</span>, though they sometimes quarreled and needed Seht to <span class="lessonlink" data-call="08-010">wring them into usefulness</span>. Ayem approached Nerevar, who was by now <span class="lessonlink" data-call="08-011">adorned in the flags of House Indoril</span>. He gifted her with the simulacrum of the netchiman's wife and the egg of Vivec inside.</p>
<p>Ayem said to Nerevar:</p>
<p>'Seht who is Azura has revealed that <span class="lessonlink" data-call="08-012">war is come</span> and that the Hortator that shall deliver us will approach with a solution walking at his side.'</p>
<p>Nerevar said:</p>
<p>'I have traveled out of my way to warn you of the deceit of our enemies, the Dwemer, but I have <span class="lessonlink" data-call="08-013">learned much on the journey</span> and have changed my mind. This netchiman's wife you see at my side is a sword and a symbol and there is prophecy inside. It tells me that, like it, we must for a while be like he is and, as a people, <span class="lessonlink" data-call="08-014">cloaked in our former enemies</span>, and <span class="lessonlink" data-call="08-015">to use their machines without shame</span>.'</p>
<p>At which Vivec spoke aloud:</p>
<p>'Boethiah-who-is-you <span class="lessonlink" data-call="08-016">wore the skin of Trinimac</span> to cleanse the faults of Veloth, my Queen, and so it should be again. <span class="lessonlink" data-call="08-017">This is the walking way of the glorious</span>.'</p>
<p>Seht appeared out of a cloud of <span class="lessonlink" data-call="08-018">iron vapor</span> and his <span class="lessonlink" data-call="08-019">minions</span> made of their blood a chair. He sat beside Ayem and looked on the <span class="lessonlink" data-call="08-020">rebirth of mastery</span>. Vivec said to them, his Triune:</p>
<p>'My rituals and ordeals and all the rhymes <span class="lessonlink" data-call="08-021">within</span>,</p>
<p>Use no other motive than the <span class="lessonlink" data-call="08-022">revelation</span> of my skin.'</p>
<p>Ayem said:</p>
<p>'<span class="lessonlink" data-call="08-023">AYEM AE SEHTI AE VEHK</span>. We are delivered and <span class="lessonlink" data-call="08-024">made whole</span>, the diamond of the Black Hands is uncovered.'</p>
<p>Seht said:</p>
<p>'Wherever so he treads, there is <span class="lessonlink" data-call="08-025">invisible scripture</span>.'</p>
<p>To which the Shouts were <span class="lessonlink" data-call="08-026">silent in sudden reading</span>. Vivec then reached out from the egg all his limbs and features, merging with the simulacrum of his mother, <span class="lessonlink" data-call="08-027">gilled</span> and <span class="lessonlink" data-call="08-028">blended in all the arts</span> of the starwounded East, <span class="lessonlink" data-call="08-029">under water</span> and <span class="lessonlink" data-call="08-030">in fire</span> and <span class="lessonlink" data-call="08-031">in metal</span> and <span class="lessonlink" data-call="08-032">in ash</span>, <span class="lessonlink" data-call="08-033">six times the wise</span>, and he became the union of male and female, the magic hermaphrodite, the <span class="lessonlink" data-call="08-034">martial axiom</span>, the <span class="lessonlink" data-call="08-035">sex-death of language</span> and <span class="lessonlink" data-call="08-036">unique</span> in all the middle world. He said:</p>
<p>'Let us now guide the hands of the Hortator in war and its aftermath. For we go <span class="lessonlink" data-call="08-037">different</span>, and in thunder. <span class="lessonlink" data-call="08-038">This is our destiny</span>.'</p>
<p><span class="lessonlink" data-call="08-039">The ending of the words is ALMSIVI</span><a href="../css/images/36rages/<?php echo pad($sermon); ?>.png">.</a></p>
<?php include 'footer.php' ?>