<?php
$sermon = '10';
include 'header.php';
?>
<div data-ident="10-000" class="commenthidden" ><p>Sermon Ten of the 36 Lessons of Vivec includes lessons from both Boethiah and Vivec about the proper arts of warfare and how to deceive both your allies and your enemies.</p><p>Watch for some commentary by Boethiah on Convention and the creation of Mundus, as well as a strongly-worded warning about the dangers of misanthropy.</p><p class="horizline"></p><p>In Morrowind, Sermon Ten grants a bonus to the Short Blade skill.  It is worth 200 Septims and weighs 3 units.  A copy can be found in the <a class="external" href="http://www.uesp.net/wiki/Morrowind:Andules_Ancestral_Tomb" target="_blank">Andules Ancestral Tomb</a>, the <a class="external" href="http://www.uesp.net/wiki/Morrowind:Tureynulal" target="_blank">Eye of Duggan in Tureynulal</a>, and in the <a class="external" href="http://www.uesp.net/wiki/Morrowind:Vivec_Temple" target="_blank">High Fane</a> in Vivec city.</p><p>Sermon 29 names this Sermon "The Tribes of the Altmer."  Its number is 140, which references the word "not."</p></div>
<div data-ident="10-001" class="commenthidden" ><p>Here in Sermon 10 we discuss the lessons Vivec gave to Nerevar following the war against Skyrim that united all of Morrowind, Chimer and Dwemer, under one banner. The key to understanding this sermon is that it follows that victory, and that it applies to the new state of Veloth.</p></div>
<div data-ident="10-002" class="commenthidden" ><p>In Thelema, and other magical practices, an "Evoker" is frequently the Magician who is performing the summoning of energies. To evoke is to summon or call forth, though this summoned thing can be an abstract energy, or concept, or a spirit of some kind.</p></div>
<div data-ident="10-003" class="commenthidden" ><p>Remember from Sermon 01: the left hand is the hand in which power and will are held. The left hand is open and empty to show that the Evoker does not require weapons. Either this is a feint, to deceive the enemy that our intentions are peaceful, or this is a statement of how wicked badass we are.</p></div>
<div data-ident="10-004" class="commenthidden" ><p>Isn't this another Crowley thing, or maybe some other Gnostic mystical reference? Sure sounds familiar. The Egyptian Book of the Dead uses "coming forth" when discussing creation in many forms, including birth.</p><p>If the coming forth is always hidden, is this related to Vivec's nature as the "invisible warrior poet?" Is there some kind of theme of invisibility or obscurity that I'm missing here? Or is this an accidental congruence of terminology?</p><p>Confusion aside, the safest conclusion I can draw is that the "coming forth" is the approach of enemies. And that it is always hidden is because the actual threat is never presented. The enemy always approaches with a plan, or some element of cunning.</p></div>
<div data-ident="10-005" class="commenthidden" ><p>This is a reference to Resdaynia. Vivec is suggesting that the Velothi have hidden in the skin of their enemies, the Dwemer, pretending to be allies against their common Nordic foe.</p><p>This entire paragraph is poetically describing Sermon Nine. The Evoker is all of Veloth, or perhaps ALMSIVI and Nerevar. They summon their enemies, the Nords, who come forth invisibly (using stealth and guile) to do battle.</p></div>
<div data-ident="10-006" class="commenthidden" ><p>Here, Vivec begins to set up a metaphor to explain the purpose of the 36 Lessons. In this case, the "eyelid" of the Kingdom is that which conceals the Eye. The Kingdom is, of course, Morrowind.</p></div>
<div data-ident="10-007" class="commenthidden" ><p>The Kingdom fills the 36 Lessons. It is encapsulated entirely by the Lessons. If you read and understand the 36 Lessons, you will therefore understand the Kingdom, the lands controlled by the Ruling King.</p></div>
<div data-ident="10-008" class="commenthidden" ><p>The Eye reads the Eyelid from behind and within, as the Prisoner observes the Tower in which he is imprisoned. However, once the Eye has read the Eyelid it no longer has any need for it, and the Eyelid draws back to allow the Eye to read the entire world.</p><p>This speaks to another philosophy, not just one of the student surpassing the teacher, but also of the limitations of the 36 Lessons. While the 36 Lessons might encapsulate the "kingdom," the "eye" is required to "read" the entire world. In other words, the Lessons can help you master Morrowind. But mastery of the entire world requires the Eye.</p><p>On that note, for those of you familiar with the Tower, do you detect a play on words, here? The "I" shall read the world? We'll touch on that again in later lessons.</p></div>
<div data-ident="10-009" class="commenthidden" ><p>Vivec insists that the Hortator (either Nerevar or the Nerevarine) cannot understand the 36 Lessons without hir aid. By extension, the Hortator will not become a Ruling King without following hir teachings. Again, the relationship between Vivec and Nerevar echoes the one between Krishna and Arjuna in the Bhagavad Gita.</p></div>
<div data-ident="10-010" class="commenthidden" ><p>As we've discussed in previous Lessons, the "sword" is a metaphor for the Warrior aspect of ALMSIVI. But it is also a broader metaphor, and I will explain it in great detail later, in Sermon 23.</p></div>
<div data-ident="10-011" class="commenthidden" ><p>There's a lot of ways to go with this, and frankly I don't think any of them are bad.</p><p>For example, consider that it may describe someone's hastily-written name at the bottom of a letter. Signatures of this kind connote a kind of ownership of a document, an agreement to enter into some condition of reliance or responsibility. Impatiently signed signatures are done out of a desire for haste or thoughtlessness, the latter of which seems like a wise thing to warn against.</p><p>Signatures are also the key and tempo notes on a piece of musical notation. An "impatient" signature would be fast-paced tempo, which describes the Sword philosophy well, since it cannot linger in any place for very long.</p></div>
<div data-ident="10-012" class="commenthidden" ><p>Keep the sword away from the past. Owe no fealty to those who have come before. Do not become mired in bargains and deals with forces that have nothing to gain from events in the present.</p><p>Similarly, do not waste your energies destroying that which is already dead. Leave the past in the past. Live in the moment.</p></div>
<div data-ident="10-013" class="commenthidden" ><p>The following section, told to Nerevar by Vivec, supposedly comes from Boethiah herself, or at least we are meant to think that.</p></div>
<div data-ident="10-014" class="commenthidden" ><p>Another obscure nickname for Lorkhan. The symbolism is a little thick, but it starts with another name for Mundus: "The Gray Maybe," so we'll start with that.</p><p>Mundus represents the equal distribution of Anuic and Padomaic forces in the universe; enough creativity to produce a new concept, enough limitation to keep the concept from dissolving into the next creation. These two chiral forces can be assigned colors: black and white. Therefore, the combination of the two produces Mundus, the color gray.</p><p>Lorkhan is called the Frame Maker because he created the "frame" in which the colors of the Aurbis can combine together to produce the tapestry of mortal life.</p></div>
<div data-ident="10-015" class="commenthidden" ><p>In Egyptian mythology, the Scarab is a beetle that pushes the sun across the sky. Ancient Egypt largely employed a heliocentric religious structure, and the sun carried such extensive religious significance that I really shouldn't open that can of worms, not now. For the time being, consider that the Scarab symbol is responsible for moving the Sun across the sky, and by extension it creates the passage of time. Similarly, Lorkhan is responsible for convincing Akatosh to become linear time itself, and to take responsibility for the creation of cause and effect.</p><p>There is also a slightly easier concept at play. The scarab, a beetle, symbolizes the lowest form of life. It feeds on detritus, rolling a ball of dung around in the dust. But Egyptian myth holds it in the highest position of honor in that it is responsible for moving the sun itself.</p><p>And in the world of the Elder Scrolls, the scarab will one day transform into the New Man.</p></div>
<div data-ident="10-016" class="commenthidden" ><p>By "a world," Boethiah means Nirn. But the word "love" carries a slightly different connotation in the 36 Lessons, and if you've read my essay about Love in the Lessons, you might have a better understanding of how Lorkhan might fit into the concept. And in C0DA we see the full plans of Vivec's Love for Lorkhan laid bare.</p></div>
<div data-ident="10-017" class="commenthidden" ><p>A common theme in Velothi philosophy is to treasure the lowest of things: the dirt, the bugs, the detritus, the rejected, and the pitiable. Here, Boethiah encourages the Dunmer to consider their mortality and the dirt on which they stand as a cloak, a garment of value meant to warm and comfort.</p></div>
<div data-ident="10-018" class="commenthidden" ><p>Boethiah describes the punishment of Lorkhan by the et'Ada and the eight Aedra as betrayal. And a foul murder in addition, considering they struck while his back was turned.</p><p>Hmmm. That rings a bell.</p></div>
<div data-ident="10-019" class="commenthidden" ><p>Boethiah is likely speaking of the events that immediately followed the creation of Mundus as described in the book "<a class="external" href="http://www.uesp.net/wiki/Lore:Before_the_Ages_of_Man" target="_blank">Before the Ages of Man</a>." But in general, this is a subtle dig at Magnus and the other Magna-Ge who found Mundus abhorrent and attempted to flee after Convention, with varying degrees of success.</p></div>
<div data-ident="10-020" class="commenthidden" ><p>The nature of those who are always satisfied is that being free from desire they are immune to temptation. Magnus and his opinions mean nothing to them because they have no fear, and no doubt.</p><p>Understated is a good way to describe them. Consider this Chinese saying: "He who speaks, does not know. He who knows, does not speak."</p><p>Who are always satisfied? Do they exist yet on Nirn?</p></div>
<div data-ident="10-021" class="commenthidden" ><p>Those of you who are familiar with the Towers concept as outlined in Kirkbride's "<a class="external" href="http://www.imperial-library.info/content/nu-mantia-intercept" target="_blank">Nu-Mantia Intercept</a>" will probably suspect that this line speaks of the length and breadth of Mundus, supported by Towers, from the beginning to the end of a Kalpa.</p><p>But in the context of the previous sentence, this is almost certainly a description of Lorkhan's mythology. In this case, "a short season of towers" refers to the creation of Mundus and the formation of the eight "gift-limbs" of the Aedra, who can be thought of as similar (or even highly relevant to) the Towers of the Nu-Mantia Intercept.</p></div>
<div data-ident="10-022" class="commenthidden" ><p>The language here is a little bit strange. Running solely from the dictionary definitions, this sounds like it means a kind of mediocre act of forgiveness. "Oh, I guess it's okay..."</p><p>Consider the fate of Lorkhan: put on trial by the Aedra and judged by Magnus. Is it possible that this "rundown absolution" is the judgement itself? "Forgiven" for his sins but still punished by Trinimac?</p></div>
<div data-ident="10-023" class="commenthidden" ><p>And again we have the "eye" that reads the world, as Lorkhan did when he viewed the Wheel sideways, saw the "I," and gained the fire of knowledge.</p></div>
<div data-ident="10-024" class="commenthidden" ><p>Recall Vivec's meditations on the nature of skin in Sermon 8. The Dunmer, who worship Boethiah, are likely the "Trinimac-eaters" in this sentence. When Boethiah tells them to "pitch your voices to the color of bruise" she references their eventual transformation from the golden-skinned Chimer into the dark-skinned Dunmer.</p><p>This entire paragraph is largely an expansion on the ideas suggested by Vivec in previous sermons. Hide your true intentions. Conceal yourself from your enemies. Embrace change, and transform yourselves so that you may better defeat those who wish to stop you.</p></div>
<div data-ident="10-025" class="commenthidden" ><p>Boethiah speaks of the Nords, but also of the Dwemer. Both races had tribe or House-based cultures.</p><p>But Boethiah intends these to be words of warning. She understands that Houses work intrinsically against the well-being of a people. Though they seem like a boon, they are actually a curse. Division causes strife between Houses, and fighting against each other weakens the the children of Veloth so much that they are incapable of defending themselves against Tiber Septim.</p><p>In a broader sense, it seems somewhat in-character if Boethiah might suggest that the broader concept of dependency upon others is also a weakness, but that helping those who cannot help themselves is a holy act.</p></div>
<div data-ident="10-026" class="commenthidden" ><p>This is a reference to the Eight Aedra, but also to the 16 Daedra, each equally integral to the structure of Mundus. As mentioned in previous Sermons, they act as the "laws" that define the structure of the chaotic possibility in the center so that something qualitative can be produced.</p></div>
<div data-ident="10-027" class="commenthidden" ><p>As a House is an organization of people, every member is a component, a brick in a wall.</p></div>
<div data-ident="10-028" class="commenthidden" ><p>This is the twist. Boethiah reminds the Dunmer that her people should appear as divided, as their enemies are, but to not actually divide. Instead, they should stay unified, focused in their ambitions, and feigning weakness until the opportunity to strike is revealed.</p></div>
<div data-ident="10-029" class="commenthidden" ><p>This is the first mention of Sithis, sometimes called the "soul" of Padomay or the "father" of Lorkhan. The blind truth is that no one really has a firm grip on the true nature of Sithis, not even Bethesda, who change their portrayal of Sithis to best serve the needs of each individual writer.</p><p>I mean, I've said it before and I'll say it again, but there is no grand lore document at Bethesda. Certainly not one that contains any great deal of depth. They prefer to keep things vague and undefined because it creates more opportunities for stories than specificity would. And this is by no means a coincidence: it gives the fans more stuff to play with.</p><p>In the 36 Lessons, SITHISIT represents a kind of corruption of brotherhood. It is misanthropia embodied; the distrust of your family and friends and strangers alike. This is the closest the 36 Lessons comes to defining something like an objectively evil force.</p></div>
<div data-ident="10-030" class="commenthidden" ><p>It's an effective way to illustrate the destructive nature of SITHISIT. Quicker than any enemy is are the forces of distrust and discord, and the entire structure can dissolve all for the sake of the smallest part. Vivec warns Nerevar, and by extension the Player: everything can fall apart if there is but one weak link.</p></div>
<div data-ident="10-031" class="commenthidden" ><p>At this point in the Lessons, the Velothi are flushed with their victory over the Nords. They face a strong temptation to relax and begin arguing amongst themselves. These reasons are why SITHISIT is the start of all true Houses. It divides people against each other, weakens a strong structure with subdivision and conflict.</p></div>
<div data-ident="10-032" class="commenthidden" ><p>I think the language here is a little confusing. The Houses, I suspect, are built "against" as in they are built on top of, or with, stasis and lazy slaves.</p><p>Anyway, the larger point here is that these two concepts, stasis and lazy slaves, are intended to be contributing factors to the misanthropia of SITHISIT.</p><p>Stasis, because Houses are built by those who wish to conserve things the way they are. Such a concept is clearly abhorrent to someone as Padomaic as Vivec.</p><p>Lazy Slaves is tricky. Vivec suggests that those who conform to such conservative tendencies are willingly allowing themselves to become enslaved. They are "lazy" because they prefer a life without responsibility and choices, and they are disinclined to seek their own freedom due to the responsibilities that freedom entails.</p><p>Lorkhan, to whom Boethiah speaks, rallied against such structures. His plan to construct Mundus was a complex scheme, drawn against the forces of stasis, intended to create a path of freedom for the slaves of the Aurbic cycle.</p></div>
<div data-ident="10-033" class="commenthidden" ><p>Remember Sermon 4, where Vivec breaks the Chancellor of Exactitude's astrolabe? This act is repeated again in metaphor as Boethiah speaks of "false maps." Just as Vivec destroys the astrolabe to symbolize acceptance of the ephemeral things that cannot be described, Boethiah speaks of breaking preconceived notions and concepts once called "facts" in favor of a formless, indescribable conception of reality.</p><p>"Your reality as visualized is a lie," Boethiah, like Lorkhan, seems to say. "No map can represent the true nature of our existence. Abandon the House of stasis and safety for the responsibility of dangerous and chaotic freedom."</p></div>
<div data-ident="10-034" class="commenthidden" ><p>This reference to the Barons of Move Like This (from Sermon 01) encourages the children of Veloth to practice their martial disciplines while concealed from their enemies. Discipline and self-improvement are, among others, the ways of a Ruling King.</p></div>
<div data-ident="10-035" class="commenthidden" ><p>This entire sentence sounds very strange, but it's both literal and figurative. "False fathers" is a metaphor for a poor or deceptive leader, teacher, or other authority figure. In short: people who would lead you astray. Mothers who weep for "glass and rain" evokes the image of an overly-kind mother, an enabler who quietly wishes for beautiful but fragile things, the melancholic and listless.</p><p>Boethiah would have the Velothi submit themselves to the disciplined taskmaster, to harsh but good-hearted instructors who wish to improve those who serve them.</p></div>
<div data-ident="10-036" class="commenthidden" ><p>A concept or entity that cannot change requires nothing. Its energy is enclosed and static. Nothing further is needed. Similarly, that which cannot change cannot interact or be interacted with, and therefore it is itself nothing.</p></div>
<div data-ident="10-037" class="commenthidden" ><p>Another dig at the Aedra. That they are considered "dead" is a bit of a misnomer, but they are certainly inert in comparison to their Daedric brethren.</p></div>
<div data-ident="10-038" class="commenthidden" ><p>So we switch again to Vivec's teachings, and in the next few lines ze chooses to remind us that SITHISIT is not gone, and not forgotten. This is not an entity that we can choose to ignore. And this fact is so important that Vivec repeatedly tells us to remember it.</p></div>
<div data-ident="10-039" class="commenthidden" ><p>Phosphorescence is light without heat, so I'm fairly certain that the intention here is to evoke an image of a calm lake or body of water. Why? Because of the metaphor of the "drowned lamp," which will come back up a few more times in the 36 Lessons.</p><p>In the Elder Scrolls universe, it's believed that memories become water when a person dies. Whether this is a metaphor or literal actually doesn't matter, as the two are frequently the same thing in the Elder Scrolls universe.</p><p>If a memory becomes forgotten by the rest of the world, it can be said that it has sunk beneath the surface, obscured beneath dark waters, never to be recovered.</p><p>The Drowned Lamp, however, is a memory that refuses to be lost beneath the waves. It's a lamp because it still burns with the light it once had, even if we can no longer feel the heat. A Drowned Lamp is a memory that refuses to die out.</p><p>Why doesn't it die? Any number of reasons. Perhaps because people still speak of that memory in legend or myth. Perhaps a permanent reminder of the memory still remains in the form of a monument or written history. To "join" or "become" a Drowned Lamp is to fade into legend.</p><p>In short, this entire passage is a warning by Vivec that SITHISIT is still a threat, even if it has faded into memory.</p></div>
<div data-ident="10-040" class="commenthidden" ><p>And so Vivec closes out another sermon with a strongly-worded warning to beware the forces of misanthropy that would divide the Velothi and pit them against each other. Remain strong against forces that have faded from the public's current consciousness and remember the threats of the past because they will rise again the moment they detect the slightest weakness.</p></div>
<?php include 'middle.php' ?>
<p>You have discovered the tenth Sermon of Vivec, which was hidden in the words that <span class="lessonlink" data-call="10-001">came in the aftermath</span> to the Hortator.</p>
<p><span class="lessonlink" data-call="10-002">The evoker</span> shall raise his <span class="lessonlink" data-call="10-003">left hand</span> empty and open, to indicate he needs no weapons of his own. <span class="lessonlink" data-call="10-004">The coming forth is always hidden</span>, so the evoker is always invisible or, better, <span class="lessonlink" data-call="10-005">in the skin of his enemies</span>.</p>
<p>'<span class="lessonlink" data-call="10-006">The eyelid of the kingdom</span> shall fill <span class="lessonlink" data-call="10-007">thirty and six folios</span>, but <span class="lessonlink" data-call="10-008">the eye shall read the world</span>.' By this the Hortator <span class="lessonlink" data-call="10-009">needs me to understand</span>.</p>
<p><span class="lessonlink" data-call="10-010">The sword</span> is an <span class="lessonlink" data-call="10-011">impatient signature</span>. <span class="lessonlink" data-call="10-012">Write no contracts on the dead</span>.</p>
<p>Vivec says unto the Hortator <span class="lessonlink" data-call="10-013">remember the words of Boet-hi-ah</span>:</p>
<p>We pledge ourselves to you, the <span class="lessonlink" data-call="10-014">Frame-maker</span>, the <span class="lessonlink" data-call="10-015">Scarab</span>: <span class="lessonlink" data-call="10-016">a world for us to love you in</span>, a <span class="lessonlink" data-call="10-017">cloak of dirt to cherish</span>. <span class="lessonlink" data-call="10-018">Betrayed by your ancestors</span> when you were not even looking. Hoary Magnus and his <span class="lessonlink" data-call="10-019">ventured opinions</span> cannot sway the understated, a trick worthy of the <span class="lessonlink" data-call="10-020">always satisfied</span>. A <span class="lessonlink" data-call="10-021">short season of towers</span>, a <span class="lessonlink" data-call="10-022">rundown absolution</span>, and what is this, what is this but <span class="lessonlink" data-call="10-023">fire under your eyelid</span>?</p>
<p><span class="lessonlink" data-call="10-024">Shift ye in your skin</span>, I say to the Trinimac-eaters. Pitch your voices into the color of bruise. <span class="lessonlink" data-call="10-025">Divide ye like your enemies, in Houses</span>, and <span class="lessonlink" data-call="10-026">lay your laws in set sequence from the center</span>, again like the enemy Corners of the House of Troubles, and see yourself thence as <span class="lessonlink" data-call="10-027">timber, or mud-slats, or sheets of resin</span>. Then <span class="lessonlink" data-call="10-028">do not divide</span>, for yet is the stride of <span class="lessonlink" data-call="10-029">SITHISIT</span> quicker than the rush of enemies, and He will <span class="lessonlink" data-call="10-030">sunder the whole for the sake of a shingle</span>.</p>
<p>For we go different, and in thunder. SITHISIT is the <span class="lessonlink" data-call="10-031">start of all true Houses</span>, built <span class="lessonlink" data-call="10-032">against stasis and lazy slaves</span>. Turn from your predilections, <span class="lessonlink" data-call="10-033">broken like false maps</span>. Move and <span class="lessonlink" data-call="10-034">move like this</span>. Quicken against <span class="lessonlink" data-call="10-035">false fathers</span>, mothers left in corners weeping for glass and rain. <span class="lessonlink" data-call="10-036">Stasis asks merely for nothing</span>, for itself, which is nothing, as you were in the <span class="lessonlink" data-call="10-037">eight everlasting imperfections</span>.</p>
<p>Vivec says unto the Hortator remember the words of Vivec.</p>
<p>UNDERSTAND THAT SITHISIT STILL TRAVELS</p>
<p>Vivec says unto the Hortator remember the words of Vivec.</p>
<p><span class="lessonlink" data-call="10-039">IN A PHOSPHORESCENT MIRROR OF THE SKY</span></p>
<p>Vivec says unto the Hortator remember the words of Vivec.</p>
<p>DROWNED AND SMILING</p>
<p>Vivec says unto the Hortator remember the words of Vivec.</p>
<p>INTERMITTENT HOPES ENOUGH</p>
<p>Vivec says unto the Hortator remember the words of Vivec.</p>
<p>TO ANSWER ALL THE THINGS</p>
<p>Vivec says unto the Hortator remember the words of Vivec.</p>
<p>NOT YET QUERIED</p>
<p><span class="lessonlink" data-call="10-040">The ending of the words is ALMSIVI</span><a href="../css/images/36rages/<?php echo pad($sermon); ?>.png">.</a></p>
<?php include 'footer.php' ?>