<?php
$sermon = '16';
include 'header.php';
?>
<div data-ident="16-000" class="commenthidden"><p>In Sermon 16, we watch Nerevar struggle to comprehend the three lessons of Ruling Kings. His confusion is understandable, but Vivec is not much help. He travels to the first of the two moons and receives a cryptic but highly relevant series of clues into the meaning of his life and all life on Nirn.</p>
<p class="horizline"></p>
<p>In Morrowind, Sermon One grants a bonus to the Axe skill. It is worth 200 Septims and weighs 3 units. A copy can be found in <a class="external" href="http://www.uesp.net/wiki/Morrowind:Adanumuran" target="_blank">Adanumuran</a>, the <a class="external" href="http://www.uesp.net/wiki/Morrowind:Baram_Ancestral_Tomb" target="_blank">Baram Ancestral Tomb</a>, the Imperial Cult Shrine at <a class="external" href="http://www.uesp.net/wiki/Bloodmoon:Fort_Frostmoth" target="_blank">Fort Frostmoth</a>, <a class="external" href="http://www.uesp.net/wiki/Morrowind:Ibar-Dad" target="_blank">Ibar-Dad</a>, and Morvayn Manor in <a class="external" href="http://www.uesp.net/wiki/Morrowind:Ald%27ruhn" target="_blank">Ald'ruhn</a>.</p>
<p>Sermon 29 names this Sermon "The Acceptable Blasphemes." Its number is 12, which references the word "He."</p>
</div>
<div data-ident="16-001" class="commenthidden"><p>Though Nerevar has received the three lessons of ruling kings, they are doubtless quite confusing to him. If we interpret the 36 Lessons literally, one of the lessons involves a statement from a devilish opponent who doesn't yet exist, and so it's easy to see how Nerevar is having trouble with them.</p></div>
<div data-ident="16-002" class="commenthidden"><p>Nerevar's concern could be warranted. Part of the danger of learning magic is that a lack of thorough knowledge can be dangerous. Learning to assemble an automobile from scratch might seem complex enough, but one small mistake can be disastrous when it comes to driving the vehicle. A poor execution of Vivec's lessons could result in unintended harm or even death.</p>
<p>Consider the process of attaining the state of CHIM. Those that succeed in reaching this level of perception are capable of nearly anything, existing in a trans-dimensional state in which they are no longer hindered by law or truth. But those that fail are incapable of retaining anything, even their sense of self, and so they vanish in a puff of logic. Therefore a student must be extremely cautious.</p>
<p>This is Nerevar's concern, without question. Vivec is educating him in the talent of CHIM and he is afraid of zero-summing.</p>
<p>You know, it occurs to me that I may not have adequately explained zero-summing yet, so let's do that now.</p>
<p>During the process of attaining the state of CHIM, a mortal must have a metaphorical confrontation with the Godhead. In this moment, the mortal must fully comprehend his non-existence in the Godhead's dream. This is not an intellectual realization (merely being told of the dream-state does not carry the requisite psychic weight) but rather a full comprehension of this reality. It is an acceptance in the same way an old man accepts his impending death, completely unlike the way a young man doesn't. It is at this point that the supplicant is at the greatest risk.</p>
<p>The metaphorical confrontation goes like this:</p>
<ul>
<li>The mortal argues, "I am mortal and alive. I have a soul. I exist."</li>
<li>The Godhead argues, "You are a fragment of my dream, a glimmer of a notion. Like the rest of the universe, you do not exist."</li>
<li>Understanding this, the mortal does the logical thing and ceases to exist. This is to zero-sum.</li>
</ul>
<p>Considered another way, the mortal is the number "1," a positive value: "I am." The Godhead is a negative number, "-1," a negation: "You are not." With the certitude of basic math, the result is zero: 1 + (-1) = 0.</p>
<p>To attain CHIM, a supplicant must obey this inescapable logic and yet somehow still retain his individuality and existence.</p>
<p>A similar experience happens in Buddhism, when a practitioner contemplates the unified nature of reality. Since all things are one, the individual does not exist. Those who become enlightened understand this joyous state and yet still maintain their individuality through mental fortitude, wisdom, and strength of training.</p></div>
<div data-ident="16-003" class="commenthidden"><p>In a simplistic way, this describes Vivec as "a glory," a thing that brings glory to Veloth. But why an <em>image</em> of Veloth?</p>
<p>Honestly, there's no way to fit this explanation in here. You'll have to wait for Sermon 25, I think.</p></div>
<div data-ident="16-004" class="commenthidden"><p>The first place my head goes is to "Beggar So," one of the <a class="external" href="https://en.wikipedia.org/wiki/Ten_Tigers_of_Canton" target="_blank">Ten Tigers of Canton</a>. Beggar So, often called the "King of Beggars," was a famous martial artist in 19th century China who, in legend, is often said to have led a formalized guild of beggars. Eccentric beyond belief, Beggar So was known for his Drunken Style of Kung Fu and being fiercely effective with a walking stick he called his "dog beating staff."</p>
<p>If a similar character is depicted here, I would imagine he and Vivec would be close friends, considering Vivec's fondness for thieves.</p>
<p>Alternatively, this could be a regional king acting like a beggar, which illustrates the value of Vivec's hair as an artifact so beloved that king would come begging for it.</p></div>
<div data-ident="16-005" class="commenthidden"><p>I'm thinking Vivec's hair is a record of hir memory? Or perhaps wisdom that can be applied to a life? But why not youth? Because Vivec was never a child. Alternatively, the map is incomplete because Vivec cannot die, therefore hir hair will not provide the needed data. Either way, it's useful for obvious reasons.</p></div>
<div data-ident="16-006" class="commenthidden"><p>In many religions and philosophies, part of the training to attain some flavor of enlightenment is the reduction of the ego - the sense of self. In order to fully comprehend the true nature of the "universal all," a being must be able to exist in a state where their individuality is non-existent. Many religions therefore practice the act of destroying their sense of self-identity. Shaving one's head is an important step in this process. Aside from the practical effect of making every practitioner appear similar to his fellow practitioners, it also helps someone fight the temptation of vanity.</p>
<p>Vivec does something similar here. Ze removes hir hair as an act of humility and as an attempt to reduce hir sense of unique identity. This is "making room" for the fire's perfect knowledge because this gift of wisdom cannot exist in a soul already burdened by ego. Vivec must prepare an empty container within which the seed of divinity can take root.</p>
<p>This isn't much of a philosophical leap. Similar to its ever-flickering and changing sigil, the state of CHIM is one of chaotic stability, of contradiction. This state of chaos shares many aspects with Oblivion and the principle of void and emptiness. Therefore CHIM can only be obtained by an "empty vessel."</p>
<p>Let's also try approaching things from a more mythical angle. Many heroes in ancient myth who sought power or knowledge ended up sacrificing some part of themselves in order to "pay" for that boon. Odin tore out his own eye to gain cultural wisdom from Mimir. On another occasion, he hung himself from a tree until he comprehended the nature of the written word (a power and wisdom that holds so many parallels with Thu'um that I wonder why the Last Dragonborn wasn't required to sacrifice something to learn his first shout).</p>
<p>In this respect, Vivec's sacrifice of hir hair could be the price that must be paid for the power ze is preparing to receive.</p></div>
<div data-ident="16-007" class="commenthidden"><p>As I mentioned previously, the 36 Lessons does not give Vivec a childhood. Ze goes immediately from hir egg/image form to that of a fully developed God.</p>
<p>A number of Morrowind fans have pointed out that this lack of a childhood is conspicuous, and is just one clue among many that Vivec destroyed hir own childhood and youth as an attempt to forget painful memories. Considering what we know about hir past as a gang leader, skooma dealer, and hooker, this seems like a reasonable assumption.</p>
<p>It may also be another reason why Vivec is not able to achieve the level of divinity to which ze aspires. Forgetting a painful memory is not the same as resolving it. Though your conscious mind may not recall the past, some other part of your being will. Call it your subconscious, inner child, star, soul, even your physical being, all these things remember long after you have forgotten.</p>
<p>Unresolved trauma is the leading cause of difficult psychological conditions. Post Traumatic Stress Disorder, for example, is often found in victims who have not yet come to understand and manage the fear and pain of their past.</p></div>
<div data-ident="16-008" class="commenthidden"><p>Vivec, perhaps more than most characters in the Elder Scrolls universe, understands that truth is relative. But hir use of this word here is probably more about honesty, or at least the lack of conscious deception, instead of objective fact.</p></div>
<div data-ident="16-009" class="commenthidden"><p>This is the House of Boethiah, then. The connection between "False" Thinking and Boethiah is a bit complex, and I'm not really sure I can explain it clearly, but you must think of it from Vivec's point of view.</p>
<p>On the surface level, the connection is easy. Boethiah is the Daedric Prince of Deceit, among her other titles. As such, deception is high on her list of weapons.</p>
<p>To Vivec, all of reality is a lie. Which, in fact, it is: the Aurbis is the Godhead's dream that lies to its inhabitants by resembling reality. To Vivec, then, "truth" is relative to the reality that is presented to us, which is therefore a lie. If something is true, it aligns with what we perceive to be true. But if what we perceive is intrinsically false, the only truth can therefore be what is not true.</p>
<p>Hence, false thinking. By contemplating what must be untrue, we see past the Godhead's lie and into the true nature of reality. There's a strong connection, I think, to the Zen concept of "no-thought," which is thinking that does not rely on the four possible combinations of Yes (or "True") and No (or "False"):</p>
<ol>
<li>Something is True.</li>
<li>Something is False.</li>
<li>Something is both True and False.</li>
<li>Something is neither True nor False.</li>
</ol>
<p>To continue this train of thought, let's consider the relationship between Boethiah and CHIM. If the true nature of reality is a lie (or, at best, a distortion of the truth), then Vivec must contemplate this falsehood in order to perceive the truth, which is a step in achieving a state in which reality can be comprehended.</p>
<p>Only by thinking beyond the realm of what is True and False can the actual nature of the universe be comprehended - it is a point beyond the various combinations of chiral concepts.</p>
<p>But you already knew this. What else could the Godhead's dream be except yet another Enantiomorph?</p></div>
<div data-ident="16-010" class="commenthidden"><p>Water, being an Anuic force, is associated with will, and the sense of need that can act on the possibility of a Padomaic force, like water creates crops in seeded ground. Since it is Anuic it is, at higher gradients, incapable of deception. It lacks the required creativity.</p>
<p>You're wondering whether or not Vivec's face is actually covered by some watery mask? I mean… Of course it is. Why not?</p></div>
<div data-ident="16-011" class="commenthidden"><p>I like the idea that Vivec is aware of hir own self-deception, or unconscious lies.</p>
<p>A recent discovery in neuroscience is that the human brain creates its perception of reality dynamically based on memory, emotion, and immediate stimuli. But all three of these sources can be flawed - they can be lies. Our memories are changed almost immediately as we make them by our emotions and our previous memories. Threatening strangers are taller in memory than reality. Dialog is mis-remembered. Seconds stretch into minutes, hours distort into moments. Ask any law enforcement officer and they'll tell you that a witness's memory is the most unreliable form of evidence.</p>
<p>So perhaps Vivec's own "secrets" are not a voluntary form of self-deception. Perhaps becoming a God required hir to cover up hir memories and past. Maybe the removal of hir past was not a cold and calculated act of revision but rather a necessary or even regrettable side-effect. It's not completely unreasonable to say that a true God must not be "born" as a mortal. So maybe Vivec is concerned with the aspects of hir personality that persist even though hir past has been erased. And since the ascension to an enlightened state requires a frank and honest quality of self-awareness, ze is using the Water Face for the purpose of self-examination - to see beyond hir own ego and into hir true nature.</p>
<p>In that respect, perhaps the "Water" aspect of the Water Face allows Vivec to form a stronger connection with hir memories, as memory and water are one and the same on Nirn. It's possible that the Water Face's allows help Vivec see beyond hir own secrets by allowing hir to remember hir past with perfect clarity. But better than Eidetic memory, this technique may allow recall that is free of emotion.</p>
<p class="horizline"></p>
<p>We might ask a neuroscientist how we can believe anything if our memories and perception are so deeply flawed, and the answer is that we can't. The concept of an "objective truth" has been disproven by science a long time ago. The only thing we can say with any certainty is that one thing or another will tend to happen according to frequently observed phenomena.</p>
<p>This is another scientific reality that the Elder Scrolls lore community embraces. Without the existence of absolute truth, nothing can be true. Therefore no event in Elder Scrolls lore can be considered "true" or "canon."</p></div>
<div data-ident="16-012" class="commenthidden"><p>This is where we explain what this phrase means. We'll do it here, because it's easiest to illustrate one thing by showing someone else doing it incorrectly.</p>
<p>Do we mean "heaven" as a state of existence? Divinity? Or literally Aetherius? Or a mortal state of perfection and wisdom?</p>
<p>We sure don't mean the moon. But that's where Nerevar goes. Good job, sidekick.</p>
<p>Vivec was hoping Nerevar would realize that "heaven" is a state of being, a condition of mental and spiritual acuity with which one can become a Ruling King. If this sounds similar to CHIM, you might be on to something.</p>
<p>In fact, I'd say it's highly likely that Vivec feels that a Ruling King must be able to attain CHIM. And ze may be right.</p>
<p>But if that's the case, is it cause to re-think what the Ruling King rules?</p></div>
<div data-ident="16-013" class="commenthidden"><p>Aleister Crowley occasionally suggested that Love, by his definition, can sometimes seem like violence, or hate. We've all seen what can happen when opposite personalities clash - an extrovert bullying an introvert through sheer force of personality, or an introvert frustrating an extrovert by refusing to communicate.</p>
<p>If that's a bit difficult to work with, consider the Enantiomorph. This miraculous event can only happen when two complete opposites are combined into one single concept. The forces of Order and Chaos, for example, hate each other with a passion unfettered. So getting the two anywhere near each other is bound to be violent.</p>
<p class="horizline"></p>
<p>So what does "Reach heaven by violence" mean, in the 36 Lessons? Vivec is telling Nerevar that if he can't become a Ruling King via CHIM, if he can't remember or understand the three lessons to Ruling Kings, he should seek power in an enantiomorph, like Vivec did with ALMSIVI. Vivec has learned that the Enantiomorph is a less than ideal (in hir opinion), but no less effective, Walking Way.</p>
<p>I would argue that there's a very obvious event that the Nerevarine could perform: the defeat of Dagoth Ur. The conflict between the two characters is a clear act of violence between chiral pairs, and Vivec's advice for Nerevar (more so,  to the Nerevarine) is to become a Ruling King by destroying the Nerevarine's equivalent - Dagoth Ur.</p>
<p>Therefore, in my opinion, "Reach Heaven by Violence," in the context of the 36 Lessons as they relate to the Nerevarine, means "Kill your one true enemy."</p></div>
<div data-ident="16-014" class="commenthidden"><p>Possibly this means Nerevar enchanted his axe, but many famous weapons in other genres receive names. Or maybe he cast an enchantment on it.</p>
<p>Still, it seems odd that we've never seen this weapon in an Elder Scrolls game. I'd think Nerevar's weapon would be a pretty powerful artifact, even if he did own more than one.</p></div>
<div data-ident="16-015" class="commenthidden"><p>Current thinking is that this is Masser, since Secunda, by its very name, indicates a secondary nature. But of course both moons could have their own Parliament, or one Parliament that moves between them.</p></div>
<div data-ident="16-016" class="commenthidden"><p>Yes, this is sentient landscape. They resent the presence of Nerevar for the same reason that a country's ruling party finds the presence of a foreign king unpleasant.</p></div>
<div data-ident="16-017" class="commenthidden"><p>Both of these are symbols of authority and/or royalty. The Crown represents the right to rule, which is why it is awarded to a King. The Scepter represents military might, which is why it is often awarded to the King's General (when it isn't also granted to the King).</p>
<p>So the parliament of craters does not recognize mortal authority of any kind - granted neither by royalty nor might. The moon is "above" such things, if you pardon the pun. But as a heavenly body, this makes quite a bit of sense.</p>
<p>I tried to get a connection with this and the Wand and Cups suits from the Tarot, but I couldn't find anything that I thought was convincing.</p></div>
<div data-ident="16-018" class="commenthidden"><p>So it's clear, in context, that each of these three symbols should correlate to a country, race, or area of Tamriel. Which ones are they, do you think?</p>
<p>I think it's safe to assume that the moons do not care much at all about politics and warfare. I'd actually suggest that the Parliament of Craters is primarily concerned with cultures and religions, since they govern the remains of Lorkhan. And if that's the case, and they are perceiving three organizations, they probably perceive Elves, the Ehlnofey, and Men, the Wandering Ehlnofey. These are the two most diametrically opposed cultures on the planet. The only third option must be the Dwemer. But which is which?</p>
<p>"Mathematician" is the Dwemer, for obvious reasons. A religion and culture based entirely on cold hard logic. But Lion and Serpent are kind of a toss-up, mostly over the somewhat confused symbolism of the Serpent.</p>
<p>If you don't dig too deep, you might think the "Serpent" was the Mer, influenced no doubt by the very well-known statue in Skyrim of Talos slaying a serpent that supposedly represents the Mer as enemies of Man. Naturally, the many variations of this statue's interpretation cast this into doubt.</p>
<p>But I think the Serpent is Man due to the multiple culture-spanning depictions of Lorkhan as a Serpent, most clearly as the Redguard god Sep.</p>
<p>The Lion must therefore be Mer, and this is a difficult conclusion to reach. You can associated the "golden" and "royal" nature of the Altmer with a Lion, but that connection might seem a little weak until you consider the line from Sermon Six ("The sun shall be eaten by Lions") within the context of C0DA, where we learn that the Altmeri Dominion and the Thalmor join forces with the Brass God remnant of the Dwemer to destroy Nirn and all of Man with it.</p>
<p>So maybe you're still not convinced? Let's try again, but with an even broader conception of this animal symbolism. The mythical depiction of the Serpent is often (at least in many Western and Christian cultures) one of deceit, chaos, and misanthropy: the forces of Evil. The Lion, on the other hand, represents the opposite - royalty, leadership, order: the forces of Good.</p>
<p>So perhaps the Lion and the Serpent do not represent sets of races or cultures but two sides of a single fundamental division. For example, the Ehlnofey and the Wandering Ehlnofey. Depending on your perspective, any race or culture could fit any of these two Padomaic or Anuic forces.</p></div>
<div data-ident="16-019" class="commenthidden"><p>In the context of this speech, the Parliament of Craters are expressing their superiority to Nerevar as the remains of those who, unsatisfied, left their homes and lands of comfort and formed their own destinies. This is the essence of their message to the Velothi hero. They seek neither Queens nor Thrones because they require no leadership - they live by their own Will.</p>
<p>You don't have to literally interpret much of what the Parliament says, but you can. They may not be the literal graves of migrants, but if they were, they might be the remnants of some of the original Wandering Ehlnofey who left Tamriel altogether for other planes of existence.</p></div>
<div data-ident="16-020" class="commenthidden"><p>Again, the root of the Parliament's argument is that Nerevar does not act on his own inspiration, but rather on the orders or tutelage of others such as Vivec. They are suggesting that Nerevar, like Magnus (who is also decidedly solar) and the other Et'Ada, is incapable of leading by his own path, as Lorkhan did. Nerevar has stolen his ideas. He has not generated his own.</p></div>
<div data-ident="16-021" class="commenthidden"><p>The Craters are not sad, nor do they mourn, because their "revolution", or more accurately Lorkhan's revolution, went according to plan. Lorkhan's inspiration was to create Mundus, and invent the dimension within which possibility could occur. That Lorkhan was "destroyed" afterwards is either irrelevant or a lie.</p></div>
<div data-ident="16-022" class="commenthidden"><p>Another Book of the Law quote, from Chapter 2, line 49. It's always nice when I find these. It feels like there's less research work to be done. That's an illusion, of course, because now I get to explain what Crowley meant by this line, and then how it fits into the 36 Lessons narrative. But from a researching perspective, it's like a fast hit of instant gratification.</p>
<p>Nerevar says this, however, as an assertion that he does not intend to suffer at the hands of another. Nerevar believes that he is a leader, not a slave. And if he was a slave, he will not die in slavery. The Parliament of Craters, however, argues otherwise.</p></div>
<div data-ident="16-023" class="commenthidden"><p>Again, the Craters reiterate their message, as though they, like Vivec, intend to teach Nerevar their most important lesson. To borrow ideas, they say, is not the same as creating those ideas, and creation is the only act that truly matters.</p></div>
<div data-ident="16-024" class="commenthidden"><p>The common thread between the admonition of the Parliament of Craters and hero myths is that the Hero of mythology only achieves divinity when he acts without the support of others. Though these myths nearly always begin with the hero learning from those wiser than he, those heroes that become greater than their own destiny frequently do so with a self-originating act. This act is what the Parliament mean when they speak of the "creative impulse," and is a central part of the teachings of Thelema and other Eastern and Eastern-inspired philosophies. A God does not operate within the boundaries of mortal restriction.</p></div>
<div data-ident="16-025" class="commenthidden"><p>I'm not sure if it's possible for Nerevar to escape his destiny. I'm sure that's a big part of why he and his reincarnations never truly become divine. I think it could be argued that Vivec came close, but I don't think any mortal in the history of the Elder Scrolls truly becomes an actual God until the Amaranth escapes the destiny of all Mundus, which is to say the Amaranth moves beyond death.</p></div>
<div data-ident="16-026" class="commenthidden"><p>What is the difference between a grave and a coffin? A coffin contains a corpse of a being, a grave records the existence of that being. A grave might not contain a coffin, but unlike a coffin it does not lose its purpose.</p></div>
<div data-ident="16-027" class="commenthidden"><p>Nerevar is acting foolishly. He's created more graves but he hasn't actually killed anything to put in them. If you think about it that way, you could say that all Nerevar is doing is flailing about without creating anything. And the Parliament's message heavily emphasizes true creation. Even if you create ghosts by destroying your enemies, at least you've created something. But without acting according to his own creative impulse, by following the orders of his teacher, Nerevar cannot create.</p></div>
<div data-ident="16-028" class="commenthidden"><p>Nerevar's "claim" is that he is not of the slaves that perish. But the Parliament of Craters argues that he only bases that claim on the events of his past which, since they were only performed according to his destiny, are frail and matter little. He has only done what is expected of him, tasks that were prepared by others for him to complete, as though he has ticked off goals on a quest log. These little events mean nothing.</p></div>
<div data-ident="16-029" class="commenthidden"><p>Though he may become a king, Nerevar will still continue to be "judged" by the earth, which is to say that he will always be mortal - from the earth, of the earth, judged by the earth. His throne will still be that of "wonder why." He will never have the answer that truly matters. "Why did I do all this?" he might ask himself. "What was the point?" These questions will always be asked by every mortal for eternity until the answer is provided by the only mortal who can escape his mortal destiny.</p></div>
<div data-ident="16-030" class="commenthidden"><p>In Sermon 16, we watch Nerevar struggle to comprehend the three lessons of Ruling Kings. His confusion is understandable, but Vivec is not much help. He travels to the first of the two moons and receives a cryptic but highly relevant series of clues into the meaning of his life and the future of all life on Nirn.</p>
<p>I have to admit, the more I learn about metaphysics and hermetic philosophy, the more I sympathize with Vivec's reluctance to speak with plain language. The issue at play here is the difference between basic comprehension and true understanding. In the same way that a mortal on Nirn can learn of the Godhead and its dream and yet not zero-sum, Nerevar could comprehend Vivec's lessons for Ruling Kings.</p>
<p>But in order for Nerevar to truly understand Vivec's teachings, for him to obtain the fire of perfect knowledge, he must feel the change of that fire in the very core of his being. This requires more than just a mild paradigm shift, but an actual conversion of the process of logical thought.</p>
<p>To use a real-world example, consider the way Zen Buddhism encourages and cultivates an alternative way of thinking, or perhaps a complete lack of thought. Without changing the practitioner in the most fundamental ways, enlightenment cannot be realized.</p>
<p>This is the reason why such strange language is sometimes used - the mental gymnastics required to comprehend these words prepare the mind for the potentially alien and difficult philosophies these words contain. Simply having them explained to you is like watching the end of a movie first. It might make some sense, but it's certainly not as emotionally engaging as it should be.</p></div>
<?php include 'middle.php' ?>
<p>The Hortator wandered through the Mourning Hold, wrestling with <span class="lessonlink" data-call="16-001">the lessons he had learned</span>. They were slippery in his mind. He could not always keep the words straight and knew that <span class="lessonlink" data-call="16-002">this was a danger</span>. He wandered to find Vivec, his lord and master, the <span class="lessonlink" data-call="16-003">glory of the image of Veloth</span>, and found him of all places in the Temple of False Thinking. There, clockwork shears were taking off Vivec's hair. A <span class="lessonlink" data-call="16-004">beggar king</span> had brought his loom and was making of the hair an <span class="lessonlink" data-call="16-005">incomplete map of adulthood and death</span>.</p>
<p>Nerevar said, 'Why are you doing this, milord?'</p>
<p>Vivec said, '<span class="lessonlink" data-call="16-006">To make room for the fire</span>.'</p>
<p>And the Hortator could see that Vivec was out of sorts, though not because of the impending new power to come. The golden warrior-poet had been exercising his Water Face as well, learned from the dreughs <span class="lessonlink" data-call="16-007">before he was born</span>.</p>
<p>Nerevar said, 'Is this to keep you from the fire?'</p>
<p>Vivec said, 'It is so that I may <span class="lessonlink" data-call="16-008">see with truth</span>. It, and my place here at the altar of Padhome in the <span class="lessonlink" data-call="16-009">house of False Thinking</span>, serve so that I may <span class="lessonlink" data-call="16-011">see beyond my own secrets</span>. The <span class="lessonlink" data-call="16-010">Water Face</span> cannot lie. It comes from the ocean, which is too busy to think, much less lie. Moving water resembles truth by its trembling.'</p>
<p>Nerevar said, 'I am afraid to become slipshod in my thinking.'</p>
<p>Vivec said, '<span class="lessonlink" data-call="16-012">Reach heaven</span> by <span class="lessonlink" data-call="16-013">violence</span> then.'</p>
<p>So to quiet his mind the Hortator chose from the Fight Racks an axe. <span class="lessonlink" data-call="16-014">He named it</span> and moved on to <span class="lessonlink" data-call="16-015">the first moon</span>.</p>
<p>There, Nerevar was greeted by the <span class="lessonlink" data-call="16-016">Parliament of Craters</span>, who knew him by title and resented his presence, for he was to be a ruling king of earth and this was the lunar realm. They shifted around him in a pattern of entrapment.</p>
<p>'<span class="lessonlink" data-call="16-017">The moon does not recognize crowns or scepters</span>,' they said, 'nor the representatives of kingdoms below, <span class="lessonlink" data-call="16-018">lion or serpent or mathematician</span>. <span class="lessonlink" data-call="16-019">We are the graves</span> of those that have migrated and become ancient countries. We seek no Queens or thrones. Your appearance is decidedly solar, which is to say a <span class="lessonlink" data-call="16-020">library of stolen ideas</span>. We are <span class="lessonlink" data-call="16-021">neither tear nor sorrow</span>. Our revolution succeeded in the manner that is was written. You are the Hortator and unwelcome here.'</p>
<p>And so Nerevar carved at the grave ghosts until he was out of breath and their Parliament could make no new laws.</p>
<p>He said, '<span class="lessonlink" data-call="16-022">I am not of the slaves that perish</span>.'</p>
<p>Of the members of Parliament only a few survived the Hortator's attack.</p>
<p>A surviving Crater said, '<span class="lessonlink" data-call="16-023">Appropriation is nothing new</span>. Everything happens of itself. This motif is by no means unassociated with <span class="lessonlink" data-call="16-024">hero myths</span>. You have not acted with the creative impulse; you <span class="lessonlink" data-call="16-025">fall below the weight of destiny</span>. We are graves but not coffins. <span class="lessonlink" data-call="16-026">Know the difference</span>. You have only dug more and <span class="lessonlink" data-call="16-027">supplied no ghosts</span> to reside within. Central to your claim is the predominance of <span class="lessonlink" data-call="16-028">frail events</span>. To be judged by the earth is to sit on a <span class="lessonlink" data-call="16-029">throne of wonder why</span>. Damage us more and you will find naught but the absence of our dead.'</p>
<p><span class="lessonlink" data-call="16-030">The ending of the words is ALMSIVI</span>.<a href="../css/images/36rages/<?php echo pad($sermon); ?>.png">.</a></p>
<?php include 'footer.php' ?>