<?php
$sermon = '17';
include 'header.php';
?>
<div data-ident="17-000" class="commenthidden"><p>Sermon 17 of the 36 Lessons of Vivec picks up where Sermon 16 left off, with Nerevar fighting his way through the heavens. Vivec takes his student on a tour through Tamriel, where the two learn many foreign fighting styles. But at the end of the Sermon, Nerevar witnesses Vivec undergo a dramatic and mysterious evolution.</p><p class="horizline"></p>
<p>In Morrowind, Sermon 17 grants a bonus to the Long Blade skill. It is worth 200 Septims and weighs 3 units. Copies can be found in the Sarethi Guard Quarters in <a href="http://www.uesp.net/wiki/Morrowind:Ald%27ruhn">Ald'ruhn</a>, the shrine in <a href="http://www.uesp.net/wiki/Morrowind:Ularradallaku">Ularradallaku</a>, and in the Secret Library in the Hall of Justice at <a href="http://www.uesp.net/wiki/Morrowind:Vivec_(city)">Vivec</a>.</p>
<p>Sermon 29 names this Sermon "The Captive Sage". Its number is 217, which references the word "chose".</p>
</div>
<div data-ident="17-001" class="commenthidden"><p>The origin of this phrase is actually found in the explanation of the origin for the legendary land of Lyg, a continent referenced (when at all) in Elder Scrolls lore as the "coffee stain of Tamriel." Most of what we know specifically about Lyg comes from careful examination of the <a href="http://www.uesp.net/wiki/Lore:Mythic_Dawn_Commentaries">Mythic Dawn Commentaries</a>, but as with many things that hide in the corners of Elder Scrolls, Lyg is a sly reference to a real-world event. Kirkbride explained the origin of Lyg and its name in a forum post as he described a meeting between himself, Kurt Kuhlmann, and "Uncle" Ken Rolston, no doubt called together to do some world-building during Morrowind or Redguard's pre-production phase.</p>
<blockquote><p>One day, in a very special room in a very special office, kings were looking at a map of Tamriel. They were new kings and old kings and some of them only wanted money as kings. So they traced a path along this map to document how things may have happened and how they might not have happened yet. But there was only one map so they passed it back and forth. The newest king drank lots of coffee and needed lots of it to see how exactly all of these ideas could fit, no matter how small no matter how money. His elder brother king had actually been hired a month before the newest but started 8 days later than his younger, impatient sibling. And there was a mighty king who had been there three months in a private office and when we knew his name to be True we bowed our heads and called him Uncle. We acknowledged that all kings were not rulers but equal and therefore bonds of kingship. But sooooo many ideas allll at once! Whoops the map tore into quarters and the coffee spilt. And the kings did quickly sop up the mess but yet still yet wanted their notes. Oh no. Here was a Queen at the door and she did NOT like this racket. Plus the monkeys were tired. So they threw the map of kings into the trash. They went to their various stations and wrote what they remembered or did not think to write at all. But lo for some reason the alarm bell went off LYGALYGALALYG and shit that means fire so three monkeys grabbed the whole trash basket for no other reason than MAYBE OUR ONLY CHANCE to save the Tamriel they had danced around. One held the basket, the other held an inner door open, a third held an outer door in, but weirdly the sprinklers did still hit the open trash. So they got outside and dumped out the contents of the trash because the basket at least held SOME water and the computers still held SOME notes. One monkey got really wet trying to do the right thing, the second got really mad about the Queen for all the wrong things, and the third just stood there kicking through the trash for real reason. Until: OOOHHH. Look at these map parts all skewed around and drying weirdly and the admixture of stains all un alike looked best from beneath. So then the monkeys that really cared forgot about all else except those line track across that drying and broken and backwards map. And they all nodded and smiled and said yes, that is how we will remember everything everyone in that room ever said. And the alarm then sputtered once last LYG. And that made the monkey-kings laugh nervously and the rolled those maps and said "I am going back in, duck your head under the broken light bulb swinging to and fro in that ONE ROOM that will never be used again because SMOKE.</p><p>"I am an Atlas of Smoke said these pieces of the map and we knew it to be called LYG."</p></div>
<div data-ident="17-002" class="commenthidden"><p>Vivec is becoming less of a being, less a powerful demi-god and more a concept, like a true God, and so ze becomes as incomprehensible as a true God, taking many shapes.</p></div>
<div data-ident="17-003" class="commenthidden"><p>As mentioned in the previous Sermon, a "library of stolen ideas" is a solar concept. These are records of the efforts and creations of others, and as such they possess no value of their own.</p></div>
<div data-ident="17-004" class="commenthidden"><p>Deshaan is a zone in ESO, interestingly. Uninterestingly, I don't know much about it, at least not yet.</p></div>
<div data-ident="17-005" class="commenthidden"><p>Vivec's student may realize that a mistake has been made, but it is uncertain if he has yet to learn from it. In later Sermons, however, we'll see Nerevar demonstrate a considerable growth in knowledge.</p></div>
<div data-ident="17-006" class="commenthidden"><p>This is Akavir, a land which we know surprisingly little about, considering how often it is referenced in Elder Scrolls games. It seems to be a safe bet that very few of what we would consider "Men" or "Mer" live in Akavir, and that it is instead occupied dominantly by beast-like races.</p>
<p>Since this is clearly Akavir, one could assume that (depending on the size of the Akavir landmass) that the site of Red Mountain could be the centerpoint of the known lands of Nirn. If you've been paying attention so far, you might anticipate how powerful a position this could be, that Red Mountain could be the literal "heart" of Nirn. Maybe this might also illustrate how the Heart of Lorkhan, and Lorkhan itself, is a critical mystical feature of Mundus, the mortal realm.</p></div>
<div data-ident="17-007" class="commenthidden"><p>Notice the joining of these two seemingly disparate concepts: speech and warfare. In fact, they both meet each other at an intersection labeled "culture." This is just one of the many places where the Word and the Sword are one - they are both products, or perhaps children, of the culture to which they are associated, and it should come as no surprise that Vivec, who exists as the joining place of the Word and the Sword (Sotha Sil and Almalexia, the Mage and the Warrior), easily combines the two.</p></div>
<div data-ident="17-008" class="commenthidden"><p>Here we have a verbal-martial technique. The specifics of the Idiom Stroke are not entirely clear. In fact, the only thing I can definitely say about it is that I keep mis-typing it as "Idiom Stork," and maybe it's very late at night but that's incredibly amusing to me right now.</p></div>
<div data-ident="17-009" class="commenthidden"><p>The <a href="https://en.wikipedia.org/wiki/The_Pillow_Book">Pillow Book</a> of Sei Shonagon might be considered a diary if it wasn't so historically important. The fact that this famous book is considered so socially important links it to the Tsaesci King's pillow book in the respect that Vivec and Nerevar were effectively stealing a closely-guarded cultural secret (a fighting style, as mentioned in a previous comment) from the snake people of Akavir, a culture that is represented here by the King's diary. Probably it was filled by the Tsaesci King with entries wishing Cobra-Sempai would notice him.</p>
<p>It's often theorized by TES Lore nerds that a race's culture is the only thing that actually differentiates one race from another. In a world like Nirn, where the landscape is created by the very myths and legends that describe it, a cultural difference can be reflected by (among other things) a race's appearance. The Dunmer's cultural drift from the Altmer is represented by their dark skin and red eyes. The Nords and the Cyrods are differentiated by height, skin and hair. Men and Mer in general are about as physically different as they can get.</p>
<p>At any rate, there is therefore very little that a race can consider sacred or unique to themselves other than their culture in all its forms. For this and many other reasons, early in Morrowind's conception, Kurt and Kirkbride suggested that players should choose from cultures instead of races.</p></div>
<div data-ident="17-010" class="commenthidden"><p>At the very least, you should be able to guess that it is curved.</p></div>
<div data-ident="17-011" class="commenthidden"><p>I'm not sure if it's possible to actually count how many times the species of Akavir have invaded or troubled Tamriel. It seems like every game includes another rumor or more conjecture. And that's assuming that Akavir even exists, which is a matter of some debate in the Lore community. We'll talk about why that might be in a moment.</p></div>
<div data-ident="17-012" class="commenthidden"><p>The Imperial Library suggests this part of the Lesson is a reference to <a href="http://www.imperial-library.info/content/thirty-six-lessons-vivec-sermon-seventeen">a map bug in Redguard</a>, and I suspect they're correct. But that Nerevar describes them as "swords" is not entirely erroneous, since the Sword is a symbol of limitation, and these swords lie at the edge of the world. But we'll talk more about that in Sermon 23.</p></div>
<div data-ident="17-013" class="commenthidden"><p>If it seems at all strange to you that Nerevar and Vivec would be able to find an "edge" to Nirn… I don't know what to say. Probably you haven't been paying attention up to this point?</p>
<p>But let's think about this from a more symbolic perspective, as it's probably intended. Let's not hit on anything huge yet, but remember that Vivec is showing Nerevar the limits of the world, the edges of reality. That'll become vitally important later in this Sermon.</p></div>
<div data-ident="17-014" class="commenthidden"><p>This spirit, in a way, represents the theme of this Sermon. It gifts Nerevar and Vivec with the spoke of a wheel, as you would find on a wagon wheel.</p></div>
<div data-ident="17-015" class="commenthidden"><p>Mundus has a mind. We know this from the Loveletter which calls the lowest state of existence beyond death to be the "state gradient echo of mundus centerex."</p>
<p>It has teeth, as we can see in this Sermon.</p>
<p>It has five corners, the limbs of a body, like DaVinci's drawing.</p>
<p>It has a throat, as we can see in Skyrim.</p>
<p>Therefore the world is a giant corpse, the gaping head of an organism that has only one purpose, and that will be discussed in Sermon 21.</p></div>
<div data-ident="17-016" class="commenthidden"><p>This is <a href="http://www.uesp.net/wiki/Lore:Atmora">Atmora</a>, the frozen land that lies to the North of Tamriel. There's actually quite a lot to talk about when it comes to Atmora, but thankfully not much of it is directly relevant to the 36 Lessons, so I'll just hit on something that I find entertaining.</p>
<p>Atmora was once supposedly connected to the main Tamriel continent but separated early in the realm's existence, while its mythical landscape (by which I mean landscape generated by myth) was still solidifying. Considered alongside the legend of the Wandering Ehlnofey as the origin of the Mannish races, it's possible that this separation could be the mythical interpretation of the original split between the races. Alternatively (and far more likely, considering the "style" of Elder Scrolls mythology), the separation of Atmora was caused by the cultural split within the Ehlnofey.</p></div>
<div data-ident="17-017" class="commenthidden"><p>One of the theories people in the community have about Mundus is that movement away from Tamriel, the "center" of the mortal realm, affects the flow of time. The general idea is that moving West from Tamriel moves you into the past, while moving East moves you into the future. This means that land masses like Yokuda, which is far to the West of Tamriel, actually resides in the past. And Akavir, which lies to the East, resides permanently in the future. Therefore you can never, for example, reach Akavir because it is always just ahead of you, in the future.</p>
<p>Similarly, moving North slows time down, whereas moving South speeds time up. This means that in Atmora, in the extreme North, time moves so slowly that everything is frozen. Hence "frozen bearded kings." Aldmeris, to the extreme South, is moving so quickly as to be too hot for occupancy.</p>
<p>This might strike you as completely arbitrary and "crazy for crazy's sake," but it makes quite a lot of sense considering the relationship between Time and Space in Mundus. They are both products of the Aedra, after all. That three dimensional space and linear time exist is entirely due to the efforts of Lorkhan and Akatosh.</p></div>
<div data-ident="17-018" class="commenthidden"><p>This of course would be Yokuda, a series of islands or archipelago where the Redguards, the people of Hammerfell, originated.</p>
<p>Yokuda was, according to legend, destroyed at the end of a war between the Redguards and the Left-Handed Elves (which are rumored in Elder Scrolls Online to be the water-based Maormer). The means of its destruction was, according to legend, the Pankratosword. A sword technique of such monstrous power that it split reality itself, the descriptions of the Pankratosword technique so closely resemble a nuclear fission explosion as to be impossible to ignore. I suspect this may have been inspired by <a href="https://en.wikipedia.org/wiki/Mahabharata">ancient Hindu legends</a> of God-like weapons called Astra, specifically weapons similar to the <a href="https://en.wikipedia.org/wiki/Brahmastra">Brahmastra</a>. The description of this weapon is incredibly reminiscent of modern weapons intended for massive destruction, which is eerie considering the text was written nearly 2,500 years ago:</p>
<blockquote><p>"Gurkha, flying a swift and powerful vimana,<br/>
hurled a single projectile<br/>
charged with the power of the Universe.</p>

<p>An incandescent column of smoke and flame,<br/>
as bright as ten thousand suns,<br/>
rose with all its splendour.</p>

<p>It was an unknown weapon,<br/>
an iron thunderbolt,<br/>
a gigantic messenger of death,<br/>
which reduced to ashes<br/>
the entire race of the Vrishnis and the Andhakas.</p>

<p>The corpses were so burned<br/>
as to be unrecognizable.</p>

<p>Hair and nails fell out;<br/>
Pottery broke without apparent cause,<br/>
and the birds turned white.</p>

<p>...After a few hours<br/>
all foodstuffs were infected…<br/>
...to escape from this fire<br/>
the soldiers threw themselves in streams<br/>
to wash themselves and their equipment."</p>
</blockquote>
</div>
<div data-ident="17-019" class="commenthidden"><p>In their legends, Vivec granted them secret martial art techniques that required their warriors to undergo a physical change of some kind. Even the word "Ansei" means "changed ones." The nature of that change is hinted at by the name the Redguard Ansei masters gave Vivec: the Ansu-Gurleht, he who makes us women.</p>
<p>The Ansei are well known for once being masters of the Shehai, the Spirit Sword, a magical weapon created out of the wielder's spirit. Considering that these masters are called "Saints," you can see how important this technique is in Redguard culture.</p></div>
<div data-ident="17-020" class="commenthidden"><p>The reward is hir penis. Probably, anyway.</p></div>
<div data-ident="17-021" class="commenthidden"><p>There's very little to go on, here. It's possible that Vivec might be taking credit for the creation of the Left-Handed Elves, but I've got nothing outside this sermon to back that up. It does seem like the kind of thing ze'd do, though.</p></div>
<div data-ident="17-022" class="commenthidden"><p>I'm pretty sure this is as close to an apology as you're likely to get from Vivec. But it could also allude to a deeper meaning, since there is a temptation to believe that a dream-like nature might be an asset in a dream-like universe. But while that reasoning is not completely beyond logical, the reality is that the awareness of CHIM requires a clarity completely unlike a dream-state.</p></div>
<div data-ident="17-023" class="commenthidden"><p>As mentioned before, the spacial-temporal nature of Nirn's existence suggests that Aldmeris, the island that Vivec is avoiding consideration, exists in a state where time moves so quickly as to generate a terminal level of thermal heat, thus making existence on its shores impossibly lethal.</p>
<p>Vivec might remain silent on the subject of Aldmeris because it is the origin from which all Mer (including hir ancestors) once originated, according to legend.</p>
<p>But here's another interpretation: What if Aldmeris doesn't actually exist? What if the same could be said for Atmora?</p>
<p>Consider the origin of the Ehlnofey and the Wandering Ehlnofey. Their split, the first event in the everlasting conflict between Mer and Men, could be a metaphor for the difference between geographic origins of the two races.</p>
<p>In a literal sense (well, as literal as the Elder Scrolls get), the Wandering Ehlnofey may have left Aldmeris for Atmora, and then migrated from there to Tamriel. But the Ehlnofey legend could be a myth explaining the intrinsic differences between Men and Mer. It could explain (in a mythical way) the geographic separation between Aldmeris and Atmora. But if Aldmeris doesn't exist, perhaps neither does Atmora, and the legend of the Ehlnofey and the Wandering Ehlnofey is only an alternative myth to explain the history of war between Man and Mer, as is the legends of Atmora and Aldmeris. Both legends illustrate the same concept: They are not like Us - a xenophobic impetus of racial strife on Nirn.</p>
<p>And unfortunately, unlike the real world, the Men and Mer of Nirn are definitely not the same.</p></div>
<div data-ident="17-024" class="commenthidden"><p>This might be a veiled admission that the Sharmat did not technically exist during Nerevar's life. According to some accounts, there was a period of time during which Voryn Dagoth was either dead or insane, but in no account was he ever referred to as Dagoth Ur or the Sharmat.</p></div>
<div data-ident="17-025" class="commenthidden"><p>I mean, we're all familiar with the importance placed on body markings in general in mythology, right? Even if you've never really thought about it, you're probably vaguely familiar with a few stories in which the fate of a hero is "foretold" by a birthmark of a particular shape, or a birth defect of some kind. So this mark might be a clue in the prophecies of the Nerevarine.</p>
<p>And this could also be a mark that depicts a right of passage, as though Nerevar has received Vivec's "stamp of approval."</p></div>
<div data-ident="17-026" class="commenthidden"><p>So that's a total of eight spokes, right? Okay.</p></div>
<div data-ident="17-027" class="commenthidden"><p>It's like Vivec is the character in a LucasArts adventure game, and this is hir default voice response for when you try to combine two or more items before the right point in the plot.</p>
<p>Anyway, Nerevar's attempt to assemble a staff is not entirely without merit - the Staff as a symbol has quite a few connections with the metaphysics of the 36 Lessons. Crowley's Thoth tarot deck equates the Staff symbol with Will and Fire, for example. So maybe Nerevar was on to something, just not the right thing at the right time.</p></div>
<div data-ident="17-028" class="commenthidden"><p>Nerevar is confused because he found them without effort. Does that give you a hint about the nature of the Wheel? He found these spokes during their journey as they explored the limits of the world, so it's easy to guess that the spokes represent the limitations of reality. Or put simply, they represent the concept of limitation.</p></div>
<div data-ident="17-029" class="commenthidden"><p>Like the formation of Mundus, Vivec assumes a wheel with a void in the middle, resembling the Aurbis with Oblivion at its center. As the Aedra lent their eight essences to keep the thought of Mundus from fading, so do the spokes keep Vivec's chaos from living too long. Without doing so, Vivec's chaotic void would dissipate or mutate, or at least change in some drastic and unpredictably unwanted way.</p></div>
<div data-ident="17-030" class="commenthidden"><p>It's a little bit difficult to fully explain how important this Sermon is without basically discussing everything that will be covered in Sermon 21, by which I mean Vivec's Godhood as represented by the Wheel metaphor. So instead I'm going to talk a bit about Nerevar's evolution as the Velothi Champion.</p>
<p>It would be irresponsible of me to discuss Heroes without talking about Jungian archetypes. But since people can get doctorates in Jungian theory, I hope you'll understand if I do so with some trepidation, as I'm woefully undereducated in the subject. So let's start slowly.</p>
<p>Jung proposed, in the earliest days of what we now consider modern psychology, that there were 12 archetypes of personalities. An individual could share aspects with several of these 12, but one would dominate above the rest. Each of these archetypes pulled its aspects from ancient myths - caregivers, rebels, rulers, creators, and so on.</p>
<p>The Hero's main objective was to achieve goals through physical strength and acts of single-minded purpose. They are obsessed with Winning, but they are not as focused on the specifics of what they've won.</p>
<p>Young men and women might identify strongly with the Hero archetype, in part because it is a very youthful caricature. Like a child, the Hero's inability to see the full depth of reality means that it is often reliant on guidance from a wise person who is often the Hero's parents or guardians. In the 36 Lessons, of course, Nerevar receives his guidance from Vivec.</p>
<p>One of the requisite performances of the Hero is the return from battle, something Nerevar has just done by performing the primary aspect of the Hero archetype: Nerevar won his battles against the Heavens. The fact that he did not achieve a goal that he did not fully understand in the first place is irrelevant - the Hero only performs acts, he does not have to comprehend the reason behind those acts.</p>
<p>But this also reveals why the Hero can be a harmful archetype. Nerevar fights with regard only to attaining victory, and a Hero can be directed to do evil because he is so easily manipulated. And because the Hero's journey (in the Joseph Campbell sense) ends with returning and distributing the spoils of victory, the Hero falls short when life continues after the story ends. How can the Hero's idiom cope with post-war conditions? How can the Hero mourn for the dead? Who will deal with the repercussions of violence?</p>
<p>In many respects, the relationship between Nerevar and Vivec outlines the limitations of Campbell's "Hero's Journey" structure when compared with Carl Jung's spiritual exploration. Campbell may have adequately explained the structure of a myth, but Jung explains what must come before and what must happen after.</p></div>
<?php include 'middle.php' ?>
<p>'<span class="lessonlink" data-call="17-001">I am an atlas of smoke</span>.'</p>
<p>With this, Vivec become greater than he had been. These were the days of Resdaynia, when Chimer and Dwemer lived under the wise and benevolent rule of the AMLSIVI and their champion the Hortator.</p>
<p>'<span class="lessonlink" data-call="17-002">Seek me without effort for I take many shapes</span>.'</p>
<p>The Hortator was still trying to subdue the heavens with an axe. He was thrown out of the <span class="lessonlink" data-call="17-003">library of the sun</span> by the power of Magnus. Vivec found him in a grub field outside of the swamps of the <span class="lessonlink" data-call="17-004">Deshaan Plain</span>. They walked for a span in silence, for <span class="lessonlink" data-call="17-005">Nerevar had been humbled</span> and Vivec still had mercy in his hand.</p>
<p>Soon they were walking across the eastern sea to the <span class="lessonlink" data-call="17-006">land of snakes and snow demons</span>. Vivec wanted to show the Hortator the <span class="lessonlink" data-call="17-007">fighting styles of foreign tongues</span>. They learned the <span class="lessonlink" data-call="17-008">idiom stroke</span> from the <span class="lessonlink" data-call="17-009">pillow book</span> of the Tsaesci king. It is shaped <span class="lessonlink" data-call="17-010">like the insight of this page</span>. The Tsaesci serpents vowed to have their vengeance on the west <span class="lessonlink" data-call="17-011">at least three times</span>.</p>
<p>They walked farther and saw the <span class="lessonlink" data-call="17-012">spiked waters</span> at the <span class="lessonlink" data-call="17-013">edge of the map</span>. Here the <span class="lessonlink" data-call="17-014">spirit of limitation</span> gifted them with a spoke and bade them find the rest of the wheel.</p>
<p>The Hortator said, 'The edge of the world is made of swords.'</p>
<p>Vivec corrected him. 'They are the bottom row of the <span class="lessonlink" data-call="17-015">world's teeth</span>.'</p>
<p>They walked to the north to the <span class="lessonlink" data-call="17-016">Elder Wood</span> and found nothing but <span class="lessonlink" data-call="17-017">frozen bearded kings</span>.</p>
<p>They came to the west <span class="lessonlink" data-call="17-018">where the black men dwelt</span>. For a year they studied under their <span class="lessonlink" data-call="17-019">sword saints</span> and then for another Vivec taught them <span class="lessonlink" data-call="17-020">the virtue of the little reward</span>. Vivec chose a king for a wife and made <span class="lessonlink" data-call="17-021">another race of monsters</span> which ended up destroying the west completely. To a warrior chief Vivec said:</p>
<p>'<span class="lessonlink" data-call="17-022">We must not act and speak as if asleep</span>.'</p>
<p>Nerevar wondered if there was anything to learn in the south but <span class="lessonlink" data-call="17-023">Vivec remained silent</span> and only led them back to Red Mountain.</p>
<p>'Here,' Vivec said, 'is the last of the last. Within it the Sharmat waits.'</p>
<p>But they both knew that <span class="lessonlink" data-call="17-024">the time was not ready to contest the Sharmat</span> and so they engaged in combat with each other. Vivec <span class="lessonlink" data-call="17-025">marked the Hortator in this way for all of the Velothi to see</span>. He sealed the wound with the blessing of Ayem-Azura. At the end of the battle, the Hortator <span class="lessonlink" data-call="17-026">found that he had gathered seven more spokes</span>. He attempted to attach them and form a staff but Vivec would not let him, saying, '<span class="lessonlink" data-call="17-027">It is not the time for that</span>.'</p>
<p>Nerevar said, '<span class="lessonlink" data-call="17-028">Where did I find these?</span>'</p>
<p>Vivec said that they had collected them from around the world, though some had come invisibly. 'I am the wheel,' he said, and took that shape. Before the emptiness at the center could live too long, <span class="lessonlink" data-call="17-029">Nerevar put in the spokes</span>.</p>
<p><span class="lessonlink" data-call="17-030">The ending of the words is ALMSIVI</span><a href="../css/images/36rages/<?php echo pad($sermon); ?>.png">.</a></p>
<?php include 'footer.php' ?>