<?php
$sermon = '18';
include 'header.php';
?>
<div data-ident="18-000" class="commenthidden"><p>Sermon 18 of the 36 Lessons of Vivec centers around a conversation between Almalexia and Vivec. Since hir change of state in Sermon 17, Vivec has had to wrestle with some frightening realizations brough on by hir newly expanded consciousness.</p><p class="horizline"></p>
<p>In Morrowind, Sermon 18 grants a bonus to the Alchemy skill. It is worth 200 Septims and weighs 3 units. Copies can be found in the Tower of Dawn at <a class="external" target="_blank" href="http://www.uesp.net/wiki/Morrowind:Ghostgate">Ghostgate</a>, and in Kagrenac's Library in <a class="external" target="_blank" href="http://www.uesp.net/wiki/Morrowind:Tureynulal">Tureynulal</a>.</p>
<p>Sermon 29 names this Sermon "The Egg, or Six Times the Wise". It has no number, for the message correlates to the author.</p></div>
<div data-ident="18-001" class="commenthidden"><p>A "<a class="external" target="_blank" href="https://en.wikipedia.org/wiki/Book_of_hours">book of hours</a>" is a type of Christian prayer book, and should probably be called a "Primer" if you translate the latin term correctly. It's a collection of texts, prayers, and psalms, just like the 36 Lessons. But where the 36 Lessons are meant to be instructions from Vivec to the Hortator, the Book of Hours has a very different goal.</p></div>
<div data-ident="18-002" class="commenthidden"><p>This might be a reference to the ending of the Merethic Era, since the Dwemer do not "vanish" until the 700th year of the First Era. But since the events of the Lessons don't seem to conform naturally to any particular time frame, I wouldn't be too concerned with specifics.</p></div>
<div data-ident="18-003" class="commenthidden"><p>Why does Vivec ask hir "Mother" for guidance? Because Ayem rules over the domain of parameters, of guidelines, of the past, and understands the rules of the universe better than others. Ayem has no doubts, and therefore cannot be blinded by them. Her message is exactly what we should expect from Mercy, because she is concerned with what is True in the events that have passed. Not that Seht would have been much more help - he probably would've answered with a twelve thousand page dissertation on the grammatical structure of second-era Tsaesci dialects. In the binary language of moisture vaporators. Backwards.</p></div>
<div data-ident="18-004" class="commenthidden"><p>These monsters represent Vivec's past mortality. Ze is destroying imperfect or un-Godlike elements of hirself. This wasn't as much a factor before, but since Sermon 17 when Vivec attained the shape of the Wheel, "true" perfection is within hir grasp. As is the nature with spiritual evolution, the Vivec before might not have been able to even comprehend this goal, much less plan to reach it.</p></div>
<div data-ident="18-005" class="commenthidden"><p>The Book of Hours are intended to "destroy" Vivec, but because of Vivec's relationship with the concepts of murder and violence, the nature of that destruction is complex to say the least.</p>
<p>So when Ayem says that Vivec will be destroyed by the Book of Hours, perhaps she means that Vivec will achieve the Godhood ze desires by writing hirself there. After all, Vivec does not destroy so much as ze changes. Ze performs destruction as in deconstruction, not obliteration. So the Book of Hours will change Vivec hirself.</p>
<p>Alternatively, and this might be an easier concept to understand, maybe Ayem is alluding to the eventual destruction of ALMSIVI by the intended audience of the Lessons: The Nerevarine.</p>
<p>But I suspect that the Book of Hours might perform both of those tasks, and one more - it will "destroy" Vivec by telling the truth.</p>
<p>Later, in Sermon 31, Vivec will write in hir Book of Hours while wearing hir Water Face, because it is Vivec's intention that the Book of Hours should be filled with only the truth, whatever that might mean. I'll discuss the implications of this in Sermon 31, but for the moment it's safe to say that the content of the Book of Hours will definitely "murder" Vivec.</p></div>
<div data-ident="18-006" class="commenthidden"><p>It might seem unusual for a God to doubt, but Vivec's nature as the delta between Mystery and Mercy requires hir to entertain disparate concepts. To doubt, one must first be able to comprehend a perspective from outside themselves, and Vivec's Sister/Mother and Brother/Father do not have that luxury, metaphysically speaking. Because they represent the polar opposite of each other, they are extremes, and therefore cannot understand each other. But Vivec was born to do this.</p></div>
<div data-ident="18-007" class="commenthidden"><p>This is ALMSIVI, if you haven't been keeping up.</p></div>
<div data-ident="18-008" class="commenthidden"><p>One of the lessons in Sermon 11 is that nothing stays the same. There will always be a New Thing that the world will deem more beautiful than its predecessor and there is no way to fight against this tendency.</p>
<p>It might be possible to argue that the difference between the divinity of ALMSIVI and that of other more traditional Gods (like the Aedra &amp; Daedra) is that traditional Gods are not subject to any mortal event, good or bad. Or at least that they will never be eliminated. And maybe that's not what Vivec is suggesting. But I think Vivec's "Rainmaker" mention later suggests that the Aedra &amp; Daedra are every bit as vulnerable as ALMSIVI, and for much the same reasons.</p></div>
<div data-ident="18-009" class="commenthidden"><p>The concern Vivec has is that ze will not be replaced by a "better" concept, but rather by one that is more capable of dealing with the current condition of the world. Because ze cannot predict the future, ze cannot adapt hirself to be the best option for every possible scenario. Even a God has limitations, even a God cannot stay eternally relevant. Just ask the Gods of ancient Egypt, who have little to no use in modern society.</p></div>
<div data-ident="18-010" class="commenthidden"><p>These are abstract terms, not synonyms for actual characters. "Executioner" meaning someone who just murders things, a thuggish brute, and "Fool" meaning someone who is concerned for nothing and knows nothing. The crude and the stupid.</p></div>
<div data-ident="18-011" class="commenthidden"><p>That cycle will never stop. There will always be more efficient models. In the future, ALMSIVI may alter their appearances and actions to better meet the whims of culture and politics. But their ideals will not change, since it is their ideals that allow them to alter themselves.</p></div>
<div data-ident="18-012" class="commenthidden"><p>Though no actual proper name has been mentioned, it's easy to guess that The Rainmaker is a God in Western Tamriel who is worshipped in order to bring rain to arid climates. My first guess is that this would be a God of the Redguard in Hammerfell - a culture with so many Gods, they have a God of We Have Too Many Gods.</p>
<p>Gods who preside over rainfall are often present in early cultures, especially ones based in arid climates. It didn't take long for mankind to figure out the connection between water, soil, and the growth of plants. And when the survival of a culture is based on the need for vegetation - for food, clothing, rope, paper, housing, etc. - that culture often respects, reveres, and even worships the processes of the harvest.</p>
<p>But as that same culture discovers and develops new agricultural techniques, the secret processes of birth and growth become known, and therefore less mysterious and magical. They no longer feel the need to pray to their Gods for a bountiful harvest, or for life-giving rain, since they have started dating and planning for the annual change of seasons. The pattern of life becomes clear to them, and, depending on your point of view, they become either unable to see the divinity behind those processes, or they realize there was never any divinity in the first place.</p>
<p>And sure, this could be Shezarr, the Missing God. But Vivec describes the Rainmaker as having once been present, and Lorkhan was never present in Tamriel's known history of linear time. You might also scratch your head at the connection between Shezarr and rain, but the connections between the Thief / Rebel, the insemination and birth of life, and the metaphysical will to change is rather strong.</p></div>
<div data-ident="18-013" class="commenthidden"><p>Vivec is concerned that hir flexibility can be a liability as well as a boon. Because ze works from within the chaotic and flexible landscape of the whim of the people, whereas Seht and Ayem do not, Vivec has to entertain the idea that the whim of the people might eventually render hir useless. Not because ze is actually useless, but because hir people think ze is. Can "the model", or ALMSIVI, be removed or destroyed simply because the people will it to be so? Will they, as suggested by the previous comment, become superfluous?</p></div>
<div data-ident="18-014" class="commenthidden"><p>Now Vivec is truly whole, a fully formed "wheel," and all that it entails. Ze comprehends hir total existence and possibility, and understands the true nature of the universe. Because ze cannot predict the future with 100% accuracy (no one can, I suspect), ze has doubts.</p>
<p>It's also very interesting that this revelation of hir purpose in the universe happens after attaining the shape of the Wheel. In many Tarot systems, the Wheel (or "The Wheel of Fortune") represents a similar knowledge.</p>
<p>In the Tarot, The Wheel involves accepting one's fate, which you can see Vivec doing in this Sermon. According to the card, Vivec looks back on hir life and contemplates every event that has brought hir to the present. While The Wheel does not offer any knowledge of the future, it does reinforce the knowledge that the future will be unpredictable, and this is another cause for worry for Vivec.</p>
<p>I'd also like to recall the line in Sermon 13, which contains a message to the Hortator from Vivec while ze was "not whole." I suspect this is relevant because Sermon 13's message contains a great number of authoritative statements about the future, and Vivec's role in it. After becoming one with the Wheel metaphor in Sermon 17, I think Sermon 18 is the point at which Vivec realizes that not everything has been predetermined, and that the future is uncertain. From this, and many other causes, ze begins to doubt.</p></div>
<div data-ident="18-015" class="commenthidden"><p>Almalexia's reply is that this is why ze was born. She does not say that Vivec has nothing to worry about. Rather, the rather grim message that Vivec's mother gives hir is that ze was born into hir life to fill a role. And while this Sermon carries the theme of the unknowable nature of the future, Ayem gives Vivec one message of certainty:</p>
<p>"There is no need to be concerned with your future usefulness because you can only be that which you already are."</p>
<p>We may never know if Vivec seemed dissatisfied with her answer, but I don't think ze could feel that way - it's the truth, or as close to it as we can get. There's nothing to do with your life except to live in alignment with your nature, and accept the consequences of that decision. But that Ayem answers in this way to the question posed by Vivec carries a hidden, but complex, message.</p>
<p>Since Vivec has achieved the Wheel, ze can look back and remember every event in hir life that has led to this moment. The path ze walks has been revealed to be a clear process of choices and consequences that have placed hir where ze now stands. Hir currency now seems inevitable - it could not have happened any other way.</p>
<p>But instead of feeling limited, like ze has little choice in hir future, Ayem gives him a message of hope: now Vivec knows what ze can do, and what ze must do. "You were born the way you were so that you could perform these great deeds," she says. "Rejoice, for your destiny is in sight."</p>
<p>Therefore, if Vivec acts according to hir nature, as dictated by hir birth, the ultimate solution to the role of the Invisible Gate will be revealed.</p></div>
<div data-ident="18-016" class="commenthidden"><p>Vivec will record hir Book of Hours because it is in hir nature to do so. Ayem has helped Vivec understand who ze is so that ze can listen to hir Will and act according to hir nature.</p>
<p>This need to stay true to one's nature will cause some friction between Vivec and Nerevar later in the Lessons.</p></div>
<div data-ident="18-017" class="commenthidden"><p>I'll explain this in greater detail in Sermon 29, but this line creates the connection between Vivec's nature and the destiny of ALMSIVI, which is the Hurling Disc, which reaches heaven by violence. And if you've read C0DA, you'll know exactly what that is.</p>
<p>This metaphysical prediction is made in this Sermon not only because of the numerological relationship between Vivec and the number 18, but because this Sermon is the point in which Vivec's true path, hir fate, perhaps hir dharma, becomes clear.</p></div>
<div data-ident="18-018" class="commenthidden"><p>That this line resembles a similar line in Crowley's The Book of the Law is probably not a coincidence, and I can't analyze the Crowley line any more thoroughly than Erwin Hessle already has, so you should probably <a class="external" href="http://www.erwinhessle.com/writings/comment.php" target="_blank">go read his notes</a>.</p>
<p>So let's try to see how Erwin Hessle's analysis might apply to this Sermon. If we assume the goal is to discourage people from following the Will of another, it's easy to connect that with the significance of this Sermon - Vivec has found hir fate, the Word of hir Will, and is warning readers against studying this Sermon as though it might also offer them guidance. This Sermon is forbidden because no one should study it for meaning - it contains meaning only for Vivec. This Sermon is untrue because it is a lie to everyone - it is only true for Vivec.</p></div>
<div data-ident="18-019" class="commenthidden"><p>Of course, this variation on the ending refrain of every Sermon save the last is conspicuous at best. And no, of course it's not a typo. Beware of being dragged down by surface-level thoughts - this is a complex concept and it's already been covered in this Sermon's commentaries.</p>
<p>It's been suggested that this could be a reference to the Dragon Break that results from the Tribunal's use of Kagrenac's Tools to ascend to godhood. It's a solid connection, considering the language used during Vivec's Trial at Hogithum Hall:</p>
<blockquote><p>I will leave it to others to find where I have written all this before. But when Vehk the mortal reached into the Heart, he ceased to be anything except for what he wished to be. The axis erupted. There was an exact cracking, an instant of pure Aurbis, his hands burnt black by that ever-nil of static change, and Vivec the god who had never been had always been. A whole universe swelled up to legitimize his throne... as the old universe, where Vehk the mortal still lapped up Godsblood, warped itself to accept its new equivalent. And like all things magical it simply could not happen, could not Be. Red Mountain was the intersection of the Is-Is Not as it was of old, its center point, and it did not hold. And so the Dragon, having broken, saw fit to heal, turning into the world you know. Except now Vivec the God was alive before his own birth, which had, in fact, really happened in the death of the last universe. Hard to grasp in three-dimensional thought? Why, of course it is. And so that is why some semblance of my anguished personal reconciliation found its way into my own scripture. Why did I leave the Nerevarine two accounts of his death, one that I could have easily erased from the minds of my own people? Because he is Hortator, GHARTOK PADHOME AE ALTADOON DUNMERI, my lord and king in this world and the last, and as Vehk and Vehk I murdered him, then raised him, then taught to him to know, and so would I have it when he came to me at last that he decide. I give you this as Vivec.</p></blockquote>
<p>In short, what's being suggested by Vivec is that the entire span of existence came to a sudden, screeching halt when ALMSIVI's apotheosis created a dragon break. And when it was re-created an instant later, ALMSIVI had never been mortal-born and had always been Gods.</p>
<p>This kind of reality-sundering assertion aligns well with Vivec's belief system. You can, given enough knowledge, skill, and power, transform the world.</p></div>
<?php include 'middle.php' ?>
<p>Now Vivec felt that he had taught the Hortator as much as he could before the war with the Dwemer came. The warrior-poet decided he had to begin his <span class="lessonlink" data-call="18-001">Book of Hours</span> at that point, because the world was about to <span class="lessonlink" data-call="18-002">bend with its age</span>.</p>
<p>Vivec entered the Mourning Hold and <span class="lessonlink" data-call="18-003">announced to Ayem</span> that he was going to fight <span class="lessonlink" data-call="18-004">nine monsters</span> that had escaped the Muatra.</p>
<p>'I will return,' he said, 'to deal the last blow to the grand architect of the Dwemer.'</p>
<p>Ayem said, 'Out of nine you will find only eight, though they be mighty. The last is already destroyed by your decision to create the Book of Hours.'</p>
<p><span class="lessonlink" data-call="18-005">Vivec understood that Ayem meant himself</span>.</p>
<p>'Why,' she asked, 'are you in doubt?'</p>
<p>Vivec knew that <span class="lessonlink" data-call="18-006">his doubt</span> made him the sword of the Triune and so he did not feel shame or fear. Instead, he explained and these are the words:</p>
<p>'Can a member of the <span class="lessonlink" data-call="18-007">Invisible Gate</span> become <span class="lessonlink" data-call="18-008">so archaic</span> that its successor is not so much an improvement of the exact model, but rather a related model that is just needed more because of <span class="lessonlink" data-call="18-009">the currency of the world's condition</span>? As the Mother, you do not have to worry, unless things in the future are so strange that even Seht cannot understand. Neither does the <span class="lessonlink" data-call="18-010">Executioner or the Fool</span>, but I am neither.</p>
<p>'These ideals are <span class="lessonlink" data-call="18-011">not going to change in nature</span>, even though they may change in representation. But, even in the west, <span class="lessonlink" data-call="18-012">the Rainmaker</span> vanishes. No one needs him anymore.</p>
<p>'Can one oust the model not because the model is set according to an ideal but because it is tied to an ever-changing <span class="lessonlink" data-call="18-013">unconscious mortal agenda</span>?'</p>
<p>This is what was said to Ayem when Vivec was whole. <span class="lessonlink" data-call="18-014">The wise shall not mistake this</span>.</p>
<p><span class="lessonlink" data-call="18-015">Ayem said</span>, 'This is why you were born of a netchiman's wife and destined to merge with the simulacrum of your mother, gilled and blended in all the arts of the star-wounded East, under water and in fire and in metal and in ash, six times the wise, to became the union of male and female, the magic hermaphrodite, the martial axiom, the sex-death of language and unique in all the middle world.'</p>
<p>Vivec knew then <span class="lessonlink" data-call="18-016">why he would record his Book of Hours</span>.</p>
<p><span class="lessonlink" data-call="18-018">This sermon is forbidden.</span></p>
<p>In this world and others <span class="lessonlink" data-call="18-017">EIGHTEEN</span> less one (the victor) is the magical disk, hurled to reach heaven by violence.</p>
<p>This sermon is untrue.</p>
<p><span class="lessonlink" data-call="18-019">The ending of the world is ALMSIVI</span><a href="../css/images/36rages/<?php echo pad($sermon); ?>.png">.</a></p>
<?php include 'footer.php' ?>