<?php
$sermon = '19';
include 'header.php';
?>
<div data-ident="19-000" class="commenthidden"><p>Sermon 19 of the 36 Lessons of Vivec describes, in some detail, the state of consciousness that Vivec uses to observe the world around hir, and to plan hir attack on the children of Molag Bal.</p><p class="horizline"></p>
<p>In Morrowind, Sermon 19 grants a bonus to the Enchanting skill. It is worth 200 Septims and weighs 3 units. Copies can be found in the <a class="external" href="http://en.uesp.net/wiki/Tribunal:Residential_Ruins" target="_blank">Residential Ruins</a> of Old Mournhold, and in <a class="external" href="http://en.uesp.net/wiki/Morrowind:Palansour" target="_blank">Palansour</a>. It can also be bought by <a class="external" href="http://en.uesp.net/wiki/Morrowind:Maren_Uvaren" target="_blank">Maren Uvaren</a>, an enchanter at Tel Aruhn.</p>
<p>Sermon 29 names this Sermon "The Provisional House". Its number is 258, which correlates to the word "this".</p></div>
<div data-ident="19-001" class="commenthidden"><p>Immediately we're reminded of Vivec's warning in Sermon 11, that a Ruling King is armored head to toe in brilliant flame. It's entirely probable that Vivec's "armor" in Sermon 19 is the very same fire we've discussed previously: that holy aura of perfect knowledge that is required to reach a state of CHIM.</p>
<p>Also keep in mind that Vivec puts on this armor voluntarily, as though ze is preparing for the upcoming endeavor. Perhaps this is a ceremonial event, like a glorious leader donning a uniform, but also because ze is preparing for a dangerous and violent encounter. This is an unconscious admission of vulnerability, and God is armored head to toe in terror. That's going to be incredibly relevant later in this Sermon's commentary.</p></div>
<div data-ident="19-002" class="commenthidden"><p>Here we begin the discussion of another point of contention in the 36 Lessons: the true nature of the Provisional House. Most people have a problem conceptualizing the various ways the Provisional House is described, so I'll work on each term individually. Interestingly, there are often several different ways to interpret each term, and many of them work together. So pick what you like.</p>
<p>Anyway, a non-spatial space can be explained as a fourth-or-higher dimension, which is to say a point of spacetime that contains all possible spacetime dimensions within a single higher-level dimension. It'd be helpful at this time to refer you once again to the excellent video "<a class="external" href="https://www.youtube.com/watch?v=XjsgoXvnStY" target="_blank">Imagining the Tenth Dimension</a>." Or, if you're a math major, this could be a "set of all sets."</p>
<p>It can also refer to a state or dimension that exists "outside" or "above" the standard spacetime dimension, by which I mean Mundus.</p>
<p>Oblivion qualifies as both of possible explanations, in that it contains both all possible spacetimes (Mundus, Daedric dimensions) within a single dimension.
It's possible to consider that this dimension could be similar to a Daedric Plane willed into existence by Vivec in much the same way that a traditional Daedric Prince might create its own Daedric dimension. And since Mundus was formed within Oblivion, and Oblivion is the "womb" in which creation can take hold, this makes a lot of sense.</p>
<p>Vivec has to establish this "outer world" because the wisdom ze gains can't be understood while ze still remains within the mortal realm. This makes sense if you try to imagine visualizing the entirety of something while dwelling within it. Instead, Vivec closes hir eyes to the world and, in so doing, becomes capable of visualizing the world's true nature. Depictions of Siddhārtha attaining enlightenment often depict him to have his eyes closed, or heavily lidded, for similar reasons.</p>
<p>Another possible avenue is Asmodean flight. Asmodeus is a spiritual entity or demon associated in many cultures including Persia, Hebrew, and even into classical Europe. Voltaire and numerous writers make mention of him, and Shakespeare even uses a portrayal of him in King Lear, as familiar Modo, demon gentleman of Murder. He is thought to be able to be invoked to allow someone to rise up and see into their neighbor's houses, not by giving the x ray vision, but by taking them to a place (usually up) to where they can see through the ceiling or through or around walls and corners, which sounds similar to experiencing extra-dimensional awareness. An awareness from a higher dimension may allow you to see through to things that were previously obscured from sight, like seeing into the interior of a 2d blueprint.</p></div>
<div data-ident="19-003" class="commenthidden"><p>It is important to think of this "cartography" as canvas-less because it is not a map, not a two-dimensional representational of a three-dimensional structure. We can probably therefore guess that this dimension's description of what it represents is complete and total in a way that a map of a mountain isn't.</p></div>
<div data-ident="19-004" class="commenthidden"><p>This is a little tricky.</p>
<p>If we consider the non-spatial space to be an omni-dimensional (or at least higher-dimensional) state, then it has known every single mind that has ever existed. Possibly even minds that could potentially exist.</p>
<p>Alternatively, if the dimension is limited, it's likely that the dimension has only known the minds that Vivec has met. If that's true, then it becomes more closely linked to Vivec.</p>
<p>So where is this dimension, from within which Vivec creates the Provisional House? Are there any more details we can integrate?</p>
<p>A final clue can be found in the Loveletter from the Fifth Era, in which Jubal Lun Sul offers a diagram of the subgradient structure of the universe. At the "bottom" of these layers of subgradient lies something Jubal calls "Z", which is to say the "end" of reality. He describes "Z" as a "state-gradient echo of Mundus centerex," which I've explained in literally the first essay I ever wrote for TES lore.</p>
<p>I think these concepts make this non-spatial space fairly clear. Although the specific results might change depending on the person, for Vivec, the state of CHIM grants hir the knowledge of "the mind of the world," by which we mean Mundus, and includes all that dwells in Mundus. This comes with the sure knowledge of the existence of the Godhead, and by extension the non-existence of Vivec hirself, which is the existential crisis that threatens all those who might achieve CHIM.</p>
<p>Vivec could have easily become lost in this state of perception. Ze could have succumbed to the sea of minds around hir, and lost hir sense of self. Or ze could have gone insane in the terrifying presence of the Godhead entity. Or ze could have surrendered and ceased to exist in the harsh truth of mathematics.</p></div>
<div data-ident="19-005" class="commenthidden"><p>Moths have often been used as a symbol of Cyrodiil, the Elder Scrolls themselves, the new Cyrodilic culture (post-Alessian rebellion) and the Empire. I'm honestly not sure why that is. The connection between moths and the ancestral memories and souls of Cyrods is very firm, however, since members of the Cult of the Ancestor Moth are known to wear robes made from silk spun from these moths. Some monks of particularly high ranks simply wear the moths themselves, as the insects rest upon their bodies.</p></div>
<div data-ident="19-006" class="commenthidden"><p>This is Tiber Septim, who possesses (depending on your interpretation of his legend) at least two or more souls. Vivec foresees his approach because, aside from hirself, Tiber Septim will become the most powerful mortal in the history of Nirn. And as ze eventually discovers, Tiber Septim's role in the future of Nirn is almost as important as Vivec's.</p></div>
<div data-ident="19-007" class="commenthidden"><p>These are the Aedra, rendered voluntarily imperfect from their contributions to the creation of Mundus. They have chosen to be exiled from the realm of the Gods, but they are never truly removed entirely, since Mundus exists within Oblivion and therefore also within Aetherius.</p></div>
<div data-ident="19-008" class="commenthidden"><p>In the respect that it is two circles joined by a chain. Of course, the metaphor is interesting as well. Are they shackles because both (?) souls of Tiber Septim are tied together? Or because Tiber Septim is playing the role of a prisoner (aka a Thief)?</p>
<p>Or perhaps the "crown" is a prison because it is comprised of a Nirnian structure, specifically one constructed by the eight Aedra? If any criticism can be levied against Tiber Septim, it's that he achieved his divinity by mantling Lorkhan, which may have tied him irrevocably to the Kaplic cycle. Vivec could well see this as an imprisoning because it might (and I may be reaching here) keep Tiber Septim from leaving the Kalpic cycle. If he's shackled to the Eight Aedra and their creation, he can't leave it. Tiber Septim (and perhaps all of Man) is imprisoned in Mundus, but the Mer do not enjoy that problem.</p></div>
<div data-ident="19-009" class="commenthidden"><p>Vivec implies, via the river metaphor, that Tiber Septim's insatiable "hunger" to conquer is driven at least in part by his dual-souled nature.</p></div>
<div data-ident="19-010" class="commenthidden"><p>This is the secret door mentioned in Vivec's prayer, which we last heard in Sermon Three. This would place the Provisional House, and Vivec's metaphysical state of CHIM, in the "Altar" of Padhome, in the "House" of Boethiah. Ze places it here, at the center, for the same reason that the Center must be surrounded to form a Wheel. The Provisional House therefore becomes the place of possibility from which Vivec may produce a result. That it is "Provisional" plays to the CHIM symbol, a flickering insignia, uncertain and temporary.</p>
<p>But why is it called a Provisional House, exactly? As we've already covered (at least in Sermon 10), houses can be a very negative concept, so why does Vivec build hir own house?</p>
<p>Vivec understands the similarities between the metaphors of Houses and Towers. The Provisional House acts as a "safe" state from which Vivec can launch hir offensive against hir children, and therefore, like a tower, it is reinforced and armored and it protects a vital secret. Think about the typical "mage's tower," built by a magician to protect the secrets he's collected, but also to provide that mage with the isolation he needs to work. Isolation similar to what a monk uses to meditate, or a cloistered priest uses to study. The Tower metaphor works on so many levels.</p>
<p>Now let's talk about Houses as Aleister Crowley considers them. And let's credit BuckneyBos, since he's done the heavy lifting for me.</p>
<p>Crowley proposed that every being, God and Mortal alike (for he proposed that they were the same), was comprised of nested houses, each of which was marked by a mystical name.</p>
<p>The nesting of these houses is relevant, because it is metaphorically similar to the structure of the wheel - Each house is a Tower, which the Thief must infiltrate. Each Tower holds within it another Tower. The Thief (aka the Incarnation, the practitioner, the magician, etc.) must infiltrate each house, from the lowest to the highest, or from the physical to the solar self. Eventually, at the core, the thief reaches the Star - the inner God.</p></div>
<div data-ident="19-011" class="commenthidden"><p>Put yourself in Vivec's position. You've achieved this amazing new state of perception, you've created this incredible metaphysical fortress, universe-spanning knowledge is at your fingertips, and suddenly you're confronted by this strange song that almost makes sense, but not quite.</p></div>
<div data-ident="19-012" class="commenthidden"><p>At this point, Vivec has been given the vision of hir entire purpose. Ze understands hir destiny from hir conversation with Ayem in the previous sermon, and now ze sees the full extent of those trials, every one of them, in great detail. Ze has visualized the mind of Mundus, and its full purpose, and so ze also visualizes the full extent of hir nature, and what the future holds. Surely it must've come as a blow to Vivec when ze realized that ze would not become the New Man, the Amaranth, a "true" God.</p>
<p>Now, as with all parents, ze must realize that it is hir destiny to make hir dreams possible for hir children (which is to say the Dunmer), not hirself.</p></div>
<div data-ident="19-013" class="commenthidden"><p>Back to the armor chosen to be don in the beginning, it comes full circle. Vivec achieves in some level what ze sought out to do, yet experiences fear in the new safe place. Relevant here is this quote from <a class="external" href="https://www.imperial-library.info/content/more-psijic-endeavor" target="_blank">More on the Psijic Endeavor</a>: "One that knows CHIM observes the Tower without fear. Moreso: he resides within." Vehk has made a special seat to reside within the Tower, but is not quite completely without fear. The armor ze wears may just as well be a cloak to hide hir subconscious insecurities, as well as something to aid Vivec in conquering them. Overcoming that insecurity is one facet of the many-sided key that is needed to unlock the final Gate, and it might have been the only facet Vivec needed to solve.</p></div>
<div data-ident="19-014" class="commenthidden"><p>It probably isn't any surprise to Vivec, at this point, that ze can't make the final leap to Amaranth. Hir emotional response to hir own House, a structure of hir own creation, is one of fear and uncertainty. This relates, philosophically, to Carl Jung's exploration of his inner nature in The Red Book. He discovers that he his repulsed by much of what he sees, and he realizes, in later self-examination, that his repulsion is what keeps him from attaining a higher level of self-comprehension. This ability to love that which most repulses us is related again to the enantiomorphic process - chiral opposites repel each other. But unification of opposites is the only goal of the enantiomorph, and by extension, of apotheosis and Love.</p>
<p>Vivec can't Love hirself because ze can't accept hir true nature. And since that true nature is (as Almalexia has already revealed in Sermon 18) to not become the Amaranth, Vivec's dissatisfaction prevents that becoming. It's a circular argument, but that shouldn't surprise you. The logic is simple: to become the Amaranth, one must simply be the Amaranth. And what keeps Vivec from becoming the New Man is that ze is not the New Man. It's a self-fulfilling prophecy.</p></div>
<?php include 'middle.php' ?>
<p>Vivec <span class="lessonlink" data-call="19-001">put on his armor</span> and stepped into a <span class="lessonlink" data-call="19-002">non-spatial space</span> filling to capacity with mortal interaction and information, a <span class="lessonlink" data-call="19-003">canvas-less cartography</span> of <span class="lessonlink" data-call="19-004">every single mind it has ever known</span>, an event that had developed some semblance of a divine spark. He said, 'From here I shall launch my attack on the eight monsters.'</p>
<p>Vivec then saw the <span class="lessonlink" data-call="19-005">moths that would come from the starry heart</span>, bringing with them dust more horrible than the ash of Red Mountain. He saw the <span class="lessonlink" data-call="19-006">twin head of a ruling king</span> who had no equivalent. And <span class="lessonlink" data-call="19-007">eight imperfections</span> rubbed into precious stones, set into a <span class="lessonlink" data-call="19-008">crown that looked like shackles</span>, which he understood to be the twin crowns of the two-headed king. And a river that fed into the mouth of the two-headed king, because <span class="lessonlink" data-call="19-009">he contained multitudes</span>.</p>
<p>Vivec then built the Provisional House at the Center of the <span class="lessonlink" data-call="19-010">Secret Door</span>. From here he could watch the age to come. <span class="lessonlink" data-call="19-011">Of the House is written</span>:</p>

<p>Cornerstone one has a finger</p>
<p>Buried under, pointing through</p>
<p>Dirt, slow low in the ground</p>
<p>North cannot be guessed,</p>
<p>And yet it is spirit-free</p>

<p>Cornerstone two has a tongue,</p>
<p>And even dust can be talkative,</p>
<p>Listen and you will see the love</p>
<p>The ancient libraries need</p>

<p>Cornerstone three has a bit of string,</p>
<p>Shaped like your favorite color,</p>
<p>A girl remembers who left it there</p>
<p>But she is afraid to dig it out,</p>
<p>And see what it is attached to</p>

<p>Cornerstone four has nine bones,</p>
<p>Removed carefully from a black cat,</p>
<p>Arranged in the fashion of this word,</p>
<p>Protecting us from our enemies</p>

<p><span class="lessonlink" data-call="19-012">Your house is safe now</span></p>
<p><span class="lessonlink" data-call="19-013">So why is it--</span></p>
<p>Your house is safe now</p>
<p>So why is it--</p>
<p><span class="lessonlink" data-call="19-014">The ending of the words is ALMSIVI</span><a href="../css/images/36rages/<?php echo pad($sermon); ?>.png">.</a></p>
<?php include 'footer.php' ?>