<?php
$sermon = '20';
include 'header.php';
?>
<div data-ident="20-000" class="commenthidden"><p>Though this sermon speaks clearly about the necessity to rid oneself of the rigid and inflexible natures, connections to spiritual enlightenment and self-awareness are hidden just beneath the surface. It features the first flaw in Vivec's character that must be defeated according to hir nature. This is an act of Love under Will, since Vivec is not preoccupied with what ze will or won't gain. There is no desire for result, just adherence to hir Will. Ze thinks only of the task at hand.</p>
<p class="horizline"></p>
<p>In Morrowind, Sermon 20 grants a bonus to the Long Blade skill. It is worth 200 Septims and weighs 3 units. Copies can be found in the Arobar Guard Quarters in <a href="https://en.uesp.net/wiki/Morrowind:Ald%27ruhn" target="_blank" class="external">Ald'ruhn</a>, <a href="https://en.uesp.net/wiki/Morrowind:Drarayne_Thelas" target="_blank" class="external">Drarayne Thelas</a>' house in Balmora, and the Secret Library in the Hall of Justice in <a href="https://en.uesp.net/wiki/Morrowind:Vivec_(city)" target="_blank" class="external">Vivec</a>.</p>
<p>Sermon 29 names this Sermon "The Lunar Lattice". It's number is 425, which correlates to the word "path".</p></div>
<div data-ident="20-001" class="commenthidden"><p>Vivec and hir first child share a similar nature, or in the least, this child mirrors hir own complexity.</p><p>Vivec was born "twice" because ze had two parents - the Netchiman's Wife, and Sotha Sil & Almalexia. This brings to mind the Greek God Dionysus, who also had two parents, Semele and Zeus. This, and other characteristics, bring Moon-Axle thematically closer to his Mother/Father Vivec than many of Vivec's other children.</p></div>
<div data-ident="20-002" class="commenthidden"><p>Names, as we've already established in previous sermons, are incredibly important in the world of magic. The simplest explanation of Moon-Axle's name is that it combines two chiral elements - a circle (the moon) and a straight line (the axle). The metaphysical implications are probably obvious.</p><p>There's more to get out of such a name, however. If taken as Lunar Axis, perhaps Earth's moon might tell us something. The Moon, like Earth, rotates on its axis as well, only it's rotation is synchronized with its orbit so closely that it appears to always be facing the earth the same way. Even though it may wax and wain, the light side always pointing towards the observer, and the dark side always obscured from sight. Moon symbolism usually relates towards the opposition of giving light and life (dark, secretive, and illusionary) and links towards the tidal influence, the depths of subconscious thoughts, fears, or the underworld.</p><p>Moon-Axle's name also reminds us of the Ego-Self Axis as described by Carl Jung, who used it as a system to explain self-analysis and the importance of psychological awareness and spiritual growth. We'll explain more of that later in this chapter.</p></div>
<div data-ident="20-003" class="commenthidden"><p>It's certainly possible this might refer to flaws in the environment, or in natural law, but the word "foible" refers specifically to flaws in someone's character. So I think that, among the various other ways that Moon-Axle resembles his mother-father, he also "harvests" flaws of character.</p><p>Each of Vivec's children represent the flaws in hir character, foibles of nature, like those harvested by Moon Axle.</p><p>Sotha Sil discusses the Aedric Imperfections quite a bit in Elder Scrolls Online, describing them as "Thrones," the seats of symbols, and their kingdoms are context. So perhaps Moon-Axle was a throne seeker, trying to define its kingdom by picking up the scraps (maybes) that were not yet claimed by other Kings.</p></div>
<div data-ident="20-004" class="commenthidden"><p>This describes the danger Moon-Axle presents to Velothi, he brings about chaos and ruin when he exercises the predatory part of his nature. Unwritten law is dangerous because laws must be followed, and unwritten laws change constantly, which makes them resemble oppression. Rules that are not defined cannot be followed, and only bring suffering when they are enforced.</p><p>From a Psycho-Philosophical view, an analogy can also be made towards the child's interaction with reality. First harvest being the perception of nature's foibles where they are first taken in when encountered. The subsequent yielding then could be appropriation and re-purposing of these inputs by the consumer for the purpose of self-reinforcement or emotional response.  The ruinous uncertain laws would then be akin to manipulative fallacious assertions or emotional reactions.</p></div>
<div data-ident="20-005" class="commenthidden"><p>This could be a somewhat 4th-wall jab at low-polygon art assets, but philosophically it speaks to the mathematical inability for straight lines to accomplish true curvature. You can add as many microscopically small lines to a shape, but that shape will never attain a true curvature while it still consists of straight lines.</p><p>Thematically, this reminds us of one of the many subtextual questions in the 36 Lessons: can a mortal become a God? If a mortal adds power after power, heaps knowledge up on knowledge, is that mortal still a mortal? Plato's theory of Forms might argue against such Godhood - something might resemble the Original Thing, perhaps to practically identical levels, but it will never become the Original Thing.</p><p>Take the simple nature of a circle. Reproducing a circle with straight lines is simply impossible. <a href="../css/images/circle06.png" class="imgModal">We can try six sides</a>, and our shape looks nothing like a circle. <a href="../css/images/circle12.png" class="imgModal">Double our lines</a>, and we still aren't close. <a href="../css/images/circle36.png" class="imgModal">Even with 36 lines</a>, it's obvious we're still struggling to reproduce something that has nothing of what we have in excess. The circle contains no straight lines, and yet even if we were provided with a million of them, we could never use straight lines to build a shape that replicates a shape that doesn't use them.</p><p>This illustrates the true nature of the "other," of the divine. The circle exists in a state of perfection that cannot be reached with straight lines. No amount of addition can bring you back around to zero.</p><p>And this might be another truth that Vivec struggles against in hir life. But ze might argue that if perception is reality, the Original Thing is rendered irrelevant.</p></div>
<div data-ident="20-006" class="commenthidden"><p>When the Ego is confronted directly, there tends to be a reaction from the Ego as it tries to reassert itself. Part of the mystic ambition to rid oneself of Ego involves subduing these assertions of the identity, the many statements of "I am," "I want," "I don't want," "I fear," etc, since they are thought to be illusionary and serving only to to keep one from the goal of true self or unity. Crowley's poem <a class="htmlModal" href="dustdevils">Dust Devils</a> describes whirling torrents composed of "I's" in the Abyss representing that such assertions needed to be overcome to achieve "<a class="external" href="https://en.wikipedia.org/wiki/Ego_death" target="_blank">ego death</a>". Carl Jung also dealt with this kind of composition of the Ego, only for him, and later for Joseph Campbell, its death wasn't necessary on the path towards personal fulfillment and potential, but yet did warn against being ruled by Ego's dictatorship.</p>
<blockquote><p>"The ego wants explanation always in order to assert its existence...Try to live without the ego. Whatever must come to you, will come... Don't allow yourself to be led astray by the ravings of the animus... He will try every stunt to get you out of the realization of stillness, which is truly the Self."</p><p>-Carl Jung Letters Vol I pg 427.</p></blockquote>
<blockquote><p>"The dragon is your ego, holding you in... What I want. What I believe. What I can do. What I think I love, and all that. What I regard as the aim of my life and so forth. It might be too small. It might be that which pins you do down. And if it's simply that of doing what the environment tells you to do then it certainly is holding you down, and so the environment is your dragon as it reflects within yourself."</p><p>- Joseph Campbell</p></blockquote></div>
<div data-ident="20-007" class="commenthidden"><p>So let's talk about the stages of evolution in the the <a href="../css/images/ego-self-axis.png" class="imgModal">Ego-Self Axis model</a>.</p>
<p>First, quick definitions: The Ego is the center of consciousness. The Self is the center of the total personality, which includes consciousness, the unconscious, and the ego. This means that the Self is both the whole <em>and</em> the center.</p>
<p>Early stage: You are part of the world, you react to stimuli, the sensual world. Young children are an example of this, in that they are often completely unable to exhibit behavior consistent with self-awareness, and simply react to everything around them without thought or analysis. This stage is the first diagram of our image.</p>
<p>Middle stages: In the next two stages, the Ego becomes aware of the Self, gradually extending beyond the Self so that it can observe the Self from an external perspective. The Ego-Self Axis is the line joining these two entities.</p>
<p>Last Stage: In the last diagram of our image, the Ego becomes aware of the Self, gradually, and both are now able to perceive each other and communicate their needs and wants. A person who has achieved this state is, among other things, fully aware of his or her actual needs, and can communicate with, and think critically about, every aspect of his or her nature.</p>
<p>Similar concepts to Ego-Self Awareness are repeated by other philosophers and psychologists including Abraham Maslow (who famously called it "self-actualization"), among others. But while the specific behavior and requirements change, the general uniting theme among these various explanations is that the enlightened individual is generally happier and more perceptive and receptive to the lives of others. It's not hard to suggest that this is a state required to become a God in the Elder Scrolls universe.</p></div>
<div data-ident="20-008" class="commenthidden"><p>This is Vivec's other famous weapon - a sword that hovers in mid-air, just out of reach, controlled by hir thoughts, presumably. It's also possible that this sword is "not held" because it is the Treasure Wood Sword from Sermon 22, which means that Vivec doesn't technically have it, yet. Of course, linear causality is not a thing that bothers Gods like Vivec.</p>
<p>Another take on "not held" could be that the sword is akin to "Intellect..." a sharpened edge to bring against complexity and break it down into examinal pieces.</p></div>
<div data-ident="20-009" class="commenthidden"><p>The purpose of Vivec's crusade against hir children is to correct the flaws that they embody, not to destroy or remove them. Since Moon-Axle has been absorbing the flaws of nature instead of re-configuring them, Vivec has to put them back where they originated so that they can be corrected by the people who own them.</p></div>
<div data-ident="20-010" class="commenthidden"><p>There's two ways I took "unsolved." Actually, there's a lot of directions I went, but only a couple that I liked.</p>
<p>The easiest was Freud's theory of penis envy, the heteronormative idea that all women experience a psychological shock when they realize that they do not have a penis, and that (similarly) all men experience a shock when they realize that all women do not have a penis. It's… I mean, it was the beginning of modern psychology, a product of the age in which it was born. But Elder Scrolls lore frequently makes references to ancient science (like Phlogiston) without judgement, so maybe this is a similar thing? Or Freud was just a bit of a tool. Could be a mix of both.</p>
<p>There's also an interesting (and similarly heteronormative) idea that an "unsolved woman" is a woman who is waiting to be (but not yet) penetrated, or a woman who seeks to be impregnated. Both conditions seem to involve metaphysics more than psycho-sexual science, since both share themes common with the Enantiomorph.</p></div>
<div data-ident="20-011" class="commenthidden"><p>And so, the flawed becomes perfect, and the union of male and female. But also the completion of both sides of an unsolved equation, since both Vivec and Moon-Axle are part of the same equation, and the inequality has been resolved. Returning to the "unsolved woman," there is no coincidence (since Vivec destroyed it) that "solving" Moon-Axle involves penetration.</p></div>
<div data-ident="20-012" class="commenthidden"><p>As Moon-Axle described himself earlier, his microscopic lines are constantly shifting. This gave him power, since he combined constant change with defined linearity, reminding us of Mundus's nature. Once Vivec removed this aspect of divinity, Moon-Axle had nothing left except stasis, which then shattered under the weight of entropy.</p></div>
<div data-ident="20-013" class="commenthidden"><p>Because Moon-Axle's lines have become static, they resemble the stasis of the Aedric gift-limbs, and can be used to create what the sermons call "mystery wheels." I don't think we've seen these wheels described elsewhere, but it's pretty easy to assume that these are mystical mortal-made constructions that resemble the wheel of Mundus, as outlined in previous sermons.</p>
<p>From an Alchemical view, we see the separating of the Formulae, quickly then followed by the putting back together. "Solve et Coagula," or "dissolve and coagulate," which speaks to the need to break down a substance before rebuilding it.</p></div>
<div data-ident="20-014" class="commenthidden"><p>The <a href="https://en.wikipedia.org/wiki/Sufi_whirling" target="_blank" class="external">Sufi Turning</a> art practiced by the Melevi Order since the early 14th century is a mystical form of prayer or meditation. It focuses on abandoning the ego so that the soul can commune directly with God, a process generally similar to the Gnostic accomplishment of the same. And in the sermons, the Whirling School almost certainly communes with Vivec. I'm just speculating here, but I think it's a good bet that the Whirling School also whirls to resemble the turning of the Aurbic Wheel.</p>
<p>Marie-Louise von Franz also describes the spinning of the self when it is out of control, or imbalanced:</p>
<blockquote><p>"It can cause people to 'spin' megalomaniac or other delusional fantasies that catch them up and 'possess' them. A person in this state thinks with mounting excitement that he has grasped and solved the great cosmic riddles; he therefore loses all touch with human reality. A reliable symptom of this condition is the loss of one's sense of humor and of human contacts."</p></blockquote></div>
<div data-ident="20-015" class="commenthidden"><p>It is certainly possible for a "regular" inhabitant of Mundus to understand and even believe in the concept of CHIM and the dream-state universe. But it is another thing entirely for a person to completely comprehend, with their mind, body, and soul, the same concepts.</p>
<p>To paraphrase a section from "Zen: Merging of East and West" by Roshi P. Kapleau -</p>
<blockquote><p>Reading about CHIM is like reading about nutrition when you're hungry. Only when you taste, chew, and swallow the food will you feel satisfied. And even then, the food you have eaten will not nourish you until digestion and assimilation has taken place. This is similar to CHIM. Until you have integrated into your daily life what you have perceived, your awakening is not working for you yet - it will not transform your life. And just as the final step in nutrition is elimination, so one must eventually rid oneself of the notion of "<em>I</em> am enlightened." Only then can you walk freely between heaven and earth.</p>
<p>Now suppose your foot itches. Does it feel better to scratch your bare foot, or to scratch the itch through your shoe? Reading about CHIM is like scratching an itch through your shoe.</p></blockquote></div>
<div data-ident="20-016" class="commenthidden"><p>The Aurbis is "egg-layered" in the respect that it is comprised of layers, each of which is distinct and serves a purpose. The egg-shell Aetherius protects the albumen of Oblivion, and the yolk of Mundus holds the environment within which life can be born.</p></div>
<div data-ident="20-017" class="commenthidden"><p>"A symbol (god) without a context (house) is meaningless. A context without a symbol is sterile. Neither the god nor the house can exist separately, for they condition and change each other. So for every god or goddess there is a house and for every house there is a god or goddess, though they may not be visible or apparent." God, I love <a href="http://www.aiwass.com/A_Secret_Key_Of_Thelema.html" target="_blank" class="external">this quote</a>. Vivec's name is alive because it exists within its House and context, and is fertile due to being alive with meaning and of a context of hirself.</p></div>
<div data-ident="20-018" class="commenthidden"><p>This would likely be the third walking way, since Vivec defeats hir opponent, of course.</p></div>
<div data-ident="20-019" class="commenthidden"><p>Don't <a href="https://en.wikipedia.org/wiki/Semantic_satiation" class="external" target="_blank">speak words so often</a> that they lose their power. Remember that empires, like all constructions, are temporary and must die or be changed. Similarly, the meaning of words change over time. "Awful," for example, used to mean "full of awe," which is how we got sentences like "the awful majesty of God."</p></div>
<div data-ident="20-020" class="commenthidden"><p>Perhaps this explains why Vivec doesn't take a more active role in Almalexia's rule - the Sword is an Exercise of the Ego. You practice the Ego early in life and then you put it aside.</p>
<p>For Crowley, the Sword as Intellect was meant to be the instrument used to rid oneself of the complexity that shrouded the inner Will. However, it had a seemingly paradoxical annotation to it, since the sword itself also represented the same faculties it is used to cut free. "One who lived by the sword, dies by the sword." The meaning, however, is that by sharpening the mental faculties to purge emotion from perception would ultimately lead one to eliminate the need for the tool. The sword being the means of removing "one" from "one's self". This is why the word "statesmanship" was chosen - it is removal of the leadership of linear structure, of command through bureaucracy.</p></div>
<div data-ident="20-021" class="commenthidden"><p>An interesting and easy to overlook turn of questioning by Vivec to hir followers. If one successfully subdues their Ego, by what will is this done? After all, desire, and the subjective action resulting from said desire, are things derived from the assertions of the Ego. The reason ze questions hir followers this is to draw distinction on how Vivec accomplished the subjugation of hir first child. This was not an act of want, need, desire, or even conscience choice… but it was an act of Vivec's unique and divine Will, which proved too much for the inflexible, assembled assertions of Moon-Axle.</p></div>
<div data-ident="20-022" class="commenthidden"><p>There is nothing beyond the solution. This is the complete state in which everything is solved. If you don't get it right the first time, there won't be a second time.</p></div>
<div data-ident="20-023" class="commenthidden"><p>I don't know about elements, but maybe this is "my existence allows the Earth to live?" It's not just outward, it's inward, so Vivec comprises the hub, the center, and the spokes - Ze surrounds and dwells within.</p></div>
<div data-ident="20-024" class="commenthidden"><p>Ego is the conscious awareness of the Self and the assertions to its identity, the Self is the unconscious self which is "<a href="https://books.google.com/books?id=xn5pY3z5Kf4C&pg=PA115&lpg=PA115&dq=campbell+ego+self+potential&source=bl&ots=-9HSbd6Fi4&sig=j0i-YDzELjVGSi9fNerXL5WplR4&hl=en&sa=X&ved=0ahUKEwi7h7eTne3ZAhVNeawKHWKIA7oQ6AEIRDAE#v=onepage&q=campbell%20ego%20self%20potential&f=false" target="_blank" class="external">the whole context of potentials</a>" contained within the individual. While the Ego is a collection of "I's" that you experience, the True Self is the sum of an individual's complete inward freedom to be anything and everything they could potentially be. Vivec is a cause for great density simply because ze can be anything within the context of hirself.</p></div>
<div data-ident="20-025" class="commenthidden"><p>This might just be related to the weight, or importance, of the thought. We might not need to associate the "axle" in this sentence with Moon Axle, or the tower at the center of a Wheel. But hey, what's the point of that?</p>
<p>Remember that the Ego-Self Axis maps the self-awareness needed for spiritual improvement and awakening. Vivec's warning, in this case, explains the danger of a thought that could destroy that mystical formation, and undo the magician's efforts to analyze, improve, and accept himself.</p></div>
<div data-ident="20-026" class="commenthidden"><p>The first stage of understanding one's ego to discover and conceptualize how it operates. Every assertion, emotional response, or raising of opinion starts with the ego inserting itself as an intermediary between the self and the world that one is faced with. While drawing upon <a href="https://en.wikipedia.org/wiki/Ego_death" target="_blank" class="external">Ego-Death</a> imagery here, defeating Moon-Axle may not necessarily be the total destruction of ego. More that it was overcoming ego's tyranny over the self by solving it's assertions (cut and set aside). Vivec can now proceed in further exploring hir true nature unobstructed by misleading lines (Ego-tampering), or with the flexibility of curves that straight lines do not provide.</p>
<p>This relates to the paradox of individuation, that a person must begin to lose their sense of individuality in order to realize their true individual nature. This is because what makes us unique is not our desires, or our fears, but rather how we exist without those falsehoods.</p></div>
<?php include 'middle.php' ?>
<p><span class="lessonlink" data-call="20-001">The first monster was actually two, having been born twice like his mother-father, Vivec</span>. He was not the mightiest of the eight to escape Muatra, but his actions were the most worrisome. <span class="lessonlink" data-call="20-002">He was known as Moon Axle</span>, and <span class="lessonlink" data-call="20-003">he harvested the leftovers foibles of nature</span>. This he did twice, as was said, and <span class="lessonlink" data-call="20-004">the second harvest always brought ruin or unwritten law</span>. His aspect was <span class="lessonlink" data-call="20-005">faceted like a polyhedron</span>.</p>
<p><span class="lessonlink" data-call="20-007">No perils are mentioned</span> in the finding of Moon Axle, but it was known that he was immune to spears, so <span class="lessonlink" data-call="20-008">Vivec had to use the sword not held against him</span>. Before he took issue with the monster, the warrior-poet asked:</p>
<p>'How came you to be immune to spears?'</p>
<p>To which Moon Axle replied, 'Mine is a dual nature, and protean. I am in fact made of <span class="lessonlink" data-call="20-006">many straight lines</span>, though none last too long. In this way I have learned to ignore all true segments.'</p>
<p>Luckily, the sword not held was curved and therefore could cut into Moon Axle, and before the sun was up he was bleeding from many wounds. Vivec did not slay him outright for to do so would to <span class="lessonlink" data-call="20-009">keep the foibles of nature within him</span> and not back where they belonged. Soon Vivec had traced geography right again, and Moon Axle was ready to be slain.</p>
<p>Vivec rose up in his giant-form, to be terrible to look upon. He reached into the west and pulled out a canyon, holding it like a horn. He reached east and ate a handful of nix hounds. Blowing their spirits through the canyon made a terrible wail, <span class="lessonlink" data-call="20-010">not unlike an unsolved woman</span>. He said:</p>
<p>'Let this overtake you,' and Moon Axle was overtaken by the curvatures of stolen souls. They wrapped about the monster like resin, until finally he could not move, nor could his dual nature.</p>
<p>Vivec said, '<span class="lessonlink" data-call="20-011">Now you are solved</span>,' and pierced his child with Muatra. Moon Axle had been <span class="lessonlink" data-call="20-012">reduced to something static</span>, and therefore shattered.</p>
<p>The lines of Moon Axle were collected by Velothi philosophers and taken into caves. There, and for a year, Vivec taught the philosophers <span class="lessonlink" data-call="20-013">how to turn the lines of his son into the spokes of mystery wheels</span>. This was the birth of the first <span class="lessonlink" data-call="20-014">Whirling School</span>. Before, there had only been the <span class="lessonlink" data-call="20-015">surface thought of fire</span>.</p>
<p>Vivec looked at his first wheeling students and observed:</p>
<p>'<span class="lessonlink" data-call="20-016">Alike the egg-layered universe is this morbid possession of three-distant coverage</span>, <span class="lessonlink" data-call="20-017">soul-wrecked and alive, like my name is alive</span>. In this cloister you have discovered <span class="lessonlink" data-call="20-018">one walking path</span>, hilled like a sword but more coarsened. So edged it is that it has to be whispered to keep the tongue from bleeding, <span class="lessonlink" data-call="20-019">where its signs evacuate their former meanings, like empires that tarry too long</span>.</p>
<p>'<span class="lessonlink" data-call="20-020">The sword is estrangement from statesmanship</span>.</p>
<p>'Look on the estimable lines of my son, now crafted star-wise, his every limb equidistant from the center. <span class="lessonlink" data-call="20-021">Is he solved because I will it so</span>? <span class="lessonlink" data-call="20-022">There cannot be a second stage</span>. Think on the theory that <span class="lessonlink" data-call="20-023">my existence promulgates the five elements</span> and alike the egg-layered universe <span class="lessonlink" data-call="20-024">I am cause for great density</span>. Here is <span class="lessonlink" data-call="20-025">a thought that can break the wagon's axle</span>; here is another that can soar.'</p>
<p><span class="lessonlink" data-call="20-026">The ending of the words is ALMSIVI</span><a href="../css/images/36rages/<?php echo pad($sermon); ?>.png">.</a></p>
<div class="modal-hidden" id="dustdevils">
    <p><strong>DUST DEVILS</strong></p>
    <p>In the Wind of the mind arises the turbulence called I.</p>
    <p>It breaks; down shower the barren thoughts.</p>
    <p>All life is choked.</p>
    <p>This desert is the Abyss wherein is the Universe. The Stars are but thistles in that waste.</p>
    <p>Yet this desert is but one spot accursèd in a world of bliss.</p>
    <p>Now and again Travellers cross the desert; they come from the Great Sea, and to the Great Sea they go.</p>
    <p>As they go they spill water; one day they will irrigate the desert, till it flower.</p>
    <p>See! five footprints of a Camel! V. V. V. V. V.</p>
    <p><em>NWS Note: For commentary and an explanation of roughly what this means, <a class="external" href="https://www.bibliotecapleyades.net/crowley/lies/45.htm" target="_blank">start here</a>.</em></p>
</div>
<?php include 'footer.php' ?>