<?php
$sermon = '21';
include 'header.php';
?>
<div data-ident="21-000" class="commenthidden"><p>Finally we've reached Sermon 21, the Scripture of the Wheel, which we may have mentioned in every single Sermon up to this point.</p>
<p>What are the various ways that we can use the Wheel metaphor?</p>
<ul>
    <li>Kingdoms, etc, as in the Ruling Kings sermons.</li>
    <li>Vivec hirself, as a creation consisting of chaos contained by constraints.</li>
    <li>As a place in which a magician can construct a Tower.</li>
</ul>
<p>In Morrowind, Sermon 21 grants a bonus to the Light Armor skill. It is worth 200 septims and weighs 3 units. Copies can be found at the Ghostgate, in the <a href="https://en.uesp.net/wiki/Morrowind:Tower_of_Dawn" target="_blank" class="external">Tower of Dawn</a>, and in the <a href="https://en.uesp.net/wiki/Morrowind:Gnisis_Temple" target="_blank" class="external">Temple at Gnisis</a>.</p>
<p>Sermon 29 names this Sermon "The Womb." It's number is 13, which correlates to the word "of".</p>
</div>
<div data-ident="21-001" class="commenthidden"><p>It does seem odd to refer to the Aedra as components of "chaos" considering we usually associate them with Anuic forces, not Padomaic forces. And their role as component "laws" of reality only seems to reinforce that. But the roles they chose make them complicit in the chaotic nature of Mundus, which makes them components of that chaos.</p>
<p>And let's not ignore the fact that this Sermon has eight parts, one for each spoke of The Wheel.</p></div>
<div data-ident="21-002" class="commenthidden"><p>The Gods of the Tsaesci (the "lizard gods") creation myth involves an event they call "the Striking," which is the very first moment that the constant interchange between Anu and Padomay resulted in a discernible outcome. Or, in other words, a third presence. This exact moment is called "<a href="https://www.imperial-library.info/content/concerning-psijic-order-and-psijic-endeavor" target="_blank" class="external">PSJJJ</a>" by the Psijic Order, and represents both the very first moment of creation and the impulse to create it. The Argonians call it "<a href="https://www.imperial-library.info/content/more-psijic-endeavor" target="_blank" class="external">Exact Egg-Cracking</a>" because it refers to the perfect action that results in the perfect birth. The Egg, in this case, being the Egg of the Universe, which we've discussed all the way back in Sermon One. But as we've also discussed in Sermon Two, the Egg is a useful metaphysical symbol for a large number of things that transform (or hatch) into other things. Like Vivec, for example. When was Vivec's "exact egg-cracking," do you think?</p></div>
<div data-ident="21-003" class="commenthidden"><p>We've discussed the Earth as a fertility metaphor before, in Sermon 13, among others. Nirn is the "new star" in the respect that it was birthed by other, older stars, which are in this case the Aedra.</p></div>
<div data-ident="21-004" class="commenthidden"><p>Historically, Plato has referred to the Soul as a circle. Joseph Campbell (referencing Jung) suggests that the Ego is best represented by a square. The relationship between the two shares metaphysical concepts with a system ancient alchemists called "Squaring the Circle," where the four primary elements (represented by a circle) could be distilled and sublimated into a divine substance (represented by the circle). Similarly, <a href="https://youtu.be/1hcogiUUNnM" target="_blank" class="external">as explained by Joseph Campbell in this video</a>, the Square Ego exists within the Circle of the Self, and it is a square because it does not conform to the reasoning of the Self.</p></div>
<div data-ident="21-005" class="commenthidden"><p>Circles are infinite. If they could bite, they could make an end to things. A note about grammar: this is not to say that serpents are not given leave to bite, only that Circles resemble serpents with that problem.</p></div>
<div data-ident="21-006" class="commenthidden"><p>The world is a giant organism, as discussed in Sermon 17. Nirn's only purpose is to devour. Why? Mundus creates strife, pain, and suffering by design. It has to, for the same reason that the Fedaykin are the most powerful warriors in the galaxy. For the same reason that the sword causes pain when it slices away fat from lean. For the same reason that military training is so unpleasant. For the same reason that exercise hurts. Self-improvement must come at a cost, because that which is free is worth nothing. Every great event requires the pain of betrayal.</p>
<p>Mundus devours and mortals improve. From the pain of causality and death the inhabitants of Nirn become increasingly powerful. The threat of the kalpic cycle is removed by the Last Dragonborn and that, in turn, prevents the kalpa from "cheating" mortality by ending before the goal can be reached.</p></div>
<div data-ident="21-007" class="commenthidden"><p>On this, we can read at least two possible interpretations:</p>
<ol>
    <li>The enlightened are above the kalpic cycle, either by remaining after the turn, or by retaining memory of their previous selves. The "uneaten" could even refer to Alduin's consumption of Mundus at the end of every cycle.</li>
    <li>The enlightened do not allow the world define you. Aedric laws force the context of the world on you, and to realize the lie, to become enlightened, is to overcome mortal constraints.</li>
</ol></div>
<div data-ident="21-008" class="commenthidden"><p>A simplistic explanation is that "manticore" means "more than one thing at a time." So it's Series (sequential, ordered, differentiated) and Manticore (parallel, chaotic, amalgamated). Also, this is an explanation I figured out two years ago, in the shower, and then I forgot to write it down. Just remembered it.</p>
<p>The word "Manticore" may also refer to the novel "The Manticore." Of the book's title it is said:</p>
<blockquote>
    <p>The title refers to elements of the subconscious which unfold through the story and are eventually manifested as a fantastic mythical creature: a manticore.</p>
</blockquote>
<p>The collective subconscious manifests as something dangerous, with a chimerical visage showing bestial strength, but it yet has the face of a man. The lock and key denotes that the Daedric aligned spheres both obscure the meanings they represent behind menacing symbolic faces, but in their study can reveal hidden truths about the “human” condition.</p></div>
<div data-ident="21-009" class="commenthidden"><p>We all know Mer built towers, focal points for their culture. However, rather than a building, this is representative of a singular connected structure/identity of existence in the macrocosm.</p>
<p>Let's take a second to discuss the Tower card of the Tarot... In earlier renditions, the card is also called "The House of God", having etymological relation to the Hebrewic Bethel (the place where Jacob dreamt of Angels traveling to and from heaven via a ladder or staircase in Genesis 28 10-22). In both the traditional card's art, as well as in Crowley's Thoth deck, depicts a stone tower being destroyed by lightning and fire. Crowley also gave the card the synonym of "War", believing it to depict the nature of spiritual warfare. In both depictions, the Tower itself is believed to symbolize mentally constructed constraints, a symbol that the observer builds so that they may fit their perceived understanding of what "God" is into it. This symbol however is obstructive, reinforcing separation from the divine, so must be deconstructed in order to continue spiritual growth. Towers built as idols reflects this idea - they are physical (limited) constructions of divine (unlimited) ideas.</p>
<p>Therefore, we can state with some credibility that the Tower is built to house concepts but it is not the concept itself.</p>
<p>The separation of a concept from the rest of reality fits our current understanding of the Tower in Elder Scrolls metaphysics. In the Enantiomorphic structure, the Tower is the position of strength and protection from which the King defends that which the Thief covets.</p></div>
<div data-ident="21-010" class="commenthidden"><p>In the Book of the Law, Hadit describes himself as the "secret serpent." This is interesting, since Hadit has been interpreted as "the inner spirit of man, the Holy Ghost, the sperm in which the DNA of man is carried, the Elixir Vitae." In a way, Hadit can be considered to be every possible "point experience," which I assume is similar to the abstract concept of an "event."</p>
<p>All this seems to thematically link the Second Serpent to Akatosh, the Dragon God of time, if you assume that its counterpart is similar to Nuit (potential) and perhaps even by extension Lorkhan.</p>
<p>When you consider the "Serpents" in TES, it's easier to shift your frame of reference to the Yokuda, and the Monomyth, and the story of the Worldskin. Though it has been re-written through the lens of Yokudan culture, it's easy to follow the thread of the Anu / Padomay relationship. In Yokuda, the "First Serpent" is almost certainly Padomay. So when Tall Papa creates the "Second Serpent", and destroys it accordingly, it is reasonable to suggest that other cultures perceive this as the destruction of Lorkhan at the hands of Trinimac.</p>
<p>If we continue to follow that line of thought, the "Heart" of the Second Serpent might therefore be the Heart of Lorkhan. The connection with CHIM and divinity is easy to see, since this is the device that Almalexia, Sotha Sil, and Vivec used to become ALMSIVI, the three-faceted God of the Dunmer.</p></div>
<div data-ident="21-011" class="commenthidden"><p>The phallic symbolism behind the "right reaching" seems obvious to me. But it's worth considering the term from a more metaphysical angle. Right Reaching is a term that echoes the Tsaesci creation mythology's "exact egg-cracking." It's a purposeful act of will that initiates creation in a condition that is specifically waiting for that act. It's the key turning in the lock.</p></div>
<div data-ident="21-012" class="commenthidden"><p>A pure symbol without latter attributed meanings and associations.</p></div>
<div data-ident="21-013" class="commenthidden"><p>Explaining the "Secret Triangular Gate" is actually significantly harder than you might think. To truly do a thorough job of it would require an entirely new website, honestly. There's just so much symbolism and metaphysics to unpack there. But I think I did a fair job in my "<a href="../essays/enteringparadise.php">Entering Paradise, Our Mother</a>" essay, available on this site. So start there, and then we'll continue.</p></div>
<div data-ident="21-014" class="commenthidden"><p>Here, instead of looking at the Wheel sideways, we are looking at the secret of the Wheel. This means we are not looking at the true nature of the Aurbis, but rather at the secret of that nature. If you like, it is the perception of the consequences of that nature.</p>
<p>So, in total, to progress towards the secret "I" of God, you have to:</p>
<ol>
    <li>Visualize the Wheel, which requires a supernatural level of perception, or a physical position outside of the Aurbis, perhaps? It could be argued that the means are not as important as the result.</li>
    <li>Comprehend the Wheel, and what it means. Understand the way Mundus was created, and the sacrifices involved. True comprehension of the true nature of Mundus means you must also understand that you do not exist, and that you are only the distant echo of an ancient dream.</li>
    <li>Turn the Wheel sideways, and comprehend the Tower. This means you have realized that, within the nature of the universe, there is a deeper meaning, a hidden lesson. You look at it from the side, if you follow me. This "secret" is a Tower, because it contains a well-hidden treasure - that you can continue to exist, in the face of all logic and reason. You have to do the impossible, the insane, by turning all of existence sideways, before you can see things this way.</li>
</ol></div>
<div data-ident="21-015" class="commenthidden"><p>To find God is not to look out, but inside one's self, where one can find collective unity with the without. That is the lesson of the Universe card, which we discussed in the Entering Paradise essay, a card that ends the journey of the Fool through the Tarot's major arcana. To quote Crowley as he commented on the Universe card:</p>
<blockquote>
    <p>"You are whirling, caught up in the perpetual dancing motion of the universe."</p>
</blockquote>
<p>This is the origin of the name of the Whirling Schools formed by Vivec's followers in Sermon 20 - schools intended to teach the sense of oneness, to teach self-awareness before the loss of the Self, all to eventually impart the most valuable and sacred knowledge of the universe: the truth. This sermon, of course, is the lesson.</p>
<p>That is ultimately the story of the Fool. He starts ignorant, like a child, and gains the strength, humility, and wisdom needed to travel through death and temptation so that he can become impregnated with divine knowledge and be reborn.</p></div>
<div data-ident="21-016" class="commenthidden"><p>Well there's a lot to unpack here. This is one of the more complex Lessons, since it deals simultaneously with universe-spanning metaphysics and incredibly symbolic monsters. Intrinsically, the core of this sermon is about the superiority of metaphysical flexibility. But it's also about the relevance of inflexibility. Vivec's re-use of hir child's straight lines facilitated the creation of the Whirling School, which (in the Campbell mythic model) is the responsibility of every hero: distribution of stolen knowledge to their people.</p>
<p>We've also discovered a vital secret to Elder Scrolls metaphysics: an explanation of the purpose of a Tower. However, we're still left without an explanation of the purposes of a House, like The House of Troubles. Fortunately, Sermon 25 will answer that for us.</p></div>
<?php include 'middle.php' ?>
<p>The Scripture of the Wheel, First:</p>
<p>'The Spokes are <span class="lessonlink" data-call="21-001">the eight components of chaos</span>, as yet solidified by the law of time: <span class="lessonlink" data-call="21-002">static change, if you will, something the lizard gods refer to as the Striking</span>. That is the reptile wheel, coiled potential, ever-preamble to the never-action.'</p>
<p>Second:</p>
<p>'They are the lent bones of the Aedra, the Eight gift-limbs to SITHISIT, <span class="lessonlink" data-call="21-003">the wet earth of the new star our home</span>. Outside them is the Aurbis, and not within. <span class="lessonlink" data-call="21-004">Like most things inexplicable, it is a circle</span>. <span class="lessonlink" data-call="21-005">Circles are confused serpents</span>, striking and striking and never given leave to bite. <span class="lessonlink" data-call="21-006">The Aedra would have you believe different, but they were givers before liars</span>. Lies have turned them into biters. Their teeth are the proselytizers; to convert is to place oneself in the mouth of falsehood; even to propitiate is to be swallowed. '</p>
<p>Third:</p>
<p>'<span class="lessonlink" data-call="21-007">The enlightened are those uneaten by the world</span>.'</p>
<p>Fourth:</p>
<p>'The spaces between the gift-limbs number sixteen, the signal shapes of the Demon Princedoms. <span class="lessonlink" data-call="21-008">It is the key and the lock, series and manticore</span>.'</p>
<p>Fifth:</p>
<p>'Look at the majesty sideways and all you see is <span class="lessonlink" data-call="21-009">the Tower, which our ancestors made idols from</span>. Look at its center and all you see is the begotten hole, <span class="lessonlink" data-call="21-010">second serpent</span>, <span class="lessonlink" data-call="21-011">womb-ready for the Right Reaching</span>, <span class="lessonlink" data-call="21-012">exact and without enchantment</span>.'</p>
<p>Sixth:</p>
<p>'<span class="lessonlink" data-call="21-013">The heart of the second serpent holds the secret triangular gate</span>.'</p>
<p>Seventh:</p>
<p>'<span class="lessonlink" data-call="21-014">Look at the secret triangular gate sideways and you see the secret Tower</span>.'</p>
<p>Eighth:</p>
<p>'<span class="lessonlink" data-call="21-015">The secret Tower within the Tower is the shape of the only name of God, I</span>.'</p>
<p><span class="lessonlink" data-call="21-016">The ending of the words is ALMSIVI</span><a href="../css/images/36rages/<?php echo pad($sermon); ?>.png">.</a></p>
<?php include 'footer.php' ?>